var skills;
!function($, _, TweenMax, Object, undefined) {
	skills = {
		init,
		getName,
		notReady,
		getDefaults,
		lastData: {},
		roman: ['I', 'I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X'],
		oneHandSlash: {
			WAR: { max: 200, level: 1 },
			CRU: { max: 200, level: 1, },
			SHD: { max: 200, level: 1, },
			MNK: { max: 0, level: 0, },
			ROG: { max: 240, level: 1, },
			RNG: { max: 250, level: 1, },
			BRD: { max: 200, level: 1, },
			CLR: { max: 0, level: 0, },
			DRU: { max: 200, level: 1, },
			SHM: { max: 0, level: 0, },
			NEC: { max: 0, level: 0, },
			ENC: { max: 0, level: 0, },
			SUM: { max: 0, level: 0, },
			WIZ: { max: 0, level: 0, },
		},
		twoHandSlash: {
			WAR: { max: 200, level: 1 },
			CRU: { max: 200, level: 1, },
			SHD: { max: 200, level: 1, },
			MNK: { max: 0, level: 0, },
			ROG: { max: 0, level: 0, },
			RNG: { max: 225, level: 1, },
			BRD: { max: 0, level: 0, },
			CLR: { max: 0, level: 0, },
			DRU: { max: 0, level: 0, },
			SHM: { max: 0, level: 0, },
			NEC: { max: 0, level: 0, },
			ENC: { max: 0, level: 0, },
			SUM: { max: 0, level: 0, },
			WIZ: { max: 0, level: 0, },
		},
		oneHandBlunt: {
			WAR: { max: 200, level: 1 },
			CRU: { max: 200, level: 1, },
			SHD: { max: 200, level: 1, },
			MNK: { max: 250, level: 1, },
			ROG: { max: 225, level: 1, },
			RNG: { max: 240, level: 1, },
			BRD: { max: 200, level: 1, },
			CLR: { max: 200, level: 1, },
			DRU: { max: 200, level: 1, },
			SHM: { max: 200, level: 1, },
			NEC: { max: 200, level: 1, },
			ENC: { max: 200, level: 1, },
			SUM: { max: 200, level: 1, },
			WIZ: { max: 200, level: 1, },
		},
		twoHandBlunt: {
			WAR: { max: 200, level: 1 },
			CRU: { max: 200, level: 1, },
			SHD: { max: 200, level: 1, },
			MNK: { max: 250, level: 1, },
			ROG: { max: 225, level: 1, },
			RNG: { max: 240, level: 1, },
			BRD: { max: 200, level: 1, },
			CLR: { max: 200, level: 1, },
			DRU: { max: 200, level: 1, },
			SHM: { max: 200, level: 1, },
			NEC: { max: 200, level: 1, },
			ENC: { max: 200, level: 1, },
			SUM: { max: 200, level: 1, },
			WIZ: { max: 200, level: 1, },
		},
		piercing: {
			WAR: { max: 200, level: 1 },
			CRU: { max: 0, level: 0, },
			SHD: { max: 0, level: 0, },
			MNK: { max: 0, level: 0, },
			ROG: { max: 250, level: 1, },
			RNG: { max: 240, level: 1, },
			BRD: { max: 200, level: 1, },
			CLR: { max: 0, level: 0, },
			DRU: { max: 0, level: 0, },
			SHM: { max: 200, level: 1, },
			NEC: { max: 200, level: 1, },
			ENC: { max: 200, level: 1, },
			SUM: { max: 200, level: 1, },
			WIZ: { max: 200, level: 1, },
		},
		handToHand: {
			WAR: { max: 100, level: 1 },
			CRU: { max: 100, level: 1, },
			SHD: { max: 100, level: 1, },
			MNK: { max: 250, level: 1, },
			ROG: { max: 100, level: 1, },
			RNG: { max: 100, level: 1, },
			BRD: { max: 100, level: 1, },
			CLR: { max: 50, level: 1, },
			DRU: { max: 50, level: 1, },
			SHM: { max: 50, level: 1, },
			NEC: { max: 50, level: 1, },
			ENC: { max: 50, level: 1, },
			SUM: { max: 50, level: 1, },
			WIZ: { max: 50, level: 1, },
		},
		archery: {
			WAR: { max: 100, level: 1 },
			CRU: { max: 100, level: 1, },
			SHD: { max: 100, level: 1, },
			MNK: { max: 0, level: 0, },
			ROG: { max: 100, level: 1, },
			RNG: { max: 250, level: 1, },
			BRD: { max: 100, level: 1, },
			CLR: { max: 0, level: 0, },
			DRU: { max: 0, level: 0, },
			SHM: { max: 0, level: 0, },
			NEC: { max: 0, level: 0, },
			ENC: { max: 0, level: 0, },
			SUM: { max: 0, level: 0, },
			WIZ: { max: 0, level: 0, },
		},
		offense: {
			WAR: { max: 200, level: 1 },
			CRU: { max: 200, level: 1, },
			SHD: { max: 250, level: 1, },
			MNK: { max: 250, level: 1, },
			ROG: { max: 250, level: 1, },
			RNG: { max: 250, level: 1, },
			BRD: { max: 200, level: 1, },
			CLR: { max: 200, level: 1, },
			DRU: { max: 200, level: 1, },
			SHM: { max: 200, level: 1, },
			NEC: { max: 150, level: 1, },
			ENC: { max: 150, level: 1, },
			SUM: { max: 150, level: 1, },
			WIZ: { max: 150, level: 1, },
		},
		defense: {
			WAR: { max: 250, level: 1 },
			CRU: { max: 250, level: 1, },
			SHD: { max: 250, level: 1, },
			MNK: { max: 200, level: 1, },
			ROG: { max: 200, level: 1, },
			RNG: { max: 200, level: 1, },
			BRD: { max: 200, level: 1, },
			CLR: { max: 200, level: 1, },
			DRU: { max: 200, level: 1, },
			SHM: { max: 200, level: 1, },
			NEC: { max: 150, level: 1, },
			ENC: { max: 150, level: 1, },
			SUM: { max: 150, level: 1, },
			WIZ: { max: 150, level: 1, },
		},
		dodge: {
			WAR: { max: 150, level: 6 },
			CRU: { max: 150, level: 10, },
			SHD: { max: 150, level: 10, },
			MNK: { max: 150, level: 1, },
			ROG: { max: 200, level: 4, },
			RNG: { max: 150, level: 8, },
			BRD: { max: 200, level: 10, },
			CLR: { max: 100, level: 15, },
			DRU: { max: 100, level: 15, },
			SHM: { max: 100, level: 15, },
			NEC: { max: 100, level: 22, },
			ENC: { max: 100, level: 22, },
			SUM: { max: 100, level: 22, },
			WIZ: { max: 100, level: 22, },
		},
		parry: {
			WAR: { max: 250, level: 10 },
			CRU: { max: 250, level: 17, },
			SHD: { max: 200, level: 17, },
			MNK: { max: 150, level: 12, },
			ROG: { max: 150, level: 12, },
			RNG: { max: 200, level: 18, },
			BRD: { max: 0, level: 0, },
			CLR: { max: 0, level: 0, },
			DRU: { max: 0, level: 0, },
			SHM: { max: 0, level: 0, },
			NEC: { max: 0, level: 0, },
			ENC: { max: 0, level: 0, },
			SUM: { max: 0, level: 0, },
			WIZ: { max: 0, level: 0, },
		},
		riposte: {
			WAR: { max: 250, level: 25 },
			CRU: { max: 200, level: 30, },
			SHD: { max: 250, level: 30, },
			MNK: { max: 200, level: 35, },
			ROG: { max: 150, level: 30, },
			RNG: { max: 150, level: 35, },
			BRD: { max: 0, level: 0, },
			CLR: { max: 0, level: 0, },
			DRU: { max: 0, level: 0, },
			SHM: { max: 0, level: 0, },
			NEC: { max: 0, level: 0, },
			ENC: { max: 0, level: 0, },
			SUM: { max: 0, level: 0, },
			WIZ: { max: 0, level: 0, },
		},
		dualWield: {
			WAR: { max: 200, level: 13},
			CRU: { max: 0, level: 0, },
			SHD: { max: 0, level: 0, },
			MNK: { max: 250, level: 1, },
			ROG: { max: 250, level: 13, },
			RNG: { max: 250, level: 17, },
			BRD: { max: 200, level: 17, },
			CLR: { max: 0, level: 0, },
			DRU: { max: 0, level: 0, },
			SHM: { max: 0, level: 0, },
			NEC: { max: 0, level: 0, },
			ENC: { max: 0, level: 0, },
			SUM: { max: 0, level: 0, },
			WIZ: { max: 0, level: 0, },
		},
		doubleAttack: {
			WAR: { max: 200, level: 15 },
			CRU: { max: 250, level: 20, },
			SHD: { max: 250, level: 20, },
			MNK: { max: 250, level: 15, },
			ROG: { max: 250, level: 16, },
			RNG: { max: 250, level: 20, },
			BRD: { max: 0, level: 0, },
			CLR: { max: 0, level: 0, },
			DRU: { max: 0, level: 0, },
			SHM: { max: 0, level: 0, },
			NEC: { max: 0, level: 0, },
			ENC: { max: 0, level: 0, },
			SUM: { max: 0, level: 0, },
			WIZ: { max: 0, level: 0, },
		},
		alteration: {
			WAR: { max: 0, level: 0 },
			CRU: { max: 200, level: 1, },
			SHD: { max: 200, level: 1, },
			MNK: { max: 0, level: 0, },
			ROG: { max: 0, level: 0, },
			RNG: { max: 200, level: 1, },
			BRD: { max: 250, level: 1, },
			CLR: { max: 250, level: 1, },
			DRU: { max: 250, level: 1, },
			SHM: { max: 250, level: 1, },
			NEC: { max: 250, level: 1, },
			ENC: { max: 250, level: 1, },
			SUM: { max: 250, level: 1, },
			WIZ: { max: 250, level: 1, },
		},
		evocation: {
			WAR: { max: 0, level: 0 },
			CRU: { max: 200, level: 1, },
			SHD: { max: 200, level: 1, },
			MNK: { max: 0, level: 0, },
			ROG: { max: 0, level: 0, },
			RNG: { max: 200, level: 1, },
			BRD: { max: 250, level: 1, },
			CLR: { max: 250, level: 1, },
			DRU: { max: 250, level: 1, },
			SHM: { max: 250, level: 1, },
			NEC: { max: 250, level: 1, },
			ENC: { max: 250, level: 1, },
			SUM: { max: 250, level: 1, },
			WIZ: { max: 250, level: 1, },
		},
		conjuration: {
			WAR: { max: 0, level: 0 },
			CRU: { max: 200, level: 1, },
			SHD: { max: 200, level: 1, },
			MNK: { max: 0, level: 0, },
			ROG: { max: 0, level: 0, },
			RNG: { max: 200, level: 1, },
			BRD: { max: 250, level: 1, },
			CLR: { max: 250, level: 1, },
			DRU: { max: 250, level: 1, },
			SHM: { max: 250, level: 1, },
			NEC: { max: 250, level: 1, },
			ENC: { max: 250, level: 1, },
			SUM: { max: 250, level: 1, },
			WIZ: { max: 250, level: 1, },
		},
		WAR: [
			{
				name: 'Shield Bash',
				img: 'WAR-1',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				executionTime: 0,
				cooldownTime: 0,
				description: 'Shield-based attack that does % shield damage (interrupts when equipped shield)',
			}, {
				name: 'Primal Stomp',
				img: 'WAR-2',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Interrupt all targets and do small damage and high threat',
			}, {
				name: 'Jump Strike',
				img: 'WAR-3',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Leaping strike that makes warrior invincible while in the air',
			}, {
				name: 'Bulwark',
				img: 'WAR-4',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Defensive shield skill - boost all damage reduction for X seconds',
			}, {
				name: 'Whirlwind',
				img: 'WAR-5',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Hit cone of targets (max 3) for % of weapon damage',
			}, {
				name: 'Rupture',
				img: 'WAR-6',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Bleeds single target - all hits on this target receives damage bonus %',
			}, {
				name: 'Shockwave',
				img: 'WAR-7',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Hit all front row targets for % shield damage',
			}, {
				name: 'Pummel',
				img: 'WAR-8',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Single-target stun (glove % damage), large threat',
			}, {
				name: 'Double Throw',
				img: 'WAR-9',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Ranged arcane attack that strikes twice for % damage',
			}, {
				name: 'Frenzy',
				img: 'WAR-10',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Reduce execution time of skills for x seconds',
			}, {
				name: 'Commanding Shout',
				img: 'WAR-11',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Boost all resources of all allies for x seconds',
			}, {
				name: 'Furious Cleave',
				img: 'WAR-12',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Swing wildly hitting 3 targets for % damage - breaks+removes stuns and fear',
			},
		],
		CRU: [
			{
				name: 'Zealous Slam',
				img: 'CRU-1',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Shield-based attack, stuns target when shield equipped',
			}, {
				name: 'Rebuke',
				img: 'CRU-2',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Hits 3x targets - hits for x damage and interrupts all targets - bonus damage if interrupted',
			}, {
				name: 'Vengeance',
				img: 'CRU-3',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Hits for % damage - Hits harder when health is lower',
			}, {
				name: 'Conviction',
				img: 'CRU-4',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Hits for % damage - boosts stack of conviction up to 5x which gives resist all bonus',
			}, {
				name: 'Seal of Damnation',
				img: 'CRU-5',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Hits for % damage - Target marked with a Seal that boosts all damage on target by x%',
			}, {
				name: 'Seal of Redemption',
				img: 'CRU-6',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Hits for % damage - Target marked with a Seal that reduces all damage by x%',
			}, {
				name: 'Holy Wrath',
				img: 'CRU-7',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Hits target for % damage and stuns for x seconds',
			}, {
				name: 'Divine Judgment',
				img: 'CRU-8',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Strikes for X arcane damage - bonus to undead',
			}, {
				name: 'Blessed Hammer',
				img: 'CRU-9',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Strikes 3x targets for arcane damage',
			}, {
				name: 'Divine Grace',
				img: 'CRU-10',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Heal target for x amount',
			}, {
				name: 'Benevolence',
				img: 'CRU-11',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Heal all allies for X amount',
			}, {
				name: 'Jubilee',
				img: 'CRU-12',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Blast all targets with arcane damage (taunt reduce threat for everyone else)',
			},
		],
		SHD: [
			{
				name: 'Shield Strike',
				img: 'SHD-1',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Shield-based attack that does % shield damage (double damage when equipped shield)',
			}, {
				name: 'Death Strike',
				img: 'SHD-2',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Single-target strike that leaches health',
			}, {
				name: 'Crescent Cleave',
				img: 'SHD-3',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: '3x slice with strong taunt',
			}, {
				name: 'Brain Hew',
				img: 'SHD-4',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Strike for % damage and drain mana resources from target to yourself',
			}, {
				name: 'Iron Heron',
				img: 'SHD-5',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Ranged melee strike that silences for 6 seconds',
			}, {
				name: 'Mark of Remphan',
				img: 'SHD-6',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Marks a single target - Strike for % damage, extra threat, extra % damage on that target',
			}, {
				name: 'Ravaging Plague',
				img: 'SHD-7',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Strikes 3x targets with poison damage; hits for x ticks',
			}, {
				name: 'Decaying Doom',
				img: 'SHD-8',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Hits single target for X arcane damage; x ticks reduce armor by x and hits for x damage',
			}, {
				name: 'Blood Terror',
				img: 'SHD-9',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Hits 3x targets for x blood damage; fears targets for 8 seconds and hits for blood damage while feared',
			}, {
				name: 'Life Tap',
				img: 'SHD-10',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Single-target arcane health drain',
			}, {
				name: 'Vampiric Lust',
				img: 'SHD-11',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Hits all targets - arcane life drain and taunt',
			}, {
				name: 'Blood Feast',
				img: 'SHD-12',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Single-target blood curse that does X damage per tick; recover health if target dies while active',
			},
		],
		RNG: [
			{
				name: 'Cross Slash',
				img: 'RNG-1',
				enhancedDamage: [0, .55, .65, .75, .85, .95, 1.05, 1.15],
				spellType: '',
				castTime: 0,
				cooldownTime: 8,
				description: 'Hits 3 front row targets for % damage',
			}, {
				name: 'Explosive Shot',
				img: 'RNG-2',
				enhancedDamage: [0, .8, .9, 1, 1.1, 1.2, 1.3, 1.4],
				spellType: '',
				castTime: 0,
				cooldownTime: 15,
				description: 'Launch an explosive fire arrow at 3x targets',
			}, {
				name: 'Trueshot Strike',
				img: 'RNG-3',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 1.6, 1.75, 1.9, 2.05, 2.2, 2.35, 2.5],
				spellType: '',
				castTime: 0,
				cooldownTime: 20,
				description: 'Powerful single strike on single target (cannot dodge, parry, riposte)',
			}, {
				name: 'Spread Shot',
				img: 'RNG-4',
				enhancedDamage: [0, .33, .39, .45, .51, .57, .63, .69],
				spellType: '',
				castTime: 0,
				cooldownTime: 24,
				description: 'Hits up to 5x targets for % damage. Hits the front row first.',
			}, {
				name: 'Blade Storm',
				img: 'RNG-5',
				enhancedDamage: [0, .3, .34, .38, .42, .46, .5, .54],
				spellType: '',
				castTime: 0,
				cooldownTime: 15,
				description: 'Unleash a piercing five-hit combo on your target for % damage - Final blow hits for quad damage',
			}, {
				name: 'Suppressing Volley',
				img: 'RNG-6',
				enhancedDamage: [0, .45, .5, 55, .6, .65, .7, .75],
				spellType: '',
				castTime: 0,
				cooldownTime: 30,
				description: 'Hits 3x targets - Reduces your threat and mobs\' physical damage by 50% for 9 seconds',
			}, {
				name: 'Ignite',
				img: 'RNG-7',
				mp: level => spellValues.igniteMana[level],
				spellDamage: level => spellValues.ignite[level] + (my.level * 2),
				spellVariance: .8,
				spellType: 'evocation',
				damageType: 'fire',
				castTime: 2.5,
				cooldownTime: 0,
				description: 'Ignites the target for X damage. Reduces armor by 15% for 15 seconds',
			}, {
				name: 'Shock Nova',
				img: 'RNG-8',
				mp: level => spellValues.shockNovaMana[level],
				spellDamage: level => spellValues.shockNova[level] + my.level,
				spellVariance: .7,
				spellType: 'evocation',
				damageType: 'lightning',
				castTime: 1.5,
				cooldownTime: 0,
				description: 'Hits all targets for X lightning damage. Interrupts all spells.',
			}, {
				name: 'Faerie Flame',
				img: 'RNG-9',
				mp: level => spellValues.faerieFlameMana[level],
				spellDamage: level => spellValues.faerieFlame[level] + (my.level * 3),
				spellVariance: .85,
				spellType: 'conjuration',
				damageType: 'fire',
				castTime: 3,
				cooldownTime: 0,
				description: 'Mark a target - Direct fire damage and reduces miss chance by 15% for 45 seconds',
			}, {
				name: 'Fungal Growth',
				img: 'RNG-10',
				sp: level => spellValues.fungalGrowthMana[level],
				spellDamage: level => spellValues.fungalGrowth[level] + (my.level),
				spellVariance: .95,
				spellType: 'alteration',
				damageType: 'arcane',
				castTime: 2,
				cooldownTime: 0,
				description: 'Restores x health over time for 30 seconds',
			}, {
				name: 'Shimmering Orb',
				img: 'RNG-11',
				sp: level => spellValues.shimmeringOrbMana[level],
				spellDamage: level => spellValues.shimmeringOrb[level],
				magMit: [0, 2, 4, 7, 9, 12, 15, 19],
				spellVariance: 1,
				spellType: 'conjuration',
				castTime: 4,
				cooldownTime: 5,
				description: 'Conjure a shimmering orb that shields your target. Reduces magical damage received by X per hit. Absorbs a total of X damage.',
			}, {
				name: 'Spirit of the Hunter',
				img: 'RNG-12',
				sp: level => spellValues.spiritOfTheHunterMana[level],
				spellDamage: level => spellValues.spiritOfTheHunter[level],
				spellVariance: 1,
				spellType: 'alteration',
				castTime: 3.5,
				cooldownTime: 15,
				description: 'Boost your attack by X by X and receive 20% attack haste for X seconds.',
			},
		],
		MNK: [
			{
				name: 'Tiger Strike',
				img: 'MNK-1',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, .8, .9, 1, 1.1, 1.2, 1.3, 1.4],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Strike for % damage - +1 Chi',
			}, {
				name: 'Hyper Strike',
				img: 'MNK-2',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, .8, .9, 1, 1.1, 1.2, 1.3, 1.4],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Strike for % damage and receive % haste - +1 Chi',
			}, {
				name: 'Viper Strike',
				img: 'MNK-3',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, .8, .9, 1, 1.1, 1.2, 1.3, 1.4],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Strike for % damage and leech extra health - +1 Chi',
			}, {
				name: 'Mime Strike',
				img: 'MNK-4',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, .8, .9, 1, 1.1, 1.2, 1.3, 1.4],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Hit for % damage - Next attack hits twice - +1 Chi',
			}, {
				name: 'Crane Kick',
				img: 'MNK-5',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, .8, .9, 1, 1.1, 1.2, 1.3, 1.4],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Strikes target for % damage - Interrupts -1 chi',
			}, {
				name: 'Feign Death',
				img: 'MNK-6',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, .8, .9, 1, 1.1, 1.2, 1.3, 1.4],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Reduces threat with all targets -1 chi',
			}, {
				name: 'Palm Strike',
				img: 'MNK-7',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, .8, .9, 1, 1.1, 1.2, 1.3, 1.4],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Delivers a powerful blow for % damage - Stuns for 2 seconds -2 chi',
			}, {
				name: 'Hurricane Kicks',
				img: 'MNK-8',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, .8, .9, 1, 1.1, 1.2, 1.3, 1.4],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Hit 3x targets -2 chi',
			}, {
				name: 'Dragon Punch',
				img: 'MNK-9',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, .8, .9, 1, 1.1, 1.2, 1.3, 1.4],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Hits front row target for % fire damage -2 chi',
			}, {
				name: 'Hadoken',
				img: 'MNK-10',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, .8, .9, 1, 1.1, 1.2, 1.3, 1.4],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Ranged fireball attack that hits for x % damage -2 chi',
			}, {
				name: 'Chakra Blast',
				img: 'MNK-11',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, .8, .9, 1, 1.1, 1.2, 1.3, 1.4],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Explode and hit all targets for X arcane damage -3 chi',
			}, {
				name: 'Spirit Barrier',
				img: 'MNK-12',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, .8, .9, 1, 1.1, 1.2, 1.3, 1.4],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'Protect yourself in a spirit barrier that reduces all damage by 50% for x seconds -3 chi',
			},
		],
		ROG: [
			{
				name: 'Shadow Strike',
				img: 'ROG-1',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, .8, .9, 1, 1.1, 1.2, 1.3, 1.4],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Sonic Strike',
				img: 'ROG-2',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, .8, .9, 1, 1.1, 1.2, 1.3, 1.4],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Faded Strike',
				img: 'ROG-3',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Manic Strike',
				img: 'ROG-4',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Lacerate',
				img: 'ROG-5',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Backstab',
				img: 'ROG-6',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Widow Strike',
				img: 'ROG-7',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Stagger Shot',
				img: 'ROG-8',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Evade',
				img: 'ROG-9',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Flash Powder',
				img: 'ROG-10',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Talisman',
				img: 'ROG-11',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Prowl',
				img: 'ROG-12',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			},
		],
		DRU: [
			{
				name: 'Starfire',
				img: 'DRU-1',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Fissure',
				img: 'DRU-2',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Lightning Blast',
				img: 'DRU-3',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Blizzard',
				img: 'DRU-4',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Toxic Spores',
				img: 'DRU-5',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Molten Boulder',
				img: 'DRU-6',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Barbed Thicket',
				img: 'DRU-7',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Tornado',
				img: 'DRU-8',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Nature\'s Touch',
				img: 'DRU-9',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Moss Breath',
				img: 'DRU-10',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Synthesize',
				img: 'DRU-11',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Branch Spirit',
				img: 'DRU-12',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			},
		],
		CLR: [
			{
				name: 'Smite',
				img: 'CLR-1',
				mp: level => spellValues.smiteMana[level],
				spellDamage: level => spellValues.smite[level] + (my.level * 1.5),
				spellVariance: .825,
				spellType: 'evocation',
				damageType: 'arcane',
				castTime: 3,
				cooldownTime: 0,
				description: 'Smite your target for X arcane damage.',
			}, {
				name: 'Deliverance',
				img: 'CLR-2',
				mp: [0, 4, 10, 23, 42, 66, 85, 98],
				mp: level => spellValues.deliveranceMana[level],
				spellDamage: level => spellValues.deliverance[level] + (my.level * 2),
				spellVariance: .9,
				spellType: 'evocation',
				damageType: 'fire',
				castTime: 2,
				cooldownTime: 6,
				description: 'Single-target arcane damage - +50% damage to undead and demons.',
			}, {
				name: 'Condemnation',
				img: 'CLR-3',
				mp: level => spellValues.condemnationMana[level],
				spellDamage: level => spellValues.condemnation[level] + (my.level * 2),
				spellVariance: .875,
				spellType: 'evocation',
				damageType: 'arcane',
				castTime: 3.5,
				cooldownTime: 12,
				description: 'Hit 3x targets arcane damage - +50% damage to undead, demons.',
			}, {
				name: 'Sacred Revelation',
				img: 'CLR-4',
				mp: level => spellValues.sacredRevelationMana[level],
				spellDamage: level => spellValues.sacredRevelation[level] + (my.level * 1.5),
				spellVariance: .95,
				spellType: 'evocation',
				damageType: 'arcane',
				castTime: 1.5,
				cooldownTime: 30,
				description: 'Hits 3x targets for X arcane damage and stuns them for 3 seconds.',
			}, {
				name: 'Holy Sanctuary',
				img: 'CLR-5',
				mp: level => spellValues.holySanctuaryMana[level],
				spellDamage: level => spellValues.holySanctuary[level],
				spellVariance: .9,
				spellType: 'conjuration',
				damageType: 'arcane',
				castTime: 1.5,
				cooldownTime: 24,
				description: 'Blast all targets with arcane damage and reduce threat by X.',
			}, {
				name: 'Force of Glory',
				img: 'CLR-6',
				mp: level => spellValues.forceOfGloryMana[level],
				spellDamage: level => spellValues.forceOfGlory[level] + (my.level),
				spellVariance: .9,
				spellType: 'conjuration',
				damageType: 'arcane',
				castTime: 1,
				cooldownTime: 60,
				description: 'Powerful Strike a single target with X arcane damage - Stuns for 5 seconds.',
			}, {
				name: 'Binding Grace',
				img: 'CLR-7',
				sp: level => spellValues.bindingGraceMana[level],
				spellDamage: level => spellValues.bindingGrace[level] + (my.level),
				spellVariance: .9,
				spellType: 'alteration',
				damageType: 'arcane',
				castTime: 4,
				cooldownTime: 8,
				description: 'Caster and target are healed for X damage.',
			}, {
				name: 'Guardian Angel',
				img: 'CLR-8',
				sp: level => spellValues.guardianAngelMana[level],
				spellDamage: level => spellValues.guardianAngel[level] + (my.level),
				spellVariance: .95,
				spellType: 'conjuration',
				damageType: 'arcane',
				castTime: 1.5,
				cooldownTime: 24,
				description: 'Protect target with a holy shield that absorbs X damage - cannot be feared while effect is active.',
			}, {
				name: 'Divine Light',
				img: 'CLR-9',
				sp: level => spellValues.divineLightMana[level],
				spellDamage: level => spellValues.divineLight[level] + (my.level),
				spellVariance: .9,
				spellType: 'alteration',
				damageType: 'arcane',
				castTime: 3,
				cooldownTime: 0,
				description: 'Heal target for X health.',
			}, {
				name: 'Circle of Prayer',
				img: 'CLR-10',
				sp: level => spellValues.circleOfPrayerMana[level],
				spellDamage: level => spellValues.circleOfPrayer[level] + (my.level),
				spellVariance: .9,
				spellType: 'alteration',
				damageType: 'arcane',
				castTime: 4,
				cooldownTime: 0,
				description: 'Heals all party members for X health.',
			}, {
				name: 'Seal of Redemption',
				img: 'CLR-11',
				sp: level => spellValues.sealOfRedemptionMana[level],
				spellDamage: level => spellValues.sealOfRedemption[level] + (my.level * 2),
				spellVariance: .875,
				spellType: 'alteration',
				damageType: 'arcane',
				castTime: 2.5,
				cooldownTime: 0,
				description: 'Smite your target for X arcane damage.',
			}, {
				name: 'Zealous Resolve',
				img: 'CLR-12',
				sp: [0, 5, 12, 29, 52, 77, 99, 115],
				spellDamage: level => spellValues.zealousResolve[level] + (my.level * 2),
				spellVariance: .875,
				spellType: 'alteration',
				damageType: 'arcane',
				castTime: 2.5,
				cooldownTime: 0,
				description: 'Smite your target for X arcane damage.',
			},
		],
		SHM: [
			{
				name: 'Frost Rift',
				img: 'SHM-1',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Poison Nova',
				img: 'SHM-2',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Scourge',
				img: 'SHM-3',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Poison Bolt',
				img: 'SHM-4',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Vampiric Gaze',
				img: 'SHM-5',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Glacial Shard',
				img: 'SHM-6',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Affliction',
				img: 'SHM-7',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Devouring Swarm',
				img: 'SHM-8',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Rejuvinate',
				img: 'SHM-9',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Mystical Glow',
				img: 'SHM-10',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Vampiric Allure',
				img: 'SHM-11',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Boreal Talisman',
				img: 'SHM-12',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			},
		],
		BRD: [
			{
				name: 'Bellow',
				img: 'BRD-1',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Sonic Boom',
				img: 'BRD-2',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Euphonic Dirge',
				img: 'BRD-3',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Subverted Symphony',
				img: 'BRD-4',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Chords of Confusion',
				img: 'BRD-5',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Battle Hymn',
				img: 'BRD-6',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Victory Jaunt',
				img: 'BRD-7',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Shackle Chords',
				img: 'BRD-8',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Littany of Life',
				img: 'BRD-9',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Melody of Mana',
				img: 'BRD-10',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Sonnet of Steel',
				img: 'BRD-11',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Chromatic Sonnet',
				img: 'BRD-12',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			},
		],
		NEC: [
			{
				name: 'Venom Bolt',
				img: 'NEC-1',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Explosive Plague',
				img: 'NEC-2',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Blood Fire',
				img: 'NEC-3',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Demonic Pact',
				img: 'NEC-4',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Haunting Vision',
				img: 'NEC-5',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Summon Skeleton',
				img: 'NEC-6',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Sanguine Pact',
				img: 'NEC-7',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Gleam of Madness',
				img: 'NEC-8',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Drain Soul',
				img: 'NEC-9',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Breath of the Dead',
				img: 'NEC-10',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Engulfing Darkness',
				img: 'NEC-11',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Defiled Spirit',
				img: 'NEC-12',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			},
		],
		ENC: [
			{
				name: 'Gravity Flux',
				img: 'ENC-1',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Phase Blade',
				img: 'ENC-2',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Suffocation',
				img: 'ENC-3',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Mind Blitz',
				img: 'ENC-4',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Subversion',
				img: 'ENC-5',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Color Shift',
				img: 'ENC-6',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Stasis Field',
				img: 'ENC-7',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Shifting Ether',
				img: 'ENC-8',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Rune',
				img: 'ENC-9',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Augmentation',
				img: 'ENC-10',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Clarity',
				img: 'ENC-11',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Enthrall',
				img: 'ENC-12',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			},
		],
		SUM: [
			{
				name: 'Lava Bolt',
				img: 'SUM-1',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Frozen Orb',
				img: 'SUM-2',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Static Storm',
				img: 'SUM-3',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Fire Wall',
				img: 'SUM-4',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Glacial Spike',
				img: 'SUM-5',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Golem Sludge',
				img: 'SUM-6',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Summon Golem',
				img: 'SUM-7',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Golem Fury',
				img: 'SUM-8',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Golem Drain',
				img: 'SUM-9',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Lava Shield',
				img: 'SUM-10',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Lucid Synergy',
				img: 'SUM-11',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Elemental Focus',
				img: 'SUM-12',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			},
		],
		WIZ: [
			{
				name: 'Fire Bolt',
				img: 'WIZ-1',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Ice Bolt',
				img: 'WIZ-2',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Lightning Bolt',
				img: 'WIZ-3',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Magic Missiles',
				img: 'WIZ-4',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Fireball',
				img: 'WIZ-5',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Chain Lightning',
				img: 'WIZ-6',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Frost Nova',
				img: 'WIZ-7',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Meteor',
				img: 'WIZ-8',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Ice Block',
				img: 'WIZ-9',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Mirror Images',
				img: 'WIZ-10',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Counterspell',
				img: 'WIZ-11',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			}, {
				name: 'Brain Freeze',
				img: 'WIZ-12',
				mp: [0, 0, 0, 0, 0, 0, 0, 0],
				sp: [0, 0, 0, 0, 0, 0, 0, 0],
				enhancedDamage: [0, 0, 0, 0, 0, 0, 0, 0],
				spellType: '',
				castTime: 0,
				cooldownTime: 0,
				description: 'LoremIpsum',
			},
		],
	}
	// HoT 3-4 sp/heal
	// DIRECT HEALING 2-3 spirit per heal
	// AE HEALING .5-1.25 sp/heal

	// DOT 3-5 mp/d
	// DIRECT DAMAGE 2-4 m/d
	// AE DAMAGE 1.5-3 m/d
	const spellValues = {
		igniteMana: [0, 5, 12, 29, 52, 77, 99, 115], // mp:  3
		ignite: [0, 15, 37, 88, 156, 231, 298, 347],
		shockNovaMana: [0, 7, 14, 33, 58, 86, 110, 127], // mp:  1.3?
		shockNova: [0, 9, 20, 47, 81, 123, 152, 179],
		faerieFlameMana: [0, 8, 17, 41, 72, 107, 137, 158], // mp:  2.1?
		faerieFlame: [0, 19, 49, 117, 207, 307, 396, 461],
		fungalGrowthMana: [0, 7, 14, 31, 57, 85, 106, 127], // sp:  3?
		fungalGrowth: [0, 21, 42, 95, 172, 255, 318, 382],
		shimmeringOrbMana: [0, 9, 18, 40, 74, 110, 137, 165],
		shimmeringOrb: [0, 33, 67, 152, 275, 408, 508, 611],
		spiritOfTheHunterMana: [0, 13, 27, 60, 111, 165, 205, 247],
		spiritOfTheHunter: [0, 4, 8, 13, 19, 26, 34, 45],
		// cleric
		smiteMana: [0, 6, 13, 31, 57, 84, 108, 126], // mp: 3.3
		smite: [0, 18, 44, 105, 187, 277, 357, 416],
		deliveranceMana: [0, 4, 10, 23, 42, 66, 85, 98], // mp:  2.8
		deliverance: [0, 14, 33, 76, 140, 220, 284, 328],
		condemnationMana: [0, 8, 18, 41, 72, 105, 135, 157],
		condemnation: [0, 16, 39, 88, 154, 225, 291, 341], //  1.6
		sacredRevelationMana: [0, 7, 16, 36, 64, 94, 121, 141],
		sacredRevelation: [0, 10, 24, 54, 96, 141, 181, 211],
		holySanctuaryMana: [0, 5, 9, 23, 41, 58, 76, 88],
		holySanctuary: [0, 9, 22, 52, 93, 138, 178, 208], // negative hate
		forceOfGloryMana: [0, 7, 15, 33, 60, 88, 112, 130],
		forceOfGlory: [0, 20, 45, 111, 196, 288, 348, 415],
		bindingGraceMana: [0, 10, 22, 49, 90, 132, 168, 195],
		bindingGrace: [0, 21, 46, 102, 189, 277, 352, 409],
		guardianAngelMana: [0, 8, 17, 39, 72, 105, 134, 156],
		guardianAngel: [0, 20, 42, 97, 180, 262, 335, 390],
		divineLightMana: [0, 8, 18, 41, 76, 112, 142, 165],
		divineLight: [0, 24, 54, 123, 228, 336, 426, 495],
		circleOfPrayerMana: [0, 12, 27, 65, 119, 176, 226, 264],
		circleOfPrayer: [0, 14, 32, 78, 142, 211, 271, 316],
		sealOfRedemptionMana: [0, 0, 0, 0, 0, 0, 0, 0],
		sealOfRedemption: [0, 0, 0, 0, 0, 0, 0, 0],
		zealousResolveMana: [0, 0, 0, 0, 0, 0, 0, 0],
		zealousResolve: [0, 0, 0, 0, 0, 0, 0, 0],
	}

	///////////////////////////////////////////
	function init() {
		skills.skillNames = getClassKeys()
		Object.keys(ng.jobLong).forEach((job) => {
			skills[job].forEach((skill, index) => {
				skills[job][index].index = index
			})
		})
	}
	function getName(prop) {
		return (item.specialPropLabels[prop] || _.capitalize(prop))
	}
	function getClassKeys() {
		return skills[my.job].map(o => o.name)
	}
	function notReady(config, data = {}) {
		if (timers.castBar < 1 ||
			(config.global && timers.globalCooldown < 1) ||
			(config.skillIndex >= 0 && timers.skillCooldowns[config.skillIndex] < 1) ||
			my.skills[config.skillIndex] === 0) return true

		// targeting
		if (config.anyTarget) {
			// A OK
		}
		else {
			if (config.isMob) {
				if (!my.targetIsMob) {
					chat.log('You must target a mob with this skill.', 'chat-warning')
					return true
				}
			}
			else {
				if (my.targetIsMob) {
					chat.log('You must target a player with this skill.', 'chat-warning')
					return true
				}
				if (config.targetOther && my.target === my.row) {
					chat.log('You must target a party member with this skill.', 'chat-warning')
					return true
				}
			}
			if (config.fixTarget) {
				if (config.isMob) my.fixTarget()
				else {
					my.partyTarget(0)
				}
				if (my.target === -1) {
					chat.log('There are no valid targets for this skill.', 'chat-warning')
					return true
				}
			}
			if (my.target === -1) {
				chat.log('You must select a target to use this skill.', 'chat-warning')
				return true
			}
		}

		if (!config.oocEnabled &&
			ng.view !== 'battle') {
			chat.log('You cannot use this skill out of combat.', 'chat-warning')
			return true
		}
		if (config.requiresFrontRow && my.target > 4) {
			chat.log('This skill can only target the front row!', 'chat-warning')
			return true
		}
		if (config.mpCost) {
			if (config.mpCost > my.mp) {
				chat.log('Not enough mana for ' + config.name + '!', 'chat-warning')
				return true
			}
		}
		if (config.spCost) {
			if (config.spCost > my.sp) {
				chat.log('Not enough spirit for ' + config.name + '!', 'chat-warning')
				return true
			}
		}
		// SUCCESS!
		// set last data used for spell completed reference
		skills.lastData = data
		return false
	}
	function getDefaults(skillIndex) {
		return {
			skillIndex: skillIndex,
			global: true,
			isMob: true,
		}
	}
}($, _, TweenMax, Object);