// primitives
const MAX_HERO_LEVEL = 50
const MAX_WIDTH = 1920
const MAX_HEIGHT = 1080
const ASPECT_RATIO = MAX_WIDTH / MAX_HEIGHT
const PARALYZE_RATE = .5
const RESIST_CAP = 100
const EMPTY_OBJECT = {}
const HALLWAY_WIDTH = 16
const HALLWAY_LENGTH = 100
let HALLWAY_START = 0
const MAX_GOLD = 4294967295

const POTION_COOLDOWN = 15
const MAX_SKILL_LEVEL = 7

const HybridJobs = [JOB.CRUSADER, JOB.SHADOW_KNIGHT, JOB.RANGER]