const TYPE = Object.freeze({
	OBJECT: 'object',
	STRING: 'string',
	NUMBER: 'number',
	FUNCTION: 'function',
})
const CHAT = Object.freeze({
	SAY: { mode: '/say' },
	PARTY: { mode: '/party' },
})
const CSS = Object.freeze({
	ACTIVE: 'active',
	DISABLED: 'disabled',
	CHAT_WARNING: 'chat-warning',
	CHAT_ALERT: 'chat-alert',
	CASTBAR_ZERO: { castBar: 0 },
	X_ZERO: { x: '-100%' },
	DISPLAY_BLOCK: { display: 'block' },
	DISPLAY_NONE: { display: 'none' },
	DISPLAY_FLEX: { display: 'flex' },
})
const JOB = Object.freeze({
	BARD: 'BRD',
	CLERIC: 'CLR',
	CRUSADER: 'CRU',
	DRUID: 'DRU',
	ENCHANTER: 'ENC',
	MONK: 'MNK',
	RANGER: 'RNG',
	ROGUE: 'ROG',
	SHADOW_KNIGHT: 'SHD',
	SHAMAN: 'SHM',
	TEMPLAR: 'TMP',
	WARLOCK: 'WLK',
	WARRIOR: 'WAR',
	WIZARD: 'WIZ',
})
const CLASS = Object.freeze({
	BARD: 'Bard',
	CLERIC: 'Cleric',
	CRUSADER: 'Crusader',
	DRUID: 'Druid',
	ENCHANTER: 'Enchanter',
	MONK: 'Monk',
	RANGER: 'Ranger',
	ROGUE: 'Rogue',
	SHADOW_KNIGHT: 'Shadow Knight',
	SHAMAN: 'Shaman',
	TEMPLAR: 'Templar',
	WARLOCK: 'Warlock',
	WARRIOR: 'Warrior',
	WIZARD: 'Wizard',
})
const KEYS = Object.freeze({
	DATA: ['data'],
	NAME: ['name'],
	ID: ['id'],
	INDEX: ['index'],
	RANK: ['rank'],
	MOB_OMIT: [ 'maxLevel', 'minLevel', ],
	SET_FACE: [ 'gender', 'race', 'face' ],
	ITEM_ENTER: [ 'index', 'type' ],
	PLAYER_CLICK: [ 'row', 'name' ],
	DAMAGE_MOB: [ 'damage', 'key', 'index', 'row', 'effects' ],
	DOT_MOB: [ 'damage', 'index', 'level' ],
	HEAL_HERO: ['damage', 'index', 'key'],
	BUFF_HERO: ['damage', 'index', 'key', 'level'],
	PARTY_PROPS: [
		'name',
		'hp',
		'hpMax',
		'mp',
		'mpMax',
		'sp',
		'spMax',
		'job',
		'partyId',
		'avatar'
	],
	MY_PROPS: [
		'str',
		'sta',
		'agi',
		'dex',
		'wis',
		'intel',
		'cha',
		'offense',
		'defense',
		'oneHandSlash',
		'twoHandSlash',
		'oneHandBlunt',
		'twoHandBlunt',
		'piercing',
		'archery',
		'handToHand',
		'dodge',
		'parry',
		'riposte',
		'dualWield',
		'doubleAttack',
		'alteration',
		'conjuration',
		'evocation',
		'skills',
	],
})