// mob type specific stats
mob.type = {
	balrog: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.DEMON,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'balrog-attack',
		sfxHit: 'balrog-hit',
		sfxDeath: 'balrog-death',
		sfxIdle: 'balrog-idle',
		sfxSpecial: 'balrog-special',
	},
	'ice-golem': {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.MYSTICAL,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'golem-attack',
		sfxHit: 'golem-hit',
		sfxDeath: 'golem-death',
		sfxIdle: 'golem-idle',
		sfxSpecial: undefined,
	},
	'stone-golem': {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.MYSTICAL,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'golem-attack',
		sfxHit: 'golem-hit',
		sfxDeath: 'golem-death',
		sfxIdle: 'golem-idle',
		sfxSpecial: undefined,
	},
	'iron-golem': {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.MYSTICAL,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'golem-attack',
		sfxHit: 'golem-hit',
		sfxDeath: 'golem-death',
		sfxIdle: 'golem-idle',
		sfxSpecial: undefined,
	},
	treant: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.MYSTICAL,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'treant-attack',
		sfxHit: 'treant-hit',
		sfxDeath: 'treant-death',
		sfxIdle: 'treant-idle',
		sfxSpecial: 'treant-special',
	},
	spider: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.BEAST,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'spider-attack',
		sfxHit: 'spider-hit',
		sfxDeath: 'spider-death',
		sfxIdle: 'spider-idle',
		sfxSpecial: undefined,
	},
	wolf: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.BEAST,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'wolf-attack',
		sfxHit: 'wolf-hit',
		sfxDeath: 'wolf-death',
		sfxIdle: 'wolf-idle',
		sfxSpecial: undefined,
	},
	rat: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.BEAST,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'rat-attack',
		sfxHit: 'rat-hit',
		sfxDeath: 'rat-death',
		sfxIdle: 'rat-idle',
		sfxSpecial: undefined,
	},
	snake: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.BEAST,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'snake-attack',
		sfxHit: 'snake-hit',
		sfxDeath: 'snake-death',
		sfxIdle: 'snake-idle',
		sfxSpecial: undefined,
	},
	dragonkin: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.DRAGONKIN,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'centaur-attack',
		sfxHit: 'centaur-hit',
		sfxDeath: 'centaur-death',
		sfxIdle: undefined,
		sfxSpecial: undefined,
	},
	lizardman: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.HUMANOID,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'lizardman-attack',
		sfxHit: 'lizardman-hit',
		sfxDeath: 'lizardman-death',
		sfxIdle: 'lizardman-idle',
		sfxSpecial: 'lizardman-special',
	},
	dragon: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.DRAGONKIN,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'dragon-attack',
		sfxHit: 'dragon-hit',
		sfxDeath: 'dragon-death',
		sfxIdle: 'dragon-idle',
		sfxSpecial: 'dragon-special',
	},
	'dragon-fire': {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.DRAGONKIN,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'dragon-attack',
		sfxHit: 'dragon-hit',
		sfxDeath: 'dragon-death',
		sfxIdle: 'dragon-idle',
		sfxSpecial: 'dragon-special',
	},
	'dragon-poison': {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.DRAGONKIN,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'dragon-attack',
		sfxHit: 'dragon-hit',
		sfxDeath: 'dragon-death',
		sfxIdle: 'dragon-idle',
		sfxSpecial: 'dragon-special',
	},
	'dragon-frost': {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.DRAGONKIN,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'dragon-attack',
		sfxHit: 'dragon-hit',
		sfxDeath: 'dragon-death',
		sfxIdle: 'dragon-idle',
		sfxSpecial: 'dragon-special',
	},
	'dragon-plains': {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.DRAGONKIN,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'dragon-attack',
		sfxHit: 'dragon-hit',
		sfxDeath: 'dragon-death',
		sfxIdle: 'dragon-idle',
		sfxSpecial: 'dragon-special',
	},
	'dragon-water': {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.DRAGONKIN,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'dragon-attack',
		sfxHit: 'dragon-hit',
		sfxDeath: 'dragon-death',
		sfxIdle: 'dragon-idle',
		sfxSpecial: 'dragon-special',
	},
	'dragon-forest': {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.DRAGONKIN,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'dragon-attack',
		sfxHit: 'dragon-hit',
		sfxDeath: 'dragon-death',
		sfxIdle: 'dragon-idle',
		sfxSpecial: 'dragon-special',
	},
	'dragon-desert': {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.DRAGONKIN,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'dragon-attack',
		sfxHit: 'dragon-hit',
		sfxDeath: 'dragon-death',
		sfxIdle: 'dragon-idle',
		sfxSpecial: 'dragon-special',
	},
	ghoul: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.UNDEAD,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'ghoul-attack',
		sfxHit: 'ghoul-hit',
		sfxDeath: 'ghoul-death',
		sfxIdle: undefined,
		sfxSpecial: 'ghoul-special',
	},
	mummy: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.UNDEAD,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'zombie-attack',
		sfxHit: 'zombie-hit',
		sfxDeath: 'zombie-death',
		sfxIdle: 'zombie-idle',
		sfxSpecial: undefined,
	},
	skeleton: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.UNDEAD,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'skeleton-attack',
		sfxHit: 'skeleton-hit',
		sfxDeath: 'skeleton-death',
		sfxIdle: undefined,
		sfxSpecial: 'skeleton-special',
	},
	'zombie': {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.UNDEAD,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'zombie-attack',
		sfxHit: 'zombie-hit',
		sfxDeath: 'zombie-death',
		sfxIdle: 'zombie-idle',
		sfxSpecial: undefined,
	},
	vampire: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.UNDEAD,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'vampire-attack',
		sfxHit: 'vampire-hit',
		sfxDeath: 'vampire-death',
		sfxIdle: 'vampire-attack',
		sfxSpecial: 'vampire-special',
	},
	goblin: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.HUMANOID,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'goblin-attack',
		sfxHit: 'goblin-hit',
		sfxDeath: 'goblin-death',
		sfxIdle: 'goblin-attack',
		sfxSpecial: 'goblin-special',
	},
	hobgoblin: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.HUMANOID,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'rhino-attack',
		sfxHit: 'rhino-hit',
		sfxDeath: 'rhino-death',
		sfxIdle: 'rhino-idle',
		sfxSpecial: undefined,
	},
	kobold: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.HUMANOID,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'werewolf-attack',
		sfxHit: 'werewolf-hit',
		sfxDeath: 'werewolf-death',
		sfxIdle: 'werewolf-idle',
		sfxSpecial: undefined,
	},
	orc: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.HUMANOID,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'orc-attack',
		sfxHit: 'orc-hit',
		sfxDeath: 'orc-death',
		sfxIdle: 'orc-idle',
		sfxSpecial: undefined,
	},
	griffon: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.MYSTICAL,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'griffon-attack',
		sfxHit: 'griffon-hit',
		sfxDeath: 'griffon-death',
		sfxIdle: 'griffon-idle',
		sfxSpecial: 'griffon-special',
	},
	'harpy': {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.MYSTICAL,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'harpy-attack',
		sfxHit: 'harpy-hit',
		sfxDeath: 'harpy-death',
		sfxIdle: undefined,
		sfxSpecial: 'harpy-special',
	},
	werewolf: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.MYSTICAL,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'werewolf-attack',
		sfxHit: 'werewolf-hit',
		sfxDeath: 'werewolf-death',
		sfxIdle: 'werewolf-idle',
		sfxSpecial: undefined,
	},
	centaur: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.MYSTICAL,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'centaur-attack',
		sfxHit: 'centaur-hit',
		sfxDeath: 'centaur-death',
		sfxIdle: undefined,
		sfxSpecial: undefined,
	},
	cerberus: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.MYSTICAL,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'cerberus-attack',
		sfxHit: 'cerberus-hit',
		sfxDeath: 'cerberus-death',
		sfxIdle: 'cerberus-idle',
		sfxSpecial: undefined,
	},
	fungoid: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.HUMANOID,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'fungoid-attack',
		sfxHit: 'fungoid-hit',
		sfxDeath: 'fungoid-death',
		sfxIdle: 'fungoid-idle',
		sfxSpecial: 'fungoid-special',
	},
	gargoyle: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.MYSTICAL,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'gargoyle-attack',
		sfxHit: 'gargoyle-hit',
		sfxDeath: 'gargoyle-death',
		sfxIdle: 'gargoyle-idle',
		sfxSpecial: undefined,
	},
	beetle: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.BEAST,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'beetle-attack',
		sfxHit: 'beetle-hit',
		sfxDeath: 'beetle-death',
		sfxIdle: undefined,
		sfxSpecial: undefined,
	},
	imp: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.DEMON,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'imp-attack',
		sfxHit: 'imp-hit',
		sfxDeath: 'imp-death',
		sfxIdle: 'imp-idle',
		sfxSpecial: 'imp-attack',
	},
	minotaur: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.MYSTICAL,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'minotaur-attack',
		sfxHit: 'minotaur-hit',
		sfxDeath: 'minotaur-death',
		sfxIdle: 'minotaur-idle',
		sfxSpecial: undefined,
	},
	aviak: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.HUMANOID,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'aviak-attack',
		sfxHit: 'aviak-hit',
		sfxDeath: 'aviak-hit',
		sfxIdle: undefined,
		sfxSpecial: 'aviak-special',
	},
	elephant: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.BEAST,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'elephant-attack',
		sfxHit: 'elephant-hit',
		sfxDeath: 'elephant-death',
		sfxIdle: 'elephant-idle',
		sfxSpecial: undefined,
	},
	lion: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.BEAST,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'lion-attack',
		sfxHit: 'lion-hit',
		sfxDeath: 'lion-death',
		sfxIdle: 'lion-idle',
		sfxSpecial: undefined,
	},
	crocodile: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.BEAST,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'crocodile-attack',
		sfxHit: 'crocodile-hit',
		sfxDeath: 'crocodile-death',
		sfxIdle: undefined,
		sfxSpecial: undefined,
	},
	rhino: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.BEAST,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'rhino-attack',
		sfxHit: 'rhino-hit',
		sfxDeath: 'rhino-death',
		sfxIdle: undefined,
		sfxSpecial: undefined,
	},
	lioness: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.BEAST,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'lion-attack',
		sfxHit: 'lion-hit',
		sfxDeath: 'lion-death',
		sfxIdle: 'lion-idle',
		sfxSpecial: undefined,
	},
	bear: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.BEAST,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'bear-attack',
		sfxHit: 'bear-hit',
		sfxDeath: 'bear-death',
		sfxIdle: 'bear-idle',
		sfxSpecial: undefined,
	},
	toadlok: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.HUMANOID,
		resist: {
			blood: 1,
			poison: .7,
			arcane: 1,
			lightning: 1,
			fire: .7,
			ice: 1,
		},
		sfxAttack: 'toadlok-attack',
		sfxHit: 'toadlok-hit',
		sfxDeath: 'toadlok-death',
		sfxIdle: 'toadlok-idle',
		sfxSpecial: 'toadlok-special',
	},
	giant: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.GIANT,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'giant-attack',
		sfxHit: 'giant-hit',
		sfxDeath: 'giant-death',
		sfxIdle: 'giant-idle',
		sfxSpecial: undefined,
	},
	'ice-giant': {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.GIANT,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'giant-attack',
		sfxHit: 'giant-hit',
		sfxDeath: 'giant-death',
		sfxIdle: 'giant-idle',
		sfxSpecial: undefined,
	},
	'fire-giant': {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.GIANT,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'giant-attack',
		sfxHit: 'giant-hit',
		sfxDeath: 'giant-death',
		sfxIdle: 'giant-idle',
		sfxSpecial: undefined,
	},
	spectre: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.UNDEAD,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'spectre-attack',
		sfxHit: 'spectre-hit',
		sfxDeath: 'spectre-death',
		sfxIdle: 'spectre-idle',
		sfxSpecial: undefined,
	},
	angler: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.HUMANOID,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'angler-attack',
		sfxHit: 'angler-hit',
		sfxDeath: 'angler-death',
		sfxIdle: 'angler-attack',
		sfxSpecial: undefined,
	},
	'evil-eye': {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.MYSTICAL,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'evil-eye-attack',
		sfxHit: 'evil-eye-hit',
		sfxDeath: 'evil-eye-death',
		sfxIdle: 'evil-eye-idle',
		sfxSpecial: undefined,
	},
	unicorn: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.MYSTICAL,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'unicorn-attack',
		sfxHit: 'unicorn-hit',
		sfxDeath: 'unicorn-death',
		sfxIdle: 'unicorn-idle',
		sfxSpecial: undefined,
	},
	scorpion: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPE.BEAST,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'beetle-attack',
		sfxHit: 'beetle-hit',
		sfxDeath: 'beetle-death',
		sfxIdle: undefined,
		sfxSpecial: undefined,
	},
	/*'cyclops': {
	},*/
}