// toadlok ranks:
/*
urg 5-9
gluk 10-13
bog 14-17
rib 18-21
viz 22-25
gish 28-31
phin 32-35
gur 36-39
kel 40-43
thul 44-47
zog 48-51
 */
mob.data = {}
mob.data[ZONES.salubrinHaven] =
[
	{
		img: MOB_IMAGES.orc,
		name: 'orc pawn',
		minLevel: 1,
		maxLevel: 2,
		size: .65,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.orc,
		name: 'orc trainee',
		minLevel: 2,
		maxLevel: 3,
		size: .7,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.orc,
		name: 'orc initiate',
		minLevel: 3,
		maxLevel: 4,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.orc,
		name: 'orc trainer',
		minLevel: 5,
		maxLevel: 6,
		size: .75,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.orc,
		name: 'orc shaman',
		minLevel: 3,
		maxLevel: 5,
		size: .75,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.orc,
		name: 'orc centurion',
		minLevel: 3,
		maxLevel: 5,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.orc,
		name: 'orc legionnaire',
		minLevel: 6,
		maxLevel: 7,
		size: .9,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.orc,
		name: 'orc shaman elder',
		minLevel: 6,
		maxLevel: 8,
		size: .8,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.orc,
		name: 'orc shaman elder',
		minLevel: 6,
		maxLevel: 8,
		size: .8,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.snake,
		name: 'snake',
		minLevel: 1,
		maxLevel: 2,
		size: .7,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.snake,
		name: 'large snake',
		minLevel: 3,
		maxLevel: 4,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.snake,
		name: 'giant snake',
		minLevel: 5,
		maxLevel: 7,
		size: .9,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.spider,
		name: 'cave spiderling',
		minLevel: 1,
		maxLevel: 2,
		size: .3,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.spider,
		name: 'cave spider',
		minLevel: 3,
		maxLevel: 5,
		size: .75,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.spider,
		name: 'giant cave spider',
		minLevel: 6,
		maxLevel: 8,
		size: .85,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.wolf,
		name: 'wolf pup',
		minLevel: 1,
		maxLevel: 2,
		size: .65,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.wolf,
		name: 'young wolf',
		minLevel: 3,
		maxLevel: 4,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.wolf,
		name: 'cave wolf',
		minLevel: 5,
		maxLevel: 7,
		size: .9,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.scorpion,
		name: 'small scorpion',
		minLevel: 1,
		maxLevel: 2,
		size: .4,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.scorpion,
		name: 'scorpion',
		minLevel: 3,
		maxLevel: 5,
		size: .6,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.scorpion,
		name: 'large scorpion',
		minLevel: 6,
		maxLevel: 8,
		size: .8,
		job: JOB.WARRIOR,
	},
	// uniques
	{
		img: MOB_IMAGES.orc,
		name: 'Peon Snuffy',
		minLevel: 3,
		maxLevel: 3,
		size: .5,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { dauntless: true },
	},
	{
		img: MOB_IMAGES.snake,
		name: 'Slitherfang',
		minLevel: 4,
		maxLevel: 4,
		size: .8,
		job: JOB.ROGUE,
		tier: MOB_TIERS.unique,
		traits: { poisonEnchanted: true },
	},
	{
		img: MOB_IMAGES.spider,
		name: 'Twitchmaw',
		minLevel: 5,
		maxLevel: 5,
		size: .9,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { frenzied: true },
	},
	{
		img: MOB_IMAGES.wolf,
		name: 'Craven the Soulless',
		minLevel: 6,
		maxLevel: 6,
		size: .8,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { soulDrain: true },
	},
	{
		img: MOB_IMAGES.scorpion,
		name: 'Scithrax',
		minLevel: 5,
		maxLevel: 5,
		size: .8,
		job: JOB.ROGUE,
		tier: MOB_TIERS.unique,
		traits: { deadEye: true },
	},
	{
		img: MOB_IMAGES.orc,
		name: 'Grathule Frostreaver',
		minLevel: 7,
		maxLevel: 7,
		size: .8,
		job: JOB.SHAMAN,
		tier: MOB_TIERS.unique,
		traits: { iceEnchanted: true },
	},
	// quest mobs
	{
		img: MOB_IMAGES.orc,
		name: 'Peon Hegug',
		minLevel: 2,
		maxLevel: 2,
		size: .5,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { dauntless: true },
	},
	{
		img: MOB_IMAGES.orc,
		name: 'Centurion Shiloh',
		minLevel: 4,
		maxLevel: 4,
		size: .75,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { bloodlusted: true },
	},
	{
		img: MOB_IMAGES.orc,
		name: 'Prophet Urzoth',
		minLevel: 6,
		maxLevel: 6,
		size: .66,
		job: JOB.SHAMAN,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { magister: true },
	},
	{
		img: MOB_IMAGES.orc,
		name: 'Sergeant Grug',
		minLevel: 8,
		maxLevel: 8,
		size: .8,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { brute: true },
	},
]
mob.data[ZONES.tendolinPassage] =
[
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok tad',
		minLevel: 1,
		maxLevel: 2,
		size: .6,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok',
		minLevel: 3,
		maxLevel: 4,
		size: .66,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok sentry',
		minLevel: 3,
		maxLevel: 4,
		size: .7,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok urg knight',
		minLevel: 5,
		maxLevel: 6,
		size: .72,
		job: JOB.CRUSADER,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok urg warrior',
		minLevel: 5,
		maxLevel: 6,
		size: .72,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok urg knight',
		minLevel: 7,
		maxLevel: 8,
		size: .8,
		job: JOB.CRUSADER,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok urg warrior',
		minLevel: 7,
		maxLevel: 8,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.rat,
		name: 'young rat',
		minLevel: 1,
		maxLevel: 2,
		size: .5,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.rat,
		name: 'rat',
		minLevel: 3,
		maxLevel: 4,
		size: .65,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.rat,
		name: 'large rat',
		minLevel: 5,
		maxLevel: 6,
		size: .75,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.rat,
		name: 'tunnel rat',
		minLevel: 7,
		maxLevel: 8,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.snake,
		name: 'garter snake',
		minLevel: 1,
		maxLevel: 2,
		size: .7,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.snake,
		name: 'moss snake',
		minLevel: 3,
		maxLevel: 4,
		size: .7,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.snake,
		name: 'large snake',
		minLevel: 5,
		maxLevel: 6,
		size: .7,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.snake,
		name: 'rattlesnake',
		minLevel: 7,
		maxLevel: 8,
		size: .7,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.beetle,
		name: 'beetle',
		minLevel: 1,
		maxLevel: 2,
		size: .4,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.beetle,
		name: 'borer beetle',
		minLevel: 3,
		maxLevel: 4,
		size: .5,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.beetle,
		name: 'dung beetle',
		minLevel: 5,
		maxLevel: 6,
		size: .6,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.beetle,
		name: 'scarab beetle',
		minLevel: 7,
		maxLevel: 8,
		size: .7,
		job: JOB.WARRIOR,
	},
	// uniques
	{
		img: MOB_IMAGES.toadlok,
		name: 'Boggin Deepwater',
		minLevel: 4,
		maxLevel: 4,
		size: .6,
		job: JOB.SHAMAN,
		tier: MOB_TIERS.unique,
		traits: { poisonEnchanted: true },
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'Radamuh',
		minLevel: 6,
		maxLevel: 6,
		size: .7,
		job: JOB.WIZARD,
		tier: MOB_TIERS.unique,
		traits: { lightningEnchanted: true },
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'Voorg Gorefist',
		minLevel: 8,
		maxLevel: 8,
		size: .6,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		traits: { soulDrain: true },
	},
	{
		img: MOB_IMAGES.rat,
		name: 'Scruffy',
		minLevel: 6,
		maxLevel: 6,
		size: .8,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { dauntless: true },
	},
	{
		img: MOB_IMAGES.snake,
		name: 'Razorfang',
		minLevel: 5,
		maxLevel: 5,
		size: .8,
		job: JOB.ROGUE,
		tier: MOB_TIERS.unique,
		traits: { poisonEnchanted: true },
	},
	{
		img: MOB_IMAGES.beetle,
		name: 'Magmavore',
		minLevel: 7,
		maxLevel: 7,
		size: .8,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { fireEnchanted: true },
	},
	// quest mobs
	{
		img: MOB_IMAGES.toadlok,
		name: 'Fain the Mauler',
		minLevel: 2,
		maxLevel: 2,
		size: .8,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { brute: true },
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'Frizzle the Insane',
		minLevel: 4,
		maxLevel: 4,
		size: .42,
		job: JOB.RANGER,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { frenzied: true },
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'Murglon Arcfist',
		minLevel: 6,
		maxLevel: 6,
		size: .7,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { fireEnchanted: true },
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'Gelphon',
		minLevel: 8,
		maxLevel: 8,
		size: .75,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { deadEye: true },
	},
]
mob.data[ZONES.greenthornCavern] =
[
	{
		img: MOB_IMAGES.hobgoblin,
		name: 'hobgoblin runt',
		minLevel: 5,
		maxLevel: 6,
		size: .62,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.hobgoblin,
		name: 'scrawny hobgoblin',
		minLevel: 6,
		maxLevel: 8,
		size: .68,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.hobgoblin,
		name: 'hobgoblin scout',
		minLevel: 7,
		maxLevel: 9,
		size: .72,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.hobgoblin,
		name: 'hobgoblin shaman',
		minLevel: 8,
		maxLevel: 14,
		size: .72,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.hobgoblin,
		name: 'hobgoblin',
		minLevel: 7,
		maxLevel: 11,
		size: .7,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.hobgoblin,
		name: 'burly hobgoblin',
		minLevel: 9,
		maxLevel: 13,
		size: .75,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.hobgoblin,
		name: 'hobgoblin guardsman',
		minLevel: 10,
		maxLevel: 14,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.hobgoblin,
		name: 'hobgoblin commander',
		minLevel: 14,
		maxLevel: 16,
		size: .85,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.bear,
		name: 'bear cub',
		minLevel: 5,
		maxLevel: 6,
		size: .5,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.bear,
		name: 'brown bear',
		minLevel: 10,
		maxLevel: 11,
		size: .7,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.bear,
		name: 'grizzly bear',
		minLevel: 13,
		maxLevel: 14,
		size: .86,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.crocodile,
		name: 'caiman',
		minLevel: 7,
		maxLevel: 8,
		size: .65,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.crocodile,
		name: 'crocodile',
		minLevel: 9,
		maxLevel: 10,
		size: .75,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.crocodile,
		name: 'deepwater caiman',
		minLevel: 12,
		maxLevel: 13,
		size: .72,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.crocodile,
		name: 'deepwater crocodile',
		minLevel: 15,
		maxLevel: 16,
		size: .83,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.scorpion,
		name: 'whiptail scorpion',
		minLevel: 6,
		maxLevel: 8,
		size: .66,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.scorpion,
		name: 'tainted scorpion',
		minLevel: 10,
		maxLevel: 12,
		size: .77,
		job: JOB.ROGUE,
	},
	{
		img: MOB_IMAGES.scorpion,
		name: 'heartsting scorpion',
		minLevel: 14,
		maxLevel: 16,
		size: .83,
		job: JOB.ROGUE,
	},
	// uniques
	{
		img: MOB_IMAGES.hobgoblin,
		name: 'Chogarr Arpen',
		minLevel: 8,
		maxLevel: 8,
		size: .72,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { deadEye: true },
	},
	{
		img: MOB_IMAGES.hobgoblin,
		name: 'Hafex Tanaden',
		minLevel: 12,
		maxLevel: 12,
		size: .8,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { bloodlusted: true },
	},
	{
		img: MOB_IMAGES.hobgoblin,
		name: 'Rikolb Dygon',
		minLevel: 15,
		maxLevel: 15,
		size: .85,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { fireEnchanted: true },
	},
	{
		img: MOB_IMAGES.bear,
		name: 'Festerpaw',
		minLevel: 12,
		maxLevel: 12,
		size: .9,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { poisonEnchanted: true },
	},
	{
		img: MOB_IMAGES.scorpion,
		name: 'Krakator',
		minLevel: 16,
		maxLevel: 16,
		size: .9,
		job: JOB.WARLOCK,
		tier: MOB_TIERS.unique,
		traits: { magister: true },
	},
	// quest mobs
	{
		img: MOB_IMAGES.hobgoblin,
		name: 'Kyrgiarr Dreckhand',
		minLevel: 6,
		maxLevel: 6,
		size: .7,
		job: JOB.TEMPLAR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { dauntless: true },
	},
	{
		img: MOB_IMAGES.hobgoblin,
		name: 'Gyz Tamebeam',
		minLevel: 8,
		maxLevel: 8,
		size: .75,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { nimble: true },
	},
	{
		img: MOB_IMAGES.hobgoblin,
		name: 'Vyrg Dampclub',
		minLevel: 10,
		maxLevel: 10,
		size: .77,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { soulDrain: true },
	},
	{
		img: MOB_IMAGES.hobgoblin,
		name: 'Brirger Dustfist',
		minLevel: 12,
		maxLevel: 12,
		size: .79,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { tough: true },
	},
	{
		img: MOB_IMAGES.hobgoblin,
		name: 'Troto Rotgrinder',
		minLevel: 14,
		maxLevel: 14,
		size: .73,
		job: JOB.DRUID,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { lightningEnchanted: true },
	},
	{
		img: MOB_IMAGES.hobgoblin,
		name: 'Shiz Gorenail',
		minLevel: 16,
		maxLevel: 16,
		size: .84,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { spiritDrain: true },
	},
]
mob.data[ZONES.lanfeldRefuge] =
[
	{
		img: MOB_IMAGES.orc,
		name: 'orc',
		minLevel: 5,
		maxLevel: 8,
		size: .7,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.orc,
		name: 'orc',
		minLevel: 5,
		maxLevel: 8,
		size: .7,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.orc,
		name: 'orc centurion',
		minLevel: 7,
		maxLevel: 12,
		size: .76,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.orc,
		name: 'orc centurion',
		minLevel: 7,
		maxLevel: 12,
		size: .76,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.orc,
		name: 'orc legionnaire',
		minLevel: 11,
		maxLevel: 17,
		size: .75,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.orc,
		name: 'orc legionnaire',
		minLevel: 11,
		maxLevel: 17,
		size: .75,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.orc,
		name: 'orc warlord',
		minLevel: 15,
		maxLevel: 20,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.orc,
		name: 'orc warlord',
		minLevel: 15,
		maxLevel: 20,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.orc,
		name: 'royal guard',
		minLevel: 13,
		maxLevel: 19,
		size: .68,
		job: JOB.ROGUE,
	},
	{
		img: MOB_IMAGES.orc,
		name: 'orc mystic',
		minLevel: 13,
		maxLevel: 17,
		size: .7,
		job: JOB.TEMPLAR,
	},
	{
		img: MOB_IMAGES.orc,
		name: 'orc wizard',
		minLevel: 16,
		maxLevel: 20,
		size: .7,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.orc,
		name: 'orc oracle',
		minLevel: 8,
		maxLevel: 13,
		size: .65,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.orc,
		name: 'orc shaman',
		minLevel: 14,
		maxLevel: 16,
		size: .7,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.orc,
		name: 'orc high shaman',
		minLevel: 18,
		maxLevel: 20,
		size: .75,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.rat,
		name: 'field rat',
		minLevel: 5,
		maxLevel: 6,
		size: .73,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.rat,
		name: 'cave rat',
		minLevel: 7,
		maxLevel: 8,
		size: .83,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.rat,
		name: 'giant rat',
		minLevel: 9,
		maxLevel: 10,
		size: .93,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.spider,
		name: 'grass spiderling',
		minLevel: 6,
		maxLevel: 8,
		size: .65,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.spider,
		name: 'prowling spider',
		minLevel: 9,
		maxLevel: 11,
		size: .9,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.spider,
		name: 'giant wolf spider',
		minLevel: 12,
		maxLevel: 14,
		size: 1,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.wolf,
		name: 'black wolf',
		minLevel: 7,
		maxLevel: 9,
		size: .75,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.wolf,
		name: 'young dire wolf',
		minLevel: 12,
		maxLevel: 14,
		size: .79,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.wolf,
		name: 'dire wolf',
		minLevel: 16,
		maxLevel: 18,
		size: .84,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.scorpion,
		name: 'heart scorpion',
		minLevel: 10,
		maxLevel: 12,
		size: .84,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.scorpion,
		name: 'lurking scorpion',
		minLevel: 13,
		maxLevel: 15,
		size: .84,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.scorpion,
		name: 'stone scorpion',
		minLevel: 17,
		maxLevel: 19,
		size: .84,
		job: JOB.WARRIOR,
	},
	// uniques
	{
		img: MOB_IMAGES.wolf,
		name: 'Ulfr',
		minLevel: 7,
		maxLevel: 7,
		size: .8,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { iceEnchanted: true },
	},
	{
		img: MOB_IMAGES.rat,
		name: 'Chuckie',
		minLevel: 12,
		maxLevel: 12,
		size: .95,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { frenzied: true },
	},
	{
		img: MOB_IMAGES.scorpion,
		name: 'Shrapnel',
		minLevel: 16,
		maxLevel: 16,
		size: .92,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		traits: { fireEnchanted: true },
	},
	{
		img: MOB_IMAGES.orc,
		name: 'Trainer Zalthu',
		minLevel: 9,
		maxLevel: 9,
		size: .74,
		job: JOB.CRUSADER,
		tier: MOB_TIERS.unique,
		traits: { dauntless: true },
	},
	{
		img: MOB_IMAGES.orc,
		name: 'Revenant Xegug',
		minLevel: 11,
		maxLevel: 11,
		size: .76,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		traits: { bloodlusted: true },
	},
	{
		img: MOB_IMAGES.orc,
		name: 'Acolyte Filge',
		minLevel: 14,
		maxLevel: 14,
		size: .7,
		job: JOB.WIZARD,
		tier: MOB_TIERS.unique,
		traits: { magister: true },
	},
	{
		img: MOB_IMAGES.orc,
		name: 'Gladiator Lagakh',
		minLevel: 17,
		maxLevel: 17,
		size: .92,
		job: JOB.CRUSADER,
		tier: MOB_TIERS.unique,
		traits: { brute: true },
	},
	{
		img: MOB_IMAGES.orc,
		name: 'Prophet Grazob',
		minLevel: 19,
		maxLevel: 19,
		size: .76,
		job: JOB.SHAMAN,
		tier: MOB_TIERS.unique,
		traits: { spiritDrain: true },
	},
	// quest mobs
	{
		img: MOB_IMAGES.orc,
		name: 'Disciple Bashag',
		minLevel: 6,
		maxLevel: 6,
		size: .7,
		job: JOB.MONK,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { nimble: true },
	},
	{
		img: MOB_IMAGES.orc,
		name: 'Sergeant Dumburz',
		minLevel: 8,
		maxLevel: 8,
		size: .75,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { tough: true },
	},
	{
		img: MOB_IMAGES.orc,
		name: 'Warlord Turbag',
		minLevel: 10,
		maxLevel: 10,
		size: .75,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { lightningEnchanted: true },
	},
	{
		img: MOB_IMAGES.orc,
		name: 'Soothsayer Bilge',
		minLevel: 12,
		maxLevel: 12,
		size: .75,
		job: JOB.SHAMAN,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { poisonEnchanted: true },
	},
	{
		img: MOB_IMAGES.orc,
		name: 'Oracle Xomath',
		minLevel: 14,
		maxLevel: 14,
		size: .75,
		job: JOB.CLERIC,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { magister: true },
	},
	{
		img: MOB_IMAGES.orc,
		name: 'Captain Urzoth',
		minLevel: 16,
		maxLevel: 16,
		size: .75,
		job: JOB.CRUSADER,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { dauntless: true },
	},
	{
		img: MOB_IMAGES.orc,
		name: 'Minstrel Baronk',
		minLevel: 18,
		maxLevel: 18,
		size: .75,
		job: JOB.BARD,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { deadEye: true },
	},
	{
		img: MOB_IMAGES.orc,
		name: 'Emperor Thresh',
		minLevel: 20,
		maxLevel: 20,
		size: .75,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { tough: true },
	},
]
mob.data[ZONES.rivenGrotto] = [
	{
		img: MOB_IMAGES.beetle,
		name: 'borer beetle',
		minLevel: 8,
		maxLevel: 11,
		size: .5,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.beetle,
		name: 'pincer beetle',
		minLevel: 12,
		maxLevel: 14,
		size: .75,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.beetle,
		name: 'death beetle',
		minLevel: 16,
		maxLevel: 18,
		size: .9,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.ghoul,
		name: 'ghoul',
		minLevel: 9,
		maxLevel: 12,
		size: .7,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.ghoul,
		name: 'fetid ghoul',
		minLevel: 13,
		maxLevel: 15,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.ghoul,
		name: 'carrion ghoul',
		minLevel: 16,
		maxLevel: 18,
		size: .85,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.ghoul,
		name: 'crazed ghoul',
		minLevel: 20,
		maxLevel: 22,
		size: .95,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'tiny skeleton',
		minLevel: 9,
		maxLevel: 12,
		size: .5,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'greater skeleton',
		minLevel: 13,
		maxLevel: 15,
		size: .75,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'skeletal monk',
		minLevel: 15,
		maxLevel: 18,
		size: .8,
		job: JOB.MONK,
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'skeletal mage',
		minLevel: 14,
		maxLevel: 19,
		size: .7,
		job: JOB.TEMPLAR,
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'dry bone skeleton',
		minLevel: 20,
		maxLevel: 23,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'skeletal sorcerer',
		minLevel: 19,
		maxLevel: 24,
		size: .66,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.mummy,
		name: 'mummy',
		minLevel: 13,
		maxLevel: 15,
		size: .75,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.mummy,
		name: 'crypt mummy',
		minLevel: 17,
		maxLevel: 19,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.mummy,
		name: 'ancient mummy',
		minLevel: 17,
		maxLevel: 19,
		size: .85,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.mummy,
		name: 'arcane mummy',
		minLevel: 14,
		maxLevel: 18,
		size: .72,
		job: JOB.WARLOCK,
	},
	{
		img: MOB_IMAGES.mummy,
		name: 'chaos mummy',
		minLevel: 19,
		maxLevel: 23,
		size: .72,
		job: JOB.WARLOCK,
	},
	{
		img: MOB_IMAGES.zombie,
		name: 'tormented zombie',
		minLevel: 10,
		maxLevel: 13,
		size: .75,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.zombie,
		name: 'listless zombie',
		minLevel: 15,
		maxLevel: 18,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.zombie,
		name: 'rotting savant',
		minLevel: 12,
		maxLevel: 16,
		size: .73,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.zombie,
		name: 'festering bloke',
		minLevel: 19,
		maxLevel: 24,
		size: .76,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.zombie,
		name: 'haunted zombie',
		minLevel: 20,
		maxLevel: 22,
		size: .85,
		job: JOB.WARRIOR,
	},
	// uniques
	{
		img: MOB_IMAGES.beetle,
		name: 'Megadeath',
		minLevel: 13,
		maxLevel: 13,
		size: 1.1,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		traits: { bloodlusted: true },
	},
	{
		img: MOB_IMAGES.beetle,
		name: 'Plagueworm the Burrower',
		minLevel: 21,
		maxLevel: 21,
		size: 1.25,
		job: JOB.WARLOCK,
		tier: MOB_TIERS.unique,
		traits: { poisonEnchanted: true },
	},
	{
		img: MOB_IMAGES.ghoul,
		name: 'Gashsorrow',
		minLevel: 11,
		maxLevel: 11,
		size: .8,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { frenzied: true },
	},
	{
		img: MOB_IMAGES.ghoul,
		name: 'Bruisesnarl',
		minLevel: 17,
		maxLevel: 17,
		size: .9,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		traits: { brute: true },
	},
	{
		img: MOB_IMAGES.mummy,
		name: 'Jiktraq the Apostle',
		minLevel: 19,
		maxLevel: 19,
		size: .86,
		job: JOB.ENCHANTER,
		tier: MOB_TIERS.unique,
		traits: { magister: true },
	},
	{
		img: MOB_IMAGES.mummy,
		name: 'Prince Corpsesworn',
		minLevel: 22,
		maxLevel: 22,
		size: .92,
		job: JOB.ENCHANTER,
		tier: MOB_TIERS.unique,
		traits: { nimble: true },
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'Undead Knight of Riven',
		minLevel: 21,
		maxLevel: 21,
		size: .93,
		job: JOB.CRUSADER,
		tier: MOB_TIERS.unique,
		traits: { deadEye: true },
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'Butler of Riven',
		minLevel: 14,
		maxLevel: 14,
		size: .85,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { lightningEnchanted: true },
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'Glyphed Sentinel of Riven',
		minLevel: 10,
		maxLevel: 10,
		size: .8,
		job: JOB.TEMPLAR,
		tier: MOB_TIERS.unique,
		traits: { soulDrain: true },
	},
	{
		img: MOB_IMAGES.zombie,
		name: 'Aurath',
		minLevel: 13,
		maxLevel: 13,
		size: .8,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { spiritDrain: true },
	},
	{
		img: MOB_IMAGES.zombie,
		name: 'Karm the Frostreaver',
		minLevel: 18,
		maxLevel: 18,
		size: .9,
		job: JOB.WIZARD,
		tier: MOB_TIERS.unique,
		traits: { iceEnchanted: true },
	},
	// quest mobs
	{
		img: MOB_IMAGES.ghoul,
		name: 'Shockflayer the Tainted',
		minLevel: 9,
		maxLevel: 9,
		size: .8,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { frenzy: true },
	},
	{
		img: MOB_IMAGES.mummy,
		name: 'Grimnail the Enflamed',
		minLevel: 11,
		maxLevel: 11,
		size: .75,
		job: JOB.TEMPLAR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { fireEnchanted: true },
	},
	{
		img: MOB_IMAGES.mummy,
		name: 'Reclusive Magi of Riven',
		minLevel: 13,
		maxLevel: 13,
		size: .77,
		job: JOB.ENCHANTER,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { lightningEnchanted: true },
	},
	{
		img: MOB_IMAGES.zombie,
		name: 'Duke of Riven',
		minLevel: 15,
		maxLevel: 15,
		size: .86,
		job: JOB.CRUSADER,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { dauntless: true },
	},
	{
		img: MOB_IMAGES.ghoul,
		name: 'Oracle of Riven',
		minLevel: 17,
		maxLevel: 17,
		size: .72,
		job: JOB.CLERIC,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { frenzy: true },
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'Riven Executioner',
		minLevel: 19,
		maxLevel: 19,
		size: 1,
		job: JOB.ROGUE,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { brute: true },
	},
	{
		img: MOB_IMAGES.ghoul,
		name: 'Plagueweaver the Untamed',
		minLevel: 21,
		maxLevel: 21,
		size: .9,
		job: JOB.WARLOCK,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { poisonEnchanted: true },
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'King of Riven Grotto',
		minLevel: 24,
		maxLevel: 24,
		size: 1.2,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { tough: true },
	},
]
mob.data[ZONES.bastilleCitadel] = [
	{
		img: MOB_IMAGES.goblin,
		name: 'goblin runt',
		minLevel: 10,
		maxLevel: 12,
		size: .65,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'goblin peon',
		minLevel: 11,
		maxLevel: 13,
		size: .69,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'goblin',
		minLevel: 13,
		maxLevel: 16,
		size: .74,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'goblin enforcer',
		minLevel: 16,
		maxLevel: 19,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'goblin despot',
		minLevel: 19,
		maxLevel: 22,
		size: .83,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'goblin tyrant',
		minLevel: 22,
		maxLevel: 24,
		size: .86,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'goblin prelate',
		minLevel: 10,
		maxLevel: 13,
		size: .75,
		job: JOB.CLERIC,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'goblin priest',
		minLevel: 14,
		maxLevel: 17,
		size: .78,
		job: JOB.CLERIC,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'goblin preacher',
		minLevel: 18,
		maxLevel: 21,
		size: .82,
		job: JOB.CLERIC,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'goblin evangelist',
		minLevel: 22,
		maxLevel: 24,
		size: .85,
		job: JOB.CLERIC,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'goblin mendicant',
		minLevel: 11,
		maxLevel: 14,
		size: .73,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'goblin mystic',
		minLevel: 16,
		maxLevel: 18,
		size: .77,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'goblin witch doctor',
		minLevel: 20,
		maxLevel: 22,
		size: .8,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'goblin diviner',
		minLevel: 10,
		maxLevel: 13,
		size: .7,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'goblin evoker',
		minLevel: 14,
		maxLevel: 17,
		size: .73,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'goblin magus',
		minLevel: 18,
		maxLevel: 21,
		size: .77,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'goblin sorcerer',
		minLevel: 22,
		maxLevel: 24,
		size: .8,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'skeleton cantor',
		minLevel: 10,
		maxLevel: 12,
		size: .7,
		job: JOB.BARD,
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'skeleton composer',
		minLevel: 14,
		maxLevel: 16,
		size: .73,
		job: JOB.BARD,
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'skeleton lyricist',
		minLevel: 18,
		maxLevel: 20,
		size: .76,
		job: JOB.BARD,
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'skeleton soloist',
		minLevel: 22,
		maxLevel: 24,
		size: .79,
		job: JOB.BARD,
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'skeleton pathfinder',
		minLevel: 12,
		maxLevel: 14,
		size: .8,
		job: JOB.RANGER,
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'skeleton outrider',
		minLevel: 16,
		maxLevel: 19,
		size: .85,
		job: JOB.RANGER,
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'skeleton warder',
		minLevel: 21,
		maxLevel: 23,
		size: .9,
		job: JOB.RANGER,
	},
	{
		img: MOB_IMAGES.hobgoblin,
		name: 'hobgoblin',
		minLevel: 11,
		maxLevel: 14,
		size: .77,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.hobgoblin,
		name: 'hobgoblin mauler',
		minLevel: 15,
		maxLevel: 18,
		size: .83,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.hobgoblin,
		name: 'hobgoblin bruiser',
		minLevel: 19,
		maxLevel: 22,
		size: .9,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.hobgoblin,
		name: 'hobgoblin knight',
		minLevel: 12,
		maxLevel: 15,
		size: .82,
		job: JOB.SHADOW_KNIGHT,
	},
	{
		img: MOB_IMAGES.hobgoblin,
		name: 'hobgoblin guardian',
		minLevel: 16,
		maxLevel: 19,
		size: .87,
		job: JOB.SHADOW_KNIGHT,
	},
	{
		img: MOB_IMAGES.hobgoblin,
		name: 'hobgoblin revenant',
		minLevel: 21,
		maxLevel: 23,
		size: .93,
		job: JOB.SHADOW_KNIGHT,
	},
	{
		img: MOB_IMAGES.evilEye,
		name: 'evil eye',
		minLevel: 12,
		maxLevel: 14,
		size: .75,
		job: JOB.ENCHANTER,
	},
	{
		img: MOB_IMAGES.evilEye,
		name: 'eye beguiler',
		minLevel: 16,
		maxLevel: 18,
		size: .83,
		job: JOB.ENCHANTER,
	},
	{
		img: MOB_IMAGES.evilEye,
		name: 'eye tyrant',
		minLevel: 20,
		maxLevel: 22,
		size: .87,
		job: JOB.ENCHANTER,
	},
	{
		img: MOB_IMAGES.evilEye,
		name: 'esoteric eye',
		minLevel: 14,
		maxLevel: 16,
		size: .83,
		job: JOB.TEMPLAR,
	},
	{
		img: MOB_IMAGES.evilEye,
		name: 'cabalistic eye',
		minLevel: 19,
		maxLevel: 21,
		size: .88,
		job: JOB.TEMPLAR,
	},
	{
		img: MOB_IMAGES.evilEye,
		name: 'occult eye',
		minLevel: 23,
		maxLevel: 24,
		size: .94,
		job: JOB.TEMPLAR,
	},
	{
		img: MOB_IMAGES.ironGolem,
		name: 'golem scout',
		minLevel: 13,
		maxLevel: 15,
		size: .75,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.ironGolem,
		name: 'golem sentinel',
		minLevel: 15,
		maxLevel: 18,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.ironGolem,
		name: 'golem keeper',
		minLevel: 17,
		maxLevel: 20,
		size: .85,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.ironGolem,
		name: 'golem protector',
		minLevel: 20,
		maxLevel: 22,
		size: .9,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.ironGolem,
		name: 'golem guardian',
		minLevel: 22,
		maxLevel: 24,
		size: .95,
		job: JOB.WARRIOR,
	},
	// uniques
	{
		img: MOB_IMAGES.goblin,
		name: 'Prefect Glozz',
		minLevel: 11,
		maxLevel: 11,
		size: .75,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { brute: true },
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'Overseer Higs',
		minLevel: 13,
		maxLevel: 13,
		size: .79,
		job: JOB.WARLOCK,
		tier: MOB_TIERS.unique,
		traits: { poisonEnchanted: true },
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'Inspector Zelb',
		minLevel: 16,
		maxLevel: 16,
		size: .83,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { tough: true },
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'Instructor Fasia',
		minLevel: 19,
		maxLevel: 19,
		size: .7,
		job: JOB.DRUID,
		tier: MOB_TIERS.unique,
		traits: { magister: true },
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'Warden Ubar',
		minLevel: 21,
		maxLevel: 21,
		size: .81,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		traits: { bloodlusted: true },
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'Adherent Stux',
		minLevel: 23,
		maxLevel: 23,
		size: .83,
		job: JOB.CRUSADER,
		tier: MOB_TIERS.unique,
		traits: { dauntless: true },
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'Grand Maestro',
		minLevel: 21,
		maxLevel: 21,
		size: .95,
		job: JOB.BARD,
		tier: MOB_TIERS.unique,
		traits: { frenzy: true },
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'Prophet of Rancor',
		minLevel: 15,
		maxLevel: 15,
		size: .86,
		job: JOB.BARD,
		tier: MOB_TIERS.unique,
		traits: { soulDrain: true },
	},
	{
		img: MOB_IMAGES.hobgoblin,
		name: 'Enforcer Rotbrass',
		minLevel: 14,
		maxLevel: 14,
		size: .85,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { deadEye: true },
	},
	{
		img: MOB_IMAGES.hobgoblin,
		name: 'Executioner Brot Sludgemug',
		minLevel: 20,
		maxLevel: 20,
		size: .93,
		job: JOB.ROGUE,
		tier: MOB_TIERS.unique,
		traits: { deadEye: true },
	},
	{
		img: MOB_IMAGES.evilEye,
		name: 'Sentinel Xolcanea',
		minLevel: 17,
		maxLevel: 17,
		size: .85,
		job: JOB.ENCHANTER,
		tier: MOB_TIERS.unique,
		traits: { magister: true },
	},
	{
		img: MOB_IMAGES.evilEye,
		name: 'Overseer Chryzyaxa',
		minLevel: 23,
		maxLevel: 23,
		size: .92,
		job: JOB.ENCHANTER,
		tier: MOB_TIERS.unique,
		traits: { lightningEnchanted: true },
	},
	{
		img: MOB_IMAGES.ironGolem,
		name: 'Keeper of Babel',
		minLevel: 14,
		maxLevel: 14,
		size: .83,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { nimble: true },
	},
	{
		img: MOB_IMAGES.ironGolem,
		name: 'Champion of Babel',
		minLevel: 21,
		maxLevel: 21,
		size: .9,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { tough: true },
	},
	// quest mobs
	{
		img: MOB_IMAGES.goblin,
		name: 'Custodian Gimzits',
		minLevel: 12,
		maxLevel: 12,
		size: .8,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { nimble: true },
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'Officer Gnaarx',
		minLevel: 14,
		maxLevel: 14,
		size: .82,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { dauntless: true },
	},
	{
		img: MOB_IMAGES.hobgoblin,
		name: 'Harvester Rotpincer',
		minLevel: 16,
		maxLevel: 16,
		size: .85,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { soulDrain: true },
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'Lieutenant Tizil',
		minLevel: 18,
		maxLevel: 18,
		size: .87,
		job: JOB.CLERIC,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { magister: true },
	},
	{
		img: MOB_IMAGES.ironGolem,
		name: 'Arbiter Slate',
		minLevel: 20,
		maxLevel: 20,
		size: .95,
		job: JOB.SHAMAN,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { deadEye: true },
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'Commander Koning',
		minLevel: 22,
		maxLevel: 22,
		size: .93,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { tough: true },
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'Chief Warden Bruizard',
		minLevel: 24,
		maxLevel: 24,
		size: 1,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { bloodlusted: true },
	},
]
mob.data[ZONES.kordataCove] = [
	{
		img: MOB_IMAGES.angler,
		name: 'angler',
		minLevel: 12,
		maxLevel: 14,
		size: .65,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.angler,
		name: 'angler hoplite',
		minLevel: 13,
		maxLevel: 15,
		size: .72,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.angler,
		name: 'angler thrasher',
		minLevel: 15,
		maxLevel: 18,
		size: .76,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.angler,
		name: 'angler hellion',
		minLevel: 18,
		maxLevel: 21,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.angler,
		name: 'angler brawler',
		minLevel: 21,
		maxLevel: 23,
		size: .83,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.angler,
		name: 'angler patriarch',
		minLevel: 23,
		maxLevel: 25,
		size: .86,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.angler,
		name: 'angler tracker',
		minLevel: 11,
		maxLevel: 15,
		size: .73,
		job: JOB.RANGER,
	},
	{
		img: MOB_IMAGES.angler,
		name: 'angler prowler',
		minLevel: 17,
		maxLevel: 20,
		size: .8,
		job: JOB.RANGER,
	},
	{
		img: MOB_IMAGES.angler,
		name: 'angler nightstalker',
		minLevel: 22,
		maxLevel: 25,
		size: .85,
		job: JOB.RANGER,
	},
	{
		img: MOB_IMAGES.angler,
		name: 'angler wanderer',
		minLevel: 10,
		maxLevel: 13,
		size: .7,
		job: JOB.DRUID,
	},
	{
		img: MOB_IMAGES.angler,
		name: 'angler protector',
		minLevel: 14,
		maxLevel: 17,
		size: .75,
		job: JOB.DRUID,
	},
	{
		img: MOB_IMAGES.angler,
		name: 'angler preserver',
		minLevel: 18,
		maxLevel: 21,
		size: .8,
		job: JOB.DRUID,
	},
	{
		img: MOB_IMAGES.angler,
		name: 'angler whisperer',
		minLevel: 22,
		maxLevel: 25,
		size: .85,
		job: JOB.DRUID,
	},
	{
		img: MOB_IMAGES.angler,
		name: 'angler templar',
		minLevel: 12,
		maxLevel: 15,
		size: .7,
		job: JOB.TEMPLAR,
	},
	{
		img: MOB_IMAGES.angler,
		name: 'angler sage',
		minLevel: 17,
		maxLevel: 20,
		size: .77,
		job: JOB.TEMPLAR,
	},
	{
		img: MOB_IMAGES.angler,
		name: 'angler magician',
		minLevel: 22,
		maxLevel: 25,
		size: .84,
		job: JOB.TEMPLAR,
	},
	{
		img: MOB_IMAGES.fungoid,
		name: 'fungoid',
		minLevel: 11,
		maxLevel: 14,
		size: .75,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.fungoid,
		name: 'fungoid disciple',
		minLevel: 16,
		maxLevel: 19,
		size: .8,
		job: JOB.MONK,
	},
	{
		img: MOB_IMAGES.fungoid,
		name: 'fungoid master',
		minLevel: 21,
		maxLevel: 24,
		size: .85,
		job: JOB.MONK,
	},
	{
		img: MOB_IMAGES.fungoid,
		name: 'fungoid agent',
		minLevel: 11,
		maxLevel: 14,
		size: .75,
		job: JOB.ROGUE,
	},
	{
		img: MOB_IMAGES.fungoid,
		name: 'fungoid emissary',
		minLevel: 16,
		maxLevel: 19,
		size: .8,
		job: JOB.ROGUE,
	},
	{
		img: MOB_IMAGES.fungoid,
		name: 'fungoid envoy',
		minLevel: 21,
		maxLevel: 24,
		size: .85,
		job: JOB.ROGUE,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok gluk reaper',
		minLevel: 10,
		maxLevel: 13,
		size: .75,
		job: JOB.SHADOW_KNIGHT,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok bog reaper',
		minLevel: 14,
		maxLevel: 17,
		size: .8,
		job: JOB.SHADOW_KNIGHT,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok rib reaper',
		minLevel: 18,
		maxLevel: 21,
		size: .86,
		job: JOB.SHADOW_KNIGHT,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok viz reaper',
		minLevel: 22,
		maxLevel: 25,
		size: .9,
		job: JOB.SHADOW_KNIGHT,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok gluk warlock',
		minLevel: 10,
		maxLevel: 13,
		size: .7,
		job: JOB.WARLOCK,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok bog warlock',
		minLevel: 14,
		maxLevel: 17,
		size: .75,
		job: JOB.WARLOCK,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok rib warlock',
		minLevel: 18,
		maxLevel: 21,
		size: .8,
		job: JOB.WARLOCK,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok viz warlock',
		minLevel: 22,
		maxLevel: 25,
		size: .85,
		job: JOB.WARLOCK,
	},
	{
		img: MOB_IMAGES.stoneGolem,
		name: 'tiny stone golem',
		minLevel: 10,
		maxLevel: 13,
		size: .5,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.stoneGolem,
		name: 'stone golem sentry',
		minLevel: 15,
		maxLevel: 17,
		size: .69,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.stoneGolem,
		name: 'hulking stone golem',
		minLevel: 19,
		maxLevel: 21,
		size: .75,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.stoneGolem,
		name: 'giant stone golem',
		minLevel: 23,
		maxLevel: 25,
		size: .95,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.stoneGolem,
		name: 'stone golem shaman',
		minLevel: 12,
		maxLevel: 15,
		size: .7,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.stoneGolem,
		name: 'stone golem mendicant',
		minLevel: 17,
		maxLevel: 19,
		size: .75,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.stoneGolem,
		name: 'stone golem soothsayer',
		minLevel: 21,
		maxLevel: 23,
		size: .8,
		job: JOB.SHAMAN,
	},
	// uniques
	{
		img: MOB_IMAGES.angler,
		name: 'Assassin Chasa',
		minLevel: 12,
		maxLevel: 12,
		size: .75,
		job: JOB.ROGUE,
		tier: MOB_TIERS.unique,
		traits: { nimble: true },
	},
	{
		img: MOB_IMAGES.angler,
		name: 'Adept Ito',
		minLevel: 15,
		maxLevel: 15,
		size: .77,
		job: JOB.WIZARD,
		tier: MOB_TIERS.unique,
		traits: { frenzied: true },
	},
	{
		img: MOB_IMAGES.angler,
		name: 'Marksman Iksha',
		minLevel: 18,
		maxLevel: 18,
		size: .8,
		job: JOB.RANGER,
		tier: MOB_TIERS.unique,
		traits: { deadEye: true },
	},
	{
		img: MOB_IMAGES.angler,
		name: 'Tetrarch Nuhanju',
		minLevel: 21,
		maxLevel: 21,
		size: .84,
		job: JOB.DRUID,
		tier: MOB_TIERS.unique,
		traits: { lightningEnchanted: true },
	},
	{
		img: MOB_IMAGES.angler,
		name: 'Judge Osha',
		minLevel: 23,
		maxLevel: 23,
		size: .83,
		job: JOB.ENCHANTER,
		tier: MOB_TIERS.unique,
		traits: { spiritDrain: true },
	},
	{
		img: MOB_IMAGES.fungoid,
		name: 'Lancer Gilliphis',
		minLevel: 13,
		maxLevel: 13,
		size: .77,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { iceEnchanted: true },
	},
	{
		img: MOB_IMAGES.fungoid,
		name: 'High Priest Hesperis',
		minLevel: 17,
		maxLevel: 17,
		size: .8,
		job: JOB.SHAMAN,
		tier: MOB_TIERS.unique,
		traits: { poisonEnchanted: true },
	},
	{
		img: MOB_IMAGES.fungoid,
		name: 'Fanatic Calamis',
		minLevel: 22,
		maxLevel: 22,
		size: .86,
		job: JOB.MONK,
		tier: MOB_TIERS.unique,
		traits: { brute: true },
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'Fribble',
		minLevel: 11,
		maxLevel: 11,
		size: .73,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { nimble: true },
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'Prophet Croakin',
		minLevel: 15,
		maxLevel: 15,
		size: .78,
		job: JOB.CLERIC,
		tier: MOB_TIERS.unique,
		traits: { soulDrain: true },
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'Channeler Auglur',
		minLevel: 21,
		maxLevel: 21,
		size: .84,
		job: JOB.WIZARD,
		tier: MOB_TIERS.unique,
		traits: { dauntless: true },
	},
	{
		img: MOB_IMAGES.stoneGolem,
		name: 'Doom Elemental Grav',
		minLevel: 13,
		maxLevel: 13,
		size: .6,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		traits: { lightningEnchanted: true },
	},
	{
		img: MOB_IMAGES.stoneGolem,
		name: 'Earth Elemental Firmis',
		minLevel: 13,
		maxLevel: 13,
		size: .95,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { tough: true },
	},
	// quest mobs
	{
		img: MOB_IMAGES.angler,
		name: 'Spearmaster Dimas',
		minLevel: 13,
		maxLevel: 13,
		size: .8,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { deadEye: true },
	},
	{
		img: MOB_IMAGES.angler,
		name: 'Assassin Nagugesa',
		minLevel: 15,
		maxLevel: 15,
		size: .77,
		job: JOB.ROGUE,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { poisonEnchanted: true },
	},
	{
		img: MOB_IMAGES.angler,
		name: 'Umber',
		minLevel: 17,
		maxLevel: 17,
		size: .88,
		job: JOB.WARLOCK,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { soulDrain: true },
	},
	{
		img: MOB_IMAGES.angler,
		name: 'Troubadour Tesai',
		minLevel: 19,
		maxLevel: 19,
		size: .84,
		job: JOB.BARD,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { frenzied: true },
	},
	{
		img: MOB_IMAGES.angler,
		name: 'Thaumaturge Vanma',
		minLevel: 21,
		maxLevel: 21,
		size: .83,
		job: JOB.TEMPLAR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { lightningEnchanted: true },
	},
	{
		img: MOB_IMAGES.angler,
		name: 'Prime Occultist Kattra',
		minLevel: 23,
		maxLevel: 23,
		size: .88,
		job: JOB.WARLOCK,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { spiritDrain: true },
	},
	{
		img: MOB_IMAGES.angler,
		name: 'King Krama',
		minLevel: 25,
		maxLevel: 25,
		size: 1,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { deadEye: true },
	},
]
mob.data[ZONES.sylongSanctuary] = [
	{
		img: MOB_IMAGES.minotaur,
		name: 'minotaur',
		minLevel: 16,
		maxLevel: 19,
		size: .75,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.minotaur,
		name: 'minotaur raider',
		minLevel: 20,
		maxLevel: 23,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.minotaur,
		name: 'minotaur elder',
		minLevel: 24,
		maxLevel: 27,
		size: .85,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.minotaur,
		name: 'minotaur patriarch',
		minLevel: 28,
		maxLevel: 30,
		size: .9,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.minotaur,
		name: 'minotaur watchman',
		minLevel: 18,
		maxLevel: 21,
		size: .75,
		job: JOB.RANGER,
	},
	{
		img: MOB_IMAGES.minotaur,
		name: 'minotaur brigand',
		minLevel: 23,
		maxLevel: 25,
		size: .8,
		job: JOB.ROGUE,
	},
	{
		img: MOB_IMAGES.minotaur,
		name: 'minotaur friar',
		minLevel: 26,
		maxLevel: 28,
		size: .8,
		job: JOB.MONK,
	},
	{
		img: MOB_IMAGES.centaur,
		name: 'centaur foal',
		minLevel: 18,
		maxLevel: 20,
		size: .74,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.centaur,
		name: 'centaur sheltie',
		minLevel: 22,
		maxLevel: 25,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.centaur,
		name: 'centaur charger',
		minLevel: 27,
		maxLevel: 29,
		size: .88,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.centaur,
		name: 'centaur archer',
		minLevel: 18,
		maxLevel: 21,
		size: .74,
		job: JOB.RANGER,
	},
	{
		img: MOB_IMAGES.centaur,
		name: 'centaur hunter',
		minLevel: 23,
		maxLevel: 25,
		size: .79,
		job: JOB.RANGER,
	},
	{
		img: MOB_IMAGES.centaur,
		name: 'centaur courser',
		minLevel: 27,
		maxLevel: 29,
		size: .83,
		job: JOB.RANGER,
	},
	{
		img: MOB_IMAGES.aviak,
		name: 'aviak egret',
		minLevel: 17,
		maxLevel: 19,
		size: .76,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.aviak,
		name: 'aviak avocet',
		minLevel: 22,
		maxLevel: 24,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.aviak,
		name: 'aviak harrier',
		minLevel: 26,
		maxLevel: 28,
		size: .84,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.aviak,
		name: 'aviak caller',
		minLevel: 16,
		maxLevel: 18,
		size: .7,
		job: JOB.DRUID,
	},
	{
		img: MOB_IMAGES.aviak,
		name: 'aviak keeper',
		minLevel: 20,
		maxLevel: 23,
		size: .75,
		job: JOB.DRUID,
	},
	{
		img: MOB_IMAGES.aviak,
		name: 'aviak cyclone',
		minLevel: 25,
		maxLevel: 27,
		size: .8,
		job: JOB.DRUID,
	},
	{
		img: MOB_IMAGES.griffon,
		name: 'griffawn',
		minLevel: 17,
		maxLevel: 19,
		size: .7,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.griffon,
		name: 'griffenne',
		minLevel: 22,
		maxLevel: 24,
		size: .77,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.griffon,
		name: 'griffon',
		minLevel: 26,
		maxLevel: 28,
		size: .84,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.harpy,
		name: 'harpy',
		minLevel: 18,
		maxLevel: 20,
		size: .75,
		job: JOB.ENCHANTER,
	},
	{
		img: MOB_IMAGES.harpy,
		name: 'harpy pillager',
		minLevel: 23,
		maxLevel: 25,
		size: .8,
		job: JOB.ENCHANTER,
	},
	{
		img: MOB_IMAGES.harpy,
		name: 'harpy sapper',
		minLevel: 28,
		maxLevel: 30,
		size: .85,
		job: JOB.ENCHANTER,
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'greater skeleton',
		minLevel: 16,
		maxLevel: 18,
		size: .75,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'tormented skeleton',
		minLevel: 20,
		maxLevel: 22,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'dreadful skeleton',
		minLevel: 24,
		maxLevel: 26,
		size: .75,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'reclusive skeleton',
		minLevel: 28,
		maxLevel: 30,
		size: .75,
		job: JOB.WARRIOR,
	},
	// uniques
	{
		img: MOB_IMAGES.unicorn,
		name: 'Celeste',
		minLevel: 27,
		maxLevel: 27,
		size: .87,
		job: JOB.DRUID,
		tier: MOB_TIERS.unique,
		traits: { frenzy: true },
	},
	{
		img: MOB_IMAGES.unicorn,
		name: 'Solstice',
		minLevel: 22,
		maxLevel: 22,
		size: .8,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { lightningEnchanted: true },
	},
	{
		img: MOB_IMAGES.minotaur,
		name: 'Mendicant Zhavir',
		minLevel: 16,
		maxLevel: 16,
		size: .8,
		job: JOB.DRUID,
		tier: MOB_TIERS.unique,
		traits: { deadEye: true },
	},
	{
		img: MOB_IMAGES.minotaur,
		name: 'Patriarch Morakar',
		minLevel: 23,
		maxLevel: 23,
		size: .9,
		job: JOB.RANGER,
		tier: MOB_TIERS.unique,
		traits: { fireEnchanted: true },
	},
	{
		img: MOB_IMAGES.minotaur,
		name: 'Gladiator Drizius',
		minLevel: 28,
		maxLevel: 28,
		size: .97,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { brute: true },
	},
	{
		img: MOB_IMAGES.centaur,
		name: 'Stelasius the Quick',
		minLevel: 21,
		maxLevel: 21,
		size: .82,
		job: JOB.RANGER,
		tier: MOB_TIERS.unique,
		traits: { frenzy: true },
	},
	{
		img: MOB_IMAGES.centaur,
		name: 'Berserker Morphysus',
		minLevel: 27,
		maxLevel: 27,
		size: .89,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { dauntless: true },
	},
	{
		img: MOB_IMAGES.aviak,
		name: 'Riawk Corsair',
		minLevel: 24,
		maxLevel: 24,
		size: .85,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { deadEye: true },
	},
	{
		img: MOB_IMAGES.aviak,
		name: 'Qhessiak Lancer',
		minLevel: 28,
		maxLevel: 28,
		size: .9,
		job: JOB.DRUID,
		tier: MOB_TIERS.unique,
		traits: { fireEnchanted: true },
	},
	{
		img: MOB_IMAGES.griffon,
		name: 'Phantomfeather',
		minLevel: 30,
		maxLevel: 30,
		size: .92,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		traits: { brute: true },
	},
	{
		img: MOB_IMAGES.harpy,
		name: 'Volyphe',
		minLevel: 17,
		maxLevel: 17,
		size: .83,
		job: JOB.ENCHANTER,
		tier: MOB_TIERS.unique,
		traits: { poisonEnchanted: true },
	},
	{
		img: MOB_IMAGES.harpy,
		name: 'Zerone',
		minLevel: 26,
		maxLevel: 26,
		size: .86,
		job: JOB.WIZARD,
		tier: MOB_TIERS.unique,
		traits: { iceEnchanted: true },
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'Stormbellow',
		minLevel: 24,
		maxLevel: 24,
		size: .85,
		job: JOB.TEMPLAR,
		tier: MOB_TIERS.unique,
		traits: { lightningEnchanted: true },
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'Gloomshade',
		minLevel: 18,
		maxLevel: 18,
		size: .8,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { magister: true },
	},
	// quest mobs
	{
		img: MOB_IMAGES.minotaur,
		name: 'Trainer Grudor',
		minLevel: 18,
		maxLevel: 18,
		size: .8,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { dauntless: true },
	},
	{
		img: MOB_IMAGES.minotaur,
		name: 'Shadow Weaver Zamgara',
		minLevel: 20,
		maxLevel: 20,
		size: .84,
		job: JOB.WARLOCK,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { magister: true },
	},
	{
		img: MOB_IMAGES.minotaur,
		name: 'Hierophant Suprak',
		minLevel: 22,
		maxLevel: 22,
		size: .73,
		job: JOB.DRUID,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { iceEnchanted: true },
	},
	{
		img: MOB_IMAGES.minotaur,
		name: 'Blademaster Xamud',
		minLevel: 24,
		maxLevel: 24,
		size: .83,
		job: JOB.RANGER,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { fireEnchanted: true },
	},
	{
		img: MOB_IMAGES.minotaur,
		name: 'Mordin the Conqueror',
		minLevel: 26,
		maxLevel: 26,
		size: .89,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { brute: true },
	},
	{
		img: MOB_IMAGES.minotaur,
		name: 'Arch Bishop Griven',
		minLevel: 28,
		maxLevel: 28,
		size: .84,
		job: JOB.CLERIC,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { soulDrain: true },
	},
	{
		img: MOB_IMAGES.minotaur,
		name: 'Baron of Sylong',
		minLevel: 30,
		maxLevel: 30,
		size: .97,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { bloodlusted: true },
	},
]
mob.data[ZONES.thuleCrypt] = [
	{
		img: MOB_IMAGES.skeleton,
		name: 'skeletal warrior',
		minLevel: 20,
		maxLevel: 23,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'skeletal soldier',
		minLevel: 24,
		maxLevel: 27,
		size: .84,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'skeletal protector',
		minLevel: 28,
		maxLevel: 31,
		size: .88,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'skeletal guardian',
		minLevel: 32,
		maxLevel: 34,
		size: .92,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'skeletal warlock',
		minLevel: 20,
		maxLevel: 23,
		size: .75,
		job: JOB.WARLOCK,
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'skeletal ritualist',
		minLevel: 24,
		maxLevel: 27,
		size: .78,
		job: JOB.WARLOCK,
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'skeletal corruptor',
		minLevel: 28,
		maxLevel: 31,
		size: .81,
		job: JOB.WARLOCK,
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'skeletal oracle',
		minLevel: 32,
		maxLevel: 35,
		size: .84,
		job: JOB.WARLOCK,
	},
	{
		img: MOB_IMAGES.ghoul,
		name: 'festering ghoul',
		minLevel: 22,
		maxLevel: 24,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.ghoul,
		name: 'lumbering ghoul',
		minLevel: 27,
		maxLevel: 29,
		size: .85,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.ghoul,
		name: 'wighted ghoul',
		minLevel: 32,
		maxLevel: 34,
		size: .9,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.ghoul,
		name: 'prowling ghoul',
		minLevel: 24,
		maxLevel: 26,
		size: .75,
		job: JOB.ROGUE,
	},
	{
		img: MOB_IMAGES.ghoul,
		name: 'shadowy ghoul',
		minLevel: 28,
		maxLevel: 30,
		size: .8,
		job: JOB.ROGUE,
	},
	{
		img: MOB_IMAGES.ghoul,
		name: 'umbral ghoul',
		minLevel: 32,
		maxLevel: 34,
		size: .85,
		job: JOB.ROGUE,
	},
	{
		img: MOB_IMAGES.mummy,
		name: 'lurking mummy',
		minLevel: 20,
		maxLevel: 23,
		size: .74,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.mummy,
		name: 'skulking mummy',
		minLevel: 24,
		maxLevel: 27,
		size: .78,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.mummy,
		name: 'lurching mummy',
		minLevel: 28,
		maxLevel: 31,
		size: .82,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.mummy,
		name: 'tainted mummy',
		minLevel: 32,
		maxLevel: 35,
		size: .87,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.mummy,
		name: 'brawling mummy',
		minLevel: 22,
		maxLevel: 25,
		size: .7,
		job: JOB.MONK,
	},
	{
		img: MOB_IMAGES.mummy,
		name: 'vexed mummy',
		minLevel: 26,
		maxLevel: 29,
		size: .75,
		job: JOB.MONK,
	},
	{
		img: MOB_IMAGES.mummy,
		name: 'wrathful mummy',
		minLevel: 31,
		maxLevel: 34,
		size: .8,
		job: JOB.MONK,
	},
	{
		img: MOB_IMAGES.spectre,
		name: 'spectral usher',
		minLevel: 27,
		maxLevel: 29,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.spectre,
		name: 'spectral herald',
		minLevel: 30,
		maxLevel: 32,
		size: .85,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.spectre,
		name: 'spectral harbinger',
		minLevel: 33,
		maxLevel: 35,
		size: .9,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.spectre,
		name: 'spectral offerer',
		minLevel: 27,
		maxLevel: 29,
		size: .76,
		job: JOB.WARLOCK,
	},
	{
		img: MOB_IMAGES.spectre,
		name: 'spectral sacrificer',
		minLevel: 30,
		maxLevel: 32,
		size: .82,
		job: JOB.WARLOCK,
	},
	{
		img: MOB_IMAGES.spectre,
		name: 'spectral ritualist',
		minLevel: 33,
		maxLevel: 35,
		size: .86,
		job: JOB.WARLOCK,
	},
	{
		img: MOB_IMAGES.fungoid,
		name: 'myconid drone',
		minLevel: 27,
		maxLevel: 29,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.fungoid,
		name: 'myconid warrior',
		minLevel: 30,
		maxLevel: 32,
		size: .84,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.fungoid,
		name: 'myconid soldier',
		minLevel: 33,
		maxLevel: 35,
		size: .88,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.fungoid,
		name: 'myconid adept',
		minLevel: 27,
		maxLevel: 29,
		size: .75,
		job: JOB.CLERIC,
	},
	{
		img: MOB_IMAGES.fungoid,
		name: 'myconid priest',
		minLevel: 30,
		maxLevel: 32,
		size: .8,
		job: JOB.CLERIC,
	},
	{
		img: MOB_IMAGES.fungoid,
		name: 'myconid diviner',
		minLevel: 33,
		maxLevel: 35,
		size: .85,
		job: JOB.CLERIC,
	},
	{
		img: MOB_IMAGES.zombie,
		name: 'sapped zombie',
		minLevel: 22,
		maxLevel: 24,
		size: .73,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.zombie,
		name: 'enfeebled zombie',
		minLevel: 26,
		maxLevel: 28,
		size: .78,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.zombie,
		name: 'decrepit zombie',
		minLevel: 30,
		maxLevel: 32,
		size: .83,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.zombie,
		name: 'tormented zombie',
		minLevel: 34,
		maxLevel: 35,
		size: .88,
		job: JOB.WARRIOR,
	},
	// uniques
	{
		img: MOB_IMAGES.skeleton,
		name: 'Firefroth the Mad',
		minLevel: 21,
		maxLevel: 21,
		size: .77,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { fireEnchanted: true },
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'Plagueshard the Unclean',
		minLevel: 26,
		maxLevel: 26,
		size: .84,
		job: JOB.ROGUE,
		tier: MOB_TIERS.unique,
		traits: { poisonEnchanted: true },
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'Slatesnout the Desolator',
		minLevel: 33,
		maxLevel: 33,
		size: .91,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		traits: { tough: true },
	},
	{
		img: MOB_IMAGES.ghoul,
		name: 'Namrud the Insane',
		minLevel: 23,
		maxLevel: 23,
		size: .5,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { frenzy: true },
	},
	{
		img: MOB_IMAGES.ghoul,
		name: 'Peleg Hightower',
		minLevel: 34,
		maxLevel: 34,
		size: 1.1,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { spiritDrain: true },
	},
	{
		img: MOB_IMAGES.mummy,
		name: 'Scribe Beseth',
		minLevel: 24,
		maxLevel: 24,
		size: .7,
		job: JOB.TEMPLAR,
		tier: MOB_TIERS.unique,
		traits: { lightningEnchanted: true },
	},
	{
		img: MOB_IMAGES.mummy,
		name: 'Vizier Zigan',
		minLevel: 27,
		maxLevel: 27,
		size: .78,
		job: JOB.WIZARD,
		tier: MOB_TIERS.unique,
		traits: { magister: true },
	},
	{
		img: MOB_IMAGES.spectre,
		name: 'Fated Messenger Yeabotinth',
		minLevel: 30,
		maxLevel: 30,
		size: .93,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		traits: { deadEye: true },
	},
	{
		img: MOB_IMAGES.spectre,
		name: 'Death Lord Shota',
		minLevel: 34,
		maxLevel: 34,
		size: .98,
		job: JOB.WIZARD,
		tier: MOB_TIERS.unique,
		traits: { manaDrain: true },
	},
	{
		img: MOB_IMAGES.fungoid,
		name: 'Custodian Lerminum',
		minLevel: 25,
		maxLevel: 25,
		size: .8,
		job: JOB.MONK,
		tier: MOB_TIERS.unique,
		traits: { nimble: true },
	},
	{
		img: MOB_IMAGES.fungoid,
		name: 'Vicar Sothroph',
		minLevel: 29,
		maxLevel: 29,
		size: .85,
		job: JOB.CLERIC,
		tier: MOB_TIERS.unique,
		traits: { magister: true },
	},
	{
		img: MOB_IMAGES.zombie,
		name: 'Dung Harvester Maduki',
		minLevel: 21,
		maxLevel: 21,
		size: .77,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { poisonEnchanted: true },
	},
	{
		img: MOB_IMAGES.zombie,
		name: 'Gut Dimsworn',
		minLevel: 28,
		maxLevel: 28,
		size: .84,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { dauntless: true },
	},
	// quest mobs
	{
		img: MOB_IMAGES.skeleton,
		name: 'Undead Knight of Thule',
		minLevel: 22,
		maxLevel: 22,
		size: .75,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { poisonEnchanted: true },
	},
	{
		img: MOB_IMAGES.skeleton,
		name: 'Skeleton King Arcturus',
		minLevel: 24,
		maxLevel: 24,
		size: .94,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { tough: true },
	},
	{
		img: MOB_IMAGES.ghoul,
		name: 'Doctor Grelzn',
		minLevel: 26,
		maxLevel: 26,
		size: .85,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { soulDrain: true },
	},
	{
		img: MOB_IMAGES.ghoul,
		name: 'Contaminated Fiend',
		minLevel: 28,
		maxLevel: 28,
		size: .82,
		job: JOB.ROGUE,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { poisonEnchanted: true },
	},
	{
		img: MOB_IMAGES.mummy,
		name: 'Prince Heparot',
		minLevel: 30,
		maxLevel: 30,
		size: .95,
		job: JOB.SHAMAN,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { spiritDrain: true },
	},
	{
		img: MOB_IMAGES.fungoid,
		name: 'Myconid Spore King',
		minLevel: 32,
		maxLevel: 32,
		size: 1,
		job: JOB.CRUSADER,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { tough: true },
	},
	{
		img: MOB_IMAGES.spectre,
		name: 'Thulian Wraith Lord',
		minLevel: 35,
		maxLevel: 35,
		size: 1.05,
		job: JOB.WARLOCK,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { poisonEnchanted: true },
	},
]
mob.data[ZONES.templeOfPrenssor] = [
	{
		img: MOB_IMAGES.lizardman,
		name: 'lizardman broodling',
		minLevel: 24,
		maxLevel: 26,
		size: .75,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.lizardman,
		name: 'lizardman sentinel',
		minLevel: 27,
		maxLevel: 30,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.lizardman,
		name: 'lizardman defender',
		minLevel: 31,
		maxLevel: 34,
		size: .84,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.lizardman,
		name: 'lizardman fanatic',
		minLevel: 35,
		maxLevel: 37,
		size: .87,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.lizardman,
		name: 'lizardman champion',
		minLevel: 38,
		maxLevel: 40,
		size: .9,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.lizardman,
		name: 'lizardman page',
		minLevel: 24,
		maxLevel: 26,
		size: .7,
		job: JOB.CLERIC,
	},
	{
		img: MOB_IMAGES.lizardman,
		name: 'lizardman proselyte',
		minLevel: 27,
		maxLevel: 30,
		size: .74,
		job: JOB.CLERIC,
	},
	{
		img: MOB_IMAGES.lizardman,
		name: 'lizardman herald',
		minLevel: 31,
		maxLevel: 34,
		size: .78,
		job: JOB.CLERIC,
	},
	{
		img: MOB_IMAGES.lizardman,
		name: 'lizardman justicar',
		minLevel: 35,
		maxLevel: 37,
		size: .82,
		job: JOB.CLERIC,
	},
	{
		img: MOB_IMAGES.lizardman,
		name: 'lizardman judicator',
		minLevel: 38,
		maxLevel: 40,
		size: .86,
		job: JOB.CLERIC,
	},
	{
		img: MOB_IMAGES.lizardman,
		name: 'lizardman crusader',
		minLevel: 24,
		maxLevel: 27,
		size: .7,
		job: JOB.SHADOW_KNIGHT,
	},
	{
		img: MOB_IMAGES.lizardman,
		name: 'lizardman ritualist',
		minLevel: 26,
		maxLevel: 30,
		size: .7,
		job: JOB.WARLOCK,
	},
	{
		img: MOB_IMAGES.lizardman,
		name: 'lizardman harbinger',
		minLevel: 30,
		maxLevel: 34,
		size: .78,
		job: JOB.SHADOW_KNIGHT,
	},
	{
		img: MOB_IMAGES.lizardman,
		name: 'lizardman forbidder',
		minLevel: 34,
		maxLevel: 37,
		size: .78,
		job: JOB.WARLOCK,
	},
	{
		img: MOB_IMAGES.lizardman,
		name: 'lizardman zealot',
		minLevel: 37,
		maxLevel: 40,
		size: .86,
		job: JOB.SHADOW_KNIGHT,
	},
	{
		img: MOB_IMAGES.dragonkin,
		name: 'dragonkin brawler',
		minLevel: 30,
		maxLevel: 32,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.dragonkin,
		name: 'dragonkin mauler',
		minLevel: 33,
		maxLevel: 35,
		size: .84,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.dragonkin,
		name: 'dragonkin bludgeoner',
		minLevel: 36,
		maxLevel: 38,
		size: .88,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.dragonkin,
		name: 'blood dragonkin shaman',
		minLevel: 30,
		maxLevel: 32,
		size: .8,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.dragonkin,
		name: 'crimson dragonkin shaman',
		minLevel: 33,
		maxLevel: 35,
		size: .84,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.dragonkin,
		name: 'ruddy dragonkin shaman',
		minLevel: 36,
		maxLevel: 38,
		size: .88,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.crocodile,
		name: 'deepwater crocodile',
		minLevel: 24,
		maxLevel: 26,
		size: .75,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.crocodile,
		name: 'primeval crocodile',
		minLevel: 27,
		maxLevel: 29,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.crocodile,
		name: 'diluvial crocodile',
		minLevel: 30,
		maxLevel: 32,
		size: .86,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.stoneGolem,
		name: 'jagged stone golem',
		minLevel: 24,
		maxLevel: 25,
		size: .7,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.stoneGolem,
		name: 'rugged stone golem',
		minLevel: 26,
		maxLevel: 28,
		size: .75,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.stoneGolem,
		name: 'coarse stone golem',
		minLevel: 29,
		maxLevel: 31,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.ironGolem,
		name: 'coarse iron golem',
		minLevel: 32,
		maxLevel: 34,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.ironGolem,
		name: 'coarse iron golem',
		minLevel: 35,
		maxLevel: 37,
		size: .85,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.ironGolem,
		name: 'coarse iron golem',
		minLevel: 38,
		maxLevel: 40,
		size: .9,
		job: JOB.WARRIOR,
	},
	// uniques
	{
		img: MOB_IMAGES.lizardman,
		name: 'Caitiff Kozua',
		minLevel: 25,
		maxLevel: 25,
		size: .8,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { nimble: true },
	},
	{
		img: MOB_IMAGES.lizardman,
		name: 'Curator Thex',
		minLevel: 30,
		maxLevel: 30,
		size: .84,
		job: JOB.SHAMAN,
		tier: MOB_TIERS.unique,
		traits: { iceEnchanted: true },
	},
	{
		img: MOB_IMAGES.lizardman,
		name: 'Apostle Egzie',
		minLevel: 33,
		maxLevel: 33,
		size: .82,
		job: JOB.ENCHANTER,
		tier: MOB_TIERS.unique,
		traits: { frenzy: true },
	},
	{
		img: MOB_IMAGES.lizardman,
		name: 'Evangelist Grothax',
		minLevel: 36,
		maxLevel: 36,
		size: .86,
		job: JOB.CRUSADER,
		tier: MOB_TIERS.unique,
		traits: { magister: true },
	},
	{
		img: MOB_IMAGES.dragonkin,
		name: 'Scion Molzagg',
		minLevel: 32,
		maxLevel: 32,
		size: .66,
		job: JOB.WIZARD,
		tier: MOB_TIERS.unique,
		traits: { fireEnchanted: true },
	},
	{
		img: MOB_IMAGES.dragonkin,
		name: 'Decapitator Ighremuth',
		minLevel: 35,
		maxLevel: 35,
		size: .94,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { brute: true },
	},
	{
		img: MOB_IMAGES.crocodile,
		name: 'colossal crocodile',
		minLevel: 31,
		maxLevel: 31,
		size: 1.1,
		job: JOB.DRUID,
		tier: MOB_TIERS.unique,
		traits: { tough: true },
	},
	{
		img: MOB_IMAGES.stoneGolem,
		name: 'Guardian Yochem',
		minLevel: 28,
		maxLevel: 28,
		size: .88,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { spiritDrain: true },
	},
	{
		img: MOB_IMAGES.ironGolem,
		name: 'Guardian Amidar',
		minLevel: 35,
		maxLevel: 35,
		size: .94,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { deadEye: true },
	},
	// quest mobs
	{
		img: MOB_IMAGES.lizardman,
		name: 'Adjudicator Vizk',
		minLevel: 26,
		maxLevel: 26,
		size: .75,
		job: JOB.ROGUE,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { poisonEnchanted: true },
	},
	{
		img: MOB_IMAGES.lizardman,
		name: 'Magistrate Kuthok',
		minLevel: 28,
		maxLevel: 28,
		size: .72,
		job: JOB.WIZARD,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { iceEnchanted: true },
	},
	{
		img: MOB_IMAGES.stoneGolem,
		name: 'Roggok',
		minLevel: 30,
		maxLevel: 30,
		size: .86,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { soulDrain: true },
	},
	{
		img: MOB_IMAGES.crocodile,
		name: 'Krushilgreth',
		minLevel: 32,
		maxLevel: 32,
		size: 1.1,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { brute: true },
	},
	{
		img: MOB_IMAGES.lizardman,
		name: 'Emperor Gox',
		minLevel: 34,
		maxLevel: 34,
		size: .96,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { bloodlusted: true },
	},
	{
		img: MOB_IMAGES.dragonkin,
		name: 'Archon Biltoth',
		minLevel: 36,
		maxLevel: 36,
		size: .95,
		job: JOB.TEMPLAR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { lightningEnchanted: true },
	},
	{
		img: MOB_IMAGES.ironGolem,
		name: 'Champion Drazzok',
		minLevel: 38,
		maxLevel: 38,
		size: 1,
		job: JOB.MONK,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { tough: true },
	},
	{
		img: MOB_IMAGES.giant,
		name: 'Avatar of Blood',
		minLevel: 40,
		maxLevel: 40,
		size: .8,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { bloodlusted: true },
	},
]
mob.data[ZONES.fahlnirCitadel] = [
	{
		img: MOB_IMAGES.vampire,
		name: 'vampire sapper',
		minLevel: 28,
		maxLevel: 31,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.vampire,
		name: 'vampire pillager',
		minLevel: 32,
		maxLevel: 35,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.vampire,
		name: 'vampire ravisher',
		minLevel: 36,
		maxLevel: 39,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.vampire,
		name: 'vampire marauder',
		minLevel: 40,
		maxLevel: 43,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.vampire,
		name: 'vampire tempter',
		minLevel: 28,
		maxLevel: 31,
		size: .8,
		job: JOB.WARLOCK,
	},
	{
		img: MOB_IMAGES.vampire,
		name: 'vampire seducer',
		minLevel: 32,
		maxLevel: 35,
		size: .8,
		job: JOB.WARLOCK,
	},
	{
		img: MOB_IMAGES.vampire,
		name: 'vampire inveigling',
		minLevel: 36,
		maxLevel: 39,
		size: .8,
		job: JOB.WARLOCK,
	},
	{
		img: MOB_IMAGES.vampire,
		name: 'vampire cajoler',
		minLevel: 40,
		maxLevel: 43,
		size: .8,
		job: JOB.WARLOCK,
	},
	{
		img: MOB_IMAGES.vampire,
		name: 'vampire spoiler',
		minLevel: 28,
		maxLevel: 31,
		size: .8,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.vampire,
		name: 'vampire defiler',
		minLevel: 32,
		maxLevel: 35,
		size: .8,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.vampire,
		name: 'vampire noble',
		minLevel: 36,
		maxLevel: 39,
		size: .8,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.vampire,
		name: 'vampire oracle',
		minLevel: 40,
		maxLevel: 43,
		size: .8,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.gargoyle,
		name: 'grinning gargoyle',
		minLevel: 28,
		maxLevel: 30,
		size: .72,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.gargoyle,
		name: 'sneering gargoyle',
		minLevel: 31,
		maxLevel: 34,
		size: .76,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.gargoyle,
		name: 'jeering gargoyle',
		minLevel: 35,
		maxLevel: 38,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.gargoyle,
		name: 'flouting gargoyle',
		minLevel: 39,
		maxLevel: 42,
		size: .84,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.gargoyle,
		name: 'leering gargoyle',
		minLevel: 43,
		maxLevel: 45,
		size: .88,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.werewolf,
		name: 'werewolf roamer',
		minLevel: 32,
		maxLevel: 34,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.werewolf,
		name: 'werewolf lurker',
		minLevel: 35,
		maxLevel: 37,
		size: .84,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.werewolf,
		name: 'werewolf scavenger',
		minLevel: 38,
		maxLevel: 40,
		size: .88,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.werewolf,
		name: 'werewolf rambler',
		minLevel: 41,
		maxLevel: 43,
		size: .92,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.ghoul,
		name: 'rancid ghoul',
		minLevel: 34,
		maxLevel: 36,
		size: .7,
		job: JOB.ROGUE,
	},
	{
		img: MOB_IMAGES.ghoul,
		name: 'abhorrent ghoul',
		minLevel: 37,
		maxLevel: 39,
		size: .74,
		job: JOB.ROGUE,
	},
	{
		img: MOB_IMAGES.ghoul,
		name: 'festering ghoul',
		minLevel: 40,
		maxLevel: 42,
		size: .78,
		job: JOB.ROGUE,
	},
	{
		img: MOB_IMAGES.ghoul,
		name: 'blighted ghoul',
		minLevel: 43,
		maxLevel: 45,
		size: .82,
		job: JOB.ROGUE,
	},
	{
		img: MOB_IMAGES.giant,
		name: 'arclite golem',
		minLevel: 34,
		maxLevel: 36,
		size: .5,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.giant,
		name: 'arclite guardian',
		minLevel: 37,
		maxLevel: 39,
		size: .53,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.giant,
		name: 'arclite juggernaut',
		minLevel: 40,
		maxLevel: 42,
		size: .56,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.giant,
		name: 'arclite protector',
		minLevel: 43,
		maxLevel: 45,
		size: .6,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.imp,
		name: 'dire imp',
		minLevel: 34,
		maxLevel: 36,
		size: .78,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.imp,
		name: 'ominous imp',
		minLevel: 37,
		maxLevel: 39,
		size: .82,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.imp,
		name: 'stygian imp',
		minLevel: 40,
		maxLevel: 42,
		size: .85,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.imp,
		name: 'tenebrous imp',
		minLevel: 43,
		maxLevel: 45,
		size: .88,
		job: JOB.WIZARD,
	},
	// uniques
	{
		img: MOB_IMAGES.vampire,
		name: 'Lothaire the Glyphed',
		minLevel: 29,
		maxLevel: 29,
		size: .8,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { dauntless: true },
	},
	{
		img: MOB_IMAGES.vampire,
		name: 'Alchemist Cynfael',
		minLevel: 33,
		maxLevel: 33,
		size: .8,
		job: JOB.ROGUE,
		tier: MOB_TIERS.unique,
		traits: { soulDrain: true },
	},
	{
		img: MOB_IMAGES.vampire,
		name: 'Duke Draven Graymoore',
		minLevel: 36,
		maxLevel: 36,
		size: .88,
		job: JOB.WIZARD,
		tier: MOB_TIERS.unique,
		traits: { fireEnchanted: true },
	},
	{
		img: MOB_IMAGES.vampire,
		name: 'Count Enoch Melchoir',
		minLevel: 41,
		maxLevel: 41,
		size: .9,
		job: JOB.WARLOCK,
		tier: MOB_TIERS.unique,
		traits: { magister: true },
	},
	{
		img: MOB_IMAGES.gargoyle,
		name: 'Kruzron',
		minLevel: 32,
		maxLevel: 32,
		size: .9,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { tough: true },
	},
	{
		img: MOB_IMAGES.gargoyle,
		name: 'Amock',
		minLevel: 40,
		maxLevel: 40,
		size: .9,
		job: JOB.ROGUE,
		tier: MOB_TIERS.unique,
		traits: { brute: true },
	},
	{
		img: MOB_IMAGES.werewolf,
		name: 'Zegrath',
		minLevel: 35,
		maxLevel: 35,
		size: .94,
		job: JOB.SHAMAN,
		tier: MOB_TIERS.unique,
		traits: { iceEnchanted: true },
	},
	{
		img: MOB_IMAGES.ghoul,
		name: 'frenzied ghoul',
		minLevel: 43,
		maxLevel: 43,
		size: .66,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { frenzy: true },
	},
	{
		img: MOB_IMAGES.giant,
		name: 'Legionnaire Todwar',
		minLevel: 41,
		maxLevel: 41,
		size: .62,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { tough: true },
	},
	{
		img: MOB_IMAGES.giant,
		name: 'Magi Zilsal',
		minLevel: 44,
		maxLevel: 44,
		size: .65,
		job: JOB.DRUID,
		tier: MOB_TIERS.unique,
		traits: { fireEnchanted: true },
	},
	{
		img: MOB_IMAGES.imp,
		name: 'Troubadour Qron',
		minLevel: 37,
		maxLevel: 37,
		size: 1,
		job: JOB.BARD,
		tier: MOB_TIERS.unique,
		traits: { fireEnchanted: true },
	},
	// quest mobs
	{
		img: MOB_IMAGES.vampire,
		name: 'Desiccator Lauden',
		minLevel: 30,
		maxLevel: 30,
		size: .8,
		job: JOB.WARLOCK,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { fireEnchanted: true },
	},
	{
		img: MOB_IMAGES.vampire,
		name: 'Acolyte Viscardi',
		minLevel: 32,
		maxLevel: 32,
		size: .85,
		job: JOB.WIZARD,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { nimble: true },
	},
	{
		img: MOB_IMAGES.gargoyle,
		name: 'Royal Guard Stolgazz',
		minLevel: 34,
		maxLevel: 34,
		size: 1,
		job: JOB.ROGUE,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { deadEye: true },
	},
	{
		img: MOB_IMAGES.vampire,
		name: 'Captain Odolff',
		minLevel: 36,
		maxLevel: 36,
		size: .8,
		job: JOB.CRUSADER,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { magister: true },
	},
	{
		img: MOB_IMAGES.imp,
		name: 'Jester Kekjo',
		minLevel: 38,
		maxLevel: 38,
		size: .87,
		job: JOB.TEMPLAR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { lightningEnchanted: true },
	},
	{
		img: MOB_IMAGES.vampire,
		name: 'Baron Lucien',
		minLevel: 40,
		maxLevel: 40,
		size: .83,
		job: JOB.ENCHANTER,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { frenzied: true },
	},
	{
		img: MOB_IMAGES.giant,
		name: 'Warder Yissachai',
		minLevel: 42,
		maxLevel: 42,
		size: .65,
		job: JOB.SHAMAN,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { poisonEnchanted: true },
	},
	{
		img: MOB_IMAGES.vampire,
		name: 'Lord Solomon Fahlnir',
		minLevel: 45,
		maxLevel: 45,
		size: 1.1,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { spiritDrain: true },
	},
]
mob.data[ZONES.anuranRuins] = [
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok phin warrior',
		minLevel: 32,
		maxLevel: 35,
		size: .77,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok gur warrior',
		minLevel: 36,
		maxLevel: 39,
		size: .81,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok kel warrior',
		minLevel: 40,
		maxLevel: 43,
		size: .84,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok thul warrior',
		minLevel: 44,
		maxLevel: 47,
		size: .87,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok zog warrior',
		minLevel: 48,
		maxLevel: 50,
		size: .9,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok phin knight',
		minLevel: 32,
		maxLevel: 35,
		size: .77,
		job: JOB.CRUSADER,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok gur knight',
		minLevel: 36,
		maxLevel: 39,
		size: .81,
		job: JOB.CRUSADER,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok kel knight',
		minLevel: 40,
		maxLevel: 43,
		size: .84,
		job: JOB.CRUSADER,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok thul knight',
		minLevel: 44,
		maxLevel: 47,
		size: .87,
		job: JOB.CRUSADER,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok zog knight',
		minLevel: 48,
		maxLevel: 50,
		size: .9,
		job: JOB.CRUSADER,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok phin shaman',
		minLevel: 32,
		maxLevel: 35,
		size: .77,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok gur shaman',
		minLevel: 36,
		maxLevel: 39,
		size: .81,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok kel shaman',
		minLevel: 40,
		maxLevel: 43,
		size: .84,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok thul shaman',
		minLevel: 44,
		maxLevel: 47,
		size: .87,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok zog shaman',
		minLevel: 48,
		maxLevel: 50,
		size: .9,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok phin wizard',
		minLevel: 32,
		maxLevel: 35,
		size: .77,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok gur wizard',
		minLevel: 36,
		maxLevel: 39,
		size: .81,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok kel wizard',
		minLevel: 40,
		maxLevel: 43,
		size: .84,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok thul wizard',
		minLevel: 44,
		maxLevel: 47,
		size: .87,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'toadlok zog wizard',
		minLevel: 48,
		maxLevel: 50,
		size: .9,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.minotaur,
		name: 'minotaur slayer',
		minLevel: 32,
		maxLevel: 34,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.minotaur,
		name: 'minotaur butcher',
		minLevel: 35,
		maxLevel: 37,
		size: .83,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.minotaur,
		name: 'minotaur slaughterer',
		minLevel: 38,
		maxLevel: 40,
		size: .87,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.gargoyle,
		name: 'gargoyle deviant',
		minLevel: 34,
		maxLevel: 36,
		size: .74,
		job: JOB.ROGUE,
	},
	{
		img: MOB_IMAGES.gargoyle,
		name: 'gargoyle knave',
		minLevel: 37,
		maxLevel: 39,
		size: .78,
		job: JOB.ROGUE,
	},
	{
		img: MOB_IMAGES.gargoyle,
		name: 'gargoyle reprobate',
		minLevel: 40,
		maxLevel: 42,
		size: .82,
		job: JOB.ROGUE,
	},
	{
		img: MOB_IMAGES.fungoid,
		name: 'syconid friar',
		minLevel: 41,
		maxLevel: 43,
		size: .76,
		job: JOB.CLERIC,
	},
	{
		img: MOB_IMAGES.fungoid,
		name: 'syconid bishop',
		minLevel: 44,
		maxLevel: 46,
		size: .8,
		job: JOB.CLERIC,
	},
	{
		img: MOB_IMAGES.fungoid,
		name: 'syconid priest',
		minLevel: 47,
		maxLevel: 49,
		size: .84,
		job: JOB.CLERIC,
	},
	{
		img: MOB_IMAGES.giant,
		name: 'ziggurat defender',
		minLevel: 42,
		maxLevel: 44,
		size: .58,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.giant,
		name: 'ziggurat enforcer',
		minLevel: 45,
		maxLevel: 47,
		size: .6,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.giant,
		name: 'ziggurat guardian',
		minLevel: 48,
		maxLevel: 50,
		size: .62,
		job: JOB.WARRIOR,
	},
	// uniques
	{
		img: MOB_IMAGES.toadlok,
		name: 'Bone Collector Froimzogz',
		minLevel: 34,
		maxLevel: 34,
		size: .76,
		job: JOB.SHAMAN,
		tier: MOB_TIERS.unique,
		traits: { poisonEnchanted: true },
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'Cavalier Egurd',
		minLevel: 37,
		maxLevel: 37,
		size: .83,
		job: JOB.CRUSADER,
		tier: MOB_TIERS.unique,
		traits: { nimble: true },
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'Executioner Trug',
		minLevel: 39,
		maxLevel: 39,
		size: .88,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { brute: true },
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'Tactician Wrenk',
		minLevel: 42,
		maxLevel: 42,
		size: .76,
		job: JOB.WIZARD,
		tier: MOB_TIERS.unique,
		traits: { fireEnchanted: true },
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'Scribe Thrung',
		minLevel: 44,
		maxLevel: 44,
		size: .76,
		job: JOB.TEMPLAR,
		tier: MOB_TIERS.unique,
		traits: { lightningEnchanted: true },
	},
	{
		img: MOB_IMAGES.minotaur,
		name: 'Captain Warmud',
		minLevel: 36,
		maxLevel: 36,
		size: .85,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { spiritDrain: true },
	},
	{
		img: MOB_IMAGES.gargoyle,
		name: 'Seer Konim',
		minLevel: 38,
		maxLevel: 38,
		size: .9,
		job: JOB.WIZARD,
		tier: MOB_TIERS.unique,
		traits: { magister: true },
	},
	{
		img: MOB_IMAGES.fungoid,
		name: 'Disciple Polixio',
		minLevel: 45,
		maxLevel: 45,
		size: .85,
		job: JOB.MONK,
		tier: MOB_TIERS.unique,
		traits: { fireEnchanted: true },
	},
	{
		img: MOB_IMAGES.fungoid,
		name: 'Master Salaphise',
		minLevel: 42,
		maxLevel: 42,
		size: .82,
		job: JOB.MONK,
		tier: MOB_TIERS.unique,
		traits: { bloodlusted: true },
	},
	{
		img: MOB_IMAGES.giant,
		name: 'Colossus Einzugath',
		minLevel: 47,
		maxLevel: 47,
		size: .65,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { tough: true },
	},
	{
		img: MOB_IMAGES.giant,
		name: 'Colossus Jusashith',
		minLevel: 49,
		maxLevel: 49,
		size: .66,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { spiritDrain: true },
	},
	// quest mobs
	{
		img: MOB_IMAGES.toadlok,
		name: 'Assassin Shex',
		minLevel: 34,
		maxLevel: 34,
		size: .75,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { deadEye: true },
	},
	{
		img: MOB_IMAGES.evilEye,
		name: 'Gazer Nazozeth',
		minLevel: 36,
		maxLevel: 36,
		size: .89,
		job: JOB.ENCHANTER,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { magister: true },
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'Minister Isizz',
		minLevel: 38,
		maxLevel: 38,
		size: .77,
		job: JOB.CLERIC,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { dauntless: true },
	},
	{
		img: MOB_IMAGES.minotaur,
		name: 'Tracker Zydius',
		minLevel: 40,
		maxLevel: 40,
		size: .8,
		job: JOB.RANGER,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { tough: true },
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'Sentinel Urgyts',
		minLevel: 42,
		maxLevel: 42,
		size: .86,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { soulDrain: true },
	},
	{
		img: MOB_IMAGES.fungoid,
		name: 'Caretaker Mystis',
		minLevel: 44,
		maxLevel: 44,
		size: .73,
		job: JOB.CLERIC,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { frenzy: true },
	},
	{
		img: MOB_IMAGES.giant,
		name: 'Avatar Gresgrog',
		minLevel: 46,
		maxLevel: 46,
		size: .63,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { tough: true },
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'Arch Magus Gurka',
		minLevel: 48,
		maxLevel: 48,
		size: .75,
		job: JOB.WIZARD,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { iceEnchanted: true },
	},
	{
		img: MOB_IMAGES.toadlok,
		name: 'Toadlok King Frogold',
		minLevel: 50,
		maxLevel: 50,
		size: .94,
		job: JOB.CRUSADER,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { magister: true },
	},
]
mob.data[ZONES.galeblastFortress] = [
	{
		img: MOB_IMAGES.goblin,
		name: 'ice goblin warrior',
		minLevel: 35,
		maxLevel: 38,
		size: .75,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'frost goblin warrior',
		minLevel: 39,
		maxLevel: 42,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'boreal goblin warrior',
		minLevel: 43,
		maxLevel: 45,
		size: .85,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'ice goblin warrior',
		minLevel: 35,
		maxLevel: 38,
		size: .75,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'frost goblin warrior',
		minLevel: 39,
		maxLevel: 42,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'boreal goblin warrior',
		minLevel: 43,
		maxLevel: 45,
		size: .85,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'ice goblin priest',
		minLevel: 35,
		maxLevel: 38,
		size: .75,
		job: JOB.CLERIC,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'frost goblin priest',
		minLevel: 39,
		maxLevel: 42,
		size: .8,
		job: JOB.CLERIC,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'boreal goblin priest',
		minLevel: 43,
		maxLevel: 45,
		size: .85,
		job: JOB.CLERIC,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'ice goblin wizard',
		minLevel: 35,
		maxLevel: 38,
		size: .75,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'frost goblin wizard',
		minLevel: 39,
		maxLevel: 42,
		size: .8,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'boreal goblin wizard',
		minLevel: 43,
		maxLevel: 45,
		size: .85,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'ice goblin shaman',
		minLevel: 35,
		maxLevel: 38,
		size: .75,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'frost goblin shaman',
		minLevel: 39,
		maxLevel: 42,
		size: .8,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'boreal goblin shaman',
		minLevel: 43,
		maxLevel: 45,
		size: .85,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.wolfArctic,
		name: 'lurking dire wolf',
		minLevel: 38,
		maxLevel: 41,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.wolfArctic,
		name: 'prowling dire wolf',
		minLevel: 42,
		maxLevel: 45,
		size: .85,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.wolfArctic,
		name: 'giant dire wolf',
		minLevel: 46,
		maxLevel: 48,
		size: 1,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.bearPolar,
		name: 'icy polar bear',
		minLevel: 41,
		maxLevel: 44,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.bearPolar,
		name: 'glacial polar bear',
		minLevel: 45,
		maxLevel: 47,
		size: .85,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.bearPolar,
		name: 'giant polar bear',
		minLevel: 48,
		maxLevel: 50,
		size: 1,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.iceGolem,
		name: 'icy golem warrior',
		minLevel: 43,
		maxLevel: 45,
		size: .75,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.iceGolem,
		name: 'frost golem warrior',
		minLevel: 46,
		maxLevel: 48,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.iceGolem,
		name: 'boreal golem warrior',
		minLevel: 49,
		maxLevel: 51,
		size: .85,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.iceGolem,
		name: 'icy golem shaman',
		minLevel: 43,
		maxLevel: 45,
		size: .75,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.iceGolem,
		name: 'frost golem shaman',
		minLevel: 46,
		maxLevel: 48,
		size: .8,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.iceGolem,
		name: 'boreal golem shaman',
		minLevel: 49,
		maxLevel: 51,
		size: .85,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.iceGiant,
		name: 'ice giant warrior',
		minLevel: 48,
		maxLevel: 49,
		size: .88,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.iceGiant,
		name: 'ice giant destroyer',
		minLevel: 50,
		maxLevel: 51,
		size: .9,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.iceGiant,
		name: 'ice giant conqueror',
		minLevel: 52,
		maxLevel: 53,
		size: .92,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.iceGiant,
		name: 'ice giant wizard',
		minLevel: 48,
		maxLevel: 49,
		size: .88,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.iceGiant,
		name: 'ice giant sorcerer',
		minLevel: 50,
		maxLevel: 51,
		size: .9,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.iceGiant,
		name: 'ice giant magus',
		minLevel: 52,
		maxLevel: 53,
		size: .92,
		job: JOB.WIZARD,
	},
	// uniques
	{
		img: MOB_IMAGES.goblin,
		name: 'Scryer Tigmak',
		minLevel: 36,
		maxLevel: 36,
		size: .82,
		job: JOB.SHAMAN,
		tier: MOB_TIERS.unique,
		traits: { poisonEnchanted: true },
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'Priest Orm of Galeblast',
		minLevel: 38,
		maxLevel: 38,
		size: .84,
		job: JOB.CLERIC,
		tier: MOB_TIERS.unique,
		traits: { nimble: true },
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'Supplier Krozz',
		minLevel: 39,
		maxLevel: 39,
		size: .86,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { lightningEnchanted: true },
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'Architect Crang',
		minLevel: 41,
		maxLevel: 41,
		size: .83,
		job: JOB.ENCHANTER,
		tier: MOB_TIERS.unique,
		traits: { soulDrain: true },
	},
	{
		img: MOB_IMAGES.wolfArctic,
		name: 'Hrodulf the Hunter',
		minLevel: 43,
		maxLevel: 43,
		size: .95,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { bloodlusted: true },
	},
	{
		img: MOB_IMAGES.bearPolar,
		name: 'Arkojo the Mauler',
		minLevel: 45,
		maxLevel: 45,
		size: 1.1,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { brute: true },
	},
	{
		img: MOB_IMAGES.iceGolem,
		name: 'Reaver Grezzlon',
		minLevel: 48,
		maxLevel: 48,
		size: .96,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		traits: { brute: true },
	},
	{
		img: MOB_IMAGES.iceGolem,
		name: 'Preserver Yissahar',
		minLevel: 50,
		maxLevel: 50,
		size: .92,
		job: JOB.DRUID,
		tier: MOB_TIERS.unique,
		traits: { iceEnchanted: true },
	},
	{
		img: MOB_IMAGES.iceGiant,
		name: 'Diplomat Brelkos',
		minLevel: 51,
		maxLevel: 51,
		size: .9,
		job: JOB.ENCHANTER,
		tier: MOB_TIERS.unique,
		traits: { magister: true },
	},
	{
		img: MOB_IMAGES.iceGiant,
		name: 'Grand Vizier Gloziar',
		minLevel: 52,
		maxLevel: 52,
		size: .91,
		job: JOB.WIZARD,
		tier: MOB_TIERS.unique,
		traits: { nimble: true },
	},
	{
		img: MOB_IMAGES.iceGiant,
		name: 'Warlord Marthor',
		minLevel: 53,
		maxLevel: 53,
		size: .94,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { iceEnchanted: true },
	},
	// quest mobs
	{
		img: MOB_IMAGES.goblinIce,
		name: 'Bishop Goktal',
		minLevel: 37,
		maxLevel: 37,
		size: .82,
		job: JOB.MONK,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { bloodlusted: true },
	},
	{
		img: MOB_IMAGES.goblinIce,
		name: 'Pontiff Kramorx',
		minLevel: 39,
		maxLevel: 39,
		size: .85,
		job: JOB.CLERIC,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { spiritDrain: true },
	},
	{
		img: MOB_IMAGES.goblinIce,
		name: 'Ambassador Volsork',
		minLevel: 41,
		maxLevel: 41,
		size: .89,
		job: JOB.ROGUE,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { deadEye: true },
	},
	{
		img: MOB_IMAGES.goblinIce,
		name: 'Magnate Korreac',
		minLevel: 43,
		maxLevel: 43,
		size: .93,
		job: JOB.SHAMAN,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { frenzy: true },
	},
	{
		img: MOB_IMAGES.iceGolem,
		name: 'Goliath Azaruch',
		minLevel: 45,
		maxLevel: 45,
		size: .98,
		job: JOB.SHAMAN,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { iceEnchanted: true },
	},
	{
		img: MOB_IMAGES.iceGiant,
		name: 'Champion Krokkos',
		minLevel: 47,
		maxLevel: 47,
		size: .92,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { brute: true },
	},
	{
		img: MOB_IMAGES.iceGiant,
		name: 'Vizier Kongumen Divorn',
		minLevel: 49,
		maxLevel: 49,
		size: .9,
		job: JOB.WIZARD,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { iceEnchanted: true },
	},
	{
		img: MOB_IMAGES.iceGiant,
		name: 'King Margrave Kalgresh',
		minLevel: 51,
		maxLevel: 51,
		size: .95,
		job: JOB.CRUSADER,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { tough: true },
	},
	{
		img: MOB_IMAGES.dragonFrost,
		name: 'Matron Maelentia',
		minLevel: 55,
		maxLevel: 55,
		size: 1,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { iceEnchanted: true },
	},
]
mob.data[ZONES.ashenflowPeak] = [
	{
		img: MOB_IMAGES.goblinFire,
		name: 'fire goblin warrior',
		minLevel: 35,
		maxLevel: 37,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.goblinFire,
		name: 'cinder goblin warrior',
		minLevel: 38,
		maxLevel: 40,
		size: .84,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.goblinFire,
		name: 'inferno goblin warrior',
		minLevel: 41,
		maxLevel: 43,
		size: .88,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.goblinFire,
		name: 'fire goblin warrior',
		minLevel: 35,
		maxLevel: 37,
		size: .8,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.goblinFire,
		name: 'cinder goblin warrior',
		minLevel: 38,
		maxLevel: 40,
		size: .84,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.goblinFire,
		name: 'inferno goblin warrior',
		minLevel: 41,
		maxLevel: 43,
		size: .88,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.goblinFire,
		name: 'fire goblin shaman',
		minLevel: 35,
		maxLevel: 37,
		size: .8,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.goblinFire,
		name: 'cinder goblin shaman',
		minLevel: 38,
		maxLevel: 40,
		size: .84,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.goblinFire,
		name: 'inferno goblin shaman',
		minLevel: 41,
		maxLevel: 43,
		size: .88,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.goblinFire,
		name: 'fire goblin wizard',
		minLevel: 35,
		maxLevel: 37,
		size: .8,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.goblinFire,
		name: 'cinder goblin wizard',
		minLevel: 38,
		maxLevel: 40,
		size: .84,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.goblinFire,
		name: 'inferno goblin wizard',
		minLevel: 41,
		maxLevel: 43,
		size: .88,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.kobold,
		name: 'greater kobold warrior',
		minLevel: 42,
		maxLevel: 44,
		size: .85,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.kobold,
		name: 'Ashenflow kobold warrior',
		minLevel: 45,
		maxLevel: 47,
		size: .9,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.kobold,
		name: 'greater kobold warrior',
		minLevel: 42,
		maxLevel: 44,
		size: .85,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.kobold,
		name: 'Ashenflow kobold warrior',
		minLevel: 45,
		maxLevel: 47,
		size: .9,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.kobold,
		name: 'greater kobold shaman',
		minLevel: 42,
		maxLevel: 44,
		size: .85,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.kobold,
		name: 'Ashenflow kobold shaman',
		minLevel: 45,
		maxLevel: 47,
		size: .9,
		job: JOB.SHAMAN,
	},
	{
		img: MOB_IMAGES.kobold,
		name: 'greater kobold templar',
		minLevel: 42,
		maxLevel: 44,
		size: .8,
		job: JOB.TEMPLAR,
	},
	{
		img: MOB_IMAGES.kobold,
		name: 'Ashenflow kobold templar',
		minLevel: 45,
		maxLevel: 47,
		size: .85,
		job: JOB.TEMPLAR,
	},
	{
		img: MOB_IMAGES.imp,
		name: 'imp trickster',
		minLevel: 44,
		maxLevel: 45,
		size: .82,
		job: JOB.ROGUE,
	},
	{
		img: MOB_IMAGES.imp,
		name: 'imp rake',
		minLevel: 46,
		maxLevel: 47,
		size: .85,
		job: JOB.ROGUE,
	},
	{
		img: MOB_IMAGES.imp,
		name: 'imp blackguard',
		minLevel: 48,
		maxLevel: 48,
		size: .88,
		job: JOB.ROGUE,
	},
	{
		img: MOB_IMAGES.balrog,
		name: 'Ashenflow balrog knight',
		minLevel: 49,
		maxLevel: 49,
		size: .85,
		job: JOB.SHADOW_KNIGHT,
	},
	{
		img: MOB_IMAGES.balrog,
		name: 'Ashenflow balrog revenant',
		minLevel: 50,
		maxLevel: 50,
		size: .88,
		job: JOB.SHADOW_KNIGHT,
	},
	{
		img: MOB_IMAGES.balrog,
		name: 'Ashenflow balrog death lord',
		minLevel: 51,
		maxLevel: 51,
		size: .9,
		job: JOB.SHADOW_KNIGHT,
	},
	{
		img: MOB_IMAGES.cerberus,
		name: 'inferno cerberus',
		minLevel: 49,
		maxLevel: 49,
		size: .88,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.cerberus,
		name: 'blazing cerberus',
		minLevel: 50,
		maxLevel: 50,
		size: .92,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.cerberus,
		name: 'volcanic cerberus',
		minLevel: 51,
		maxLevel: 51,
		size: .96,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.fireGiant,
		name: 'fire giant warrior',
		minLevel: 48,
		maxLevel: 49,
		size: .88,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.fireGiant,
		name: 'fire giant avenger',
		minLevel: 50,
		maxLevel: 51,
		size: .9,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.fireGiant,
		name: 'fire giant gladiator',
		minLevel: 52,
		maxLevel: 53,
		size: .92,
		job: JOB.WARRIOR,
	},
	{
		img: MOB_IMAGES.fireGiant,
		name: 'fire giant wizard',
		minLevel: 48,
		maxLevel: 49,
		size: .88,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.fireGiant,
		name: 'fire giant diviner',
		minLevel: 50,
		maxLevel: 51,
		size: .9,
		job: JOB.WIZARD,
	},
	{
		img: MOB_IMAGES.fireGiant,
		name: 'fire giant mage',
		minLevel: 52,
		maxLevel: 53,
		size: .92,
		job: JOB.WIZARD,
	},
	// uniques
	{
		img: MOB_IMAGES.goblin,
		name: 'Engineer Kledlearm',
		minLevel: 37,
		maxLevel: 37,
		size: .82,
		job: JOB.TEMPLAR,
		tier: MOB_TIERS.unique,
		traits: { lightningEnchanted: true },
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'Occultist Swigzolt',
		minLevel: 39,
		maxLevel: 39,
		size: .85,
		job: JOB.WIZARD,
		tier: MOB_TIERS.unique,
		traits: { fireEnchanted: true },
	},
	{
		img: MOB_IMAGES.goblin,
		name: 'Mercenary Wrank',
		minLevel: 41,
		maxLevel: 41,
		size: .88,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { spiritDrain: true },
	},
	{
		img: MOB_IMAGES.kobold,
		name: 'Executor Meenralm',
		minLevel: 43,
		maxLevel: 43,
		size: .85,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		traits: { bloodlusted: true },
	},
	{
		img: MOB_IMAGES.kobold,
		name: 'Solicitor Zaimzun',
		minLevel: 46,
		maxLevel: 46,
		size: .88,
		job: JOB.ENCHANTER,
		tier: MOB_TIERS.unique,
		traits: { soulDrain: true },
	},
	{
		img: MOB_IMAGES.imp,
		name: 'Grave Lord Varzog',
		minLevel: 47,
		maxLevel: 47,
		size: .94,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		traits: { frenzy: true },
	},
	{
		img: MOB_IMAGES.cerberus,
		name: 'Hell Hound Jorgroud',
		minLevel: 49,
		maxLevel: 49,
		size: .9,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		traits: { fireEnchanted: true },
	},
	{
		img: MOB_IMAGES.balrog,
		name: 'Death Prince Jalgraxon',
		minLevel: 50,
		maxLevel: 50,
		size: .94,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		traits: { brute: true },
	},
	{
		img: MOB_IMAGES.balrog,
		name: 'General Xith\'tareth',
		minLevel: 51,
		maxLevel: 51,
		size: .98,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		traits: { bloodlusted: true },
	},
	{
		img: MOB_IMAGES.fireGiant,
		name: 'Minister Sulthos',
		minLevel: 51,
		maxLevel: 51,
		size: .96,
		job: JOB.CLERIC,
		tier: MOB_TIERS.unique,
		traits: { soulDrain: true },
	},
	{
		img: MOB_IMAGES.fireGiant,
		name: 'Arbiter Titor',
		minLevel: 53,
		maxLevel: 53,
		size: .99,
		job: JOB.ENCHANTER,
		tier: MOB_TIERS.unique,
		traits: { magister: true },
	},
	// quest mobs
	{
		img: MOB_IMAGES.kobold,
		name: 'Sergeant Slegs',
		minLevel: 37,
		maxLevel: 37,
		size: .87,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { bloodlusted: true },
	},
	{
		img: MOB_IMAGES.kobold,
		name: 'Alchemist Forzogz',
		minLevel: 39,
		maxLevel: 39,
		size: .86,
		job: JOB.SHAMAN,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { soulDrain: true },
	},
	{
		img: MOB_IMAGES.kobold,
		name: 'Captain Blemrots',
		minLevel: 41,
		maxLevel: 41,
		size: .9,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { brute: true },
	},
	{
		img: MOB_IMAGES.kobold,
		name: 'General Gerx',
		minLevel: 43,
		maxLevel: 43,
		size: .97,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { tough: true },
	},
	{
		img: MOB_IMAGES.kobold,
		name: 'Dark Templar Zur Emberflare',
		minLevel: 45,
		maxLevel: 45,
		size: .9,
		job: JOB.TEMPLAR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { lightningEnchanted: true },
	},
	{
		img: MOB_IMAGES.imp,
		name: 'King Grolgak Rockflare',
		minLevel: 47,
		maxLevel: 47,
		size: 1,
		job: JOB.SHAMAN,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { poisonEnchanted: true },
	},
	{
		img: MOB_IMAGES.fireGiant,
		name: 'Arch Mage Kreuzius',
		minLevel: 49,
		maxLevel: 49,
		size: .94,
		job: JOB.WIZARD,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { magister: true },
	},
	{
		img: MOB_IMAGES.fireGiant,
		name: 'Ashenflow King Chigowitz',
		minLevel: 51,
		maxLevel: 51,
		size: 1,
		job: JOB.SHADOW_KNIGHT,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { bloodlusted: true },
	},
	{
		img: MOB_IMAGES.dragonFire,
		name: 'Lord Szarthax',
		minLevel: 55,
		maxLevel: 55,
		size: 1,
		job: JOB.WARRIOR,
		tier: MOB_TIERS.unique,
		questOnly: true,
		traits: { fireEnchanted: true },
	},
]