// mob type specific stats
mob.type = {
	[MOB_IMAGES.balrog]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.DEMON,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'balrog-attack',
		sfxHit: 'balrog-hit',
		sfxDeath: 'balrog-death',
		sfxIdle: 'balrog-idle',
		sfxSpecial: 'balrog-special',
	},
	[MOB_IMAGES.iceGolem]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.MYSTICAL,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'golem-attack',
		sfxHit: 'golem-hit',
		sfxDeath: 'golem-death',
		sfxIdle: 'golem-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.stoneGolem]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.MYSTICAL,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'golem-attack',
		sfxHit: 'golem-hit',
		sfxDeath: 'golem-death',
		sfxIdle: 'golem-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.ironGolem]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.MYSTICAL,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'golem-attack',
		sfxHit: 'golem-hit',
		sfxDeath: 'golem-death',
		sfxIdle: 'golem-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.treant]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.MYSTICAL,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'treant-attack',
		sfxHit: 'treant-hit',
		sfxDeath: 'treant-death',
		sfxIdle: 'treant-idle',
		sfxSpecial: 'treant-special',
	},
	[MOB_IMAGES.spider]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.BEAST,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'spider-attack',
		sfxHit: 'spider-hit',
		sfxDeath: 'spider-death',
		sfxIdle: 'spider-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.wolf]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.BEAST,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'wolf-attack',
		sfxHit: 'wolf-hit',
		sfxDeath: 'wolf-death',
		sfxIdle: 'wolf-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.wolfArctic]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.BEAST,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'wolf-attack',
		sfxHit: 'wolf-hit',
		sfxDeath: 'wolf-death',
		sfxIdle: 'wolf-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.rat]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.BEAST,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'rat-attack',
		sfxHit: 'rat-hit',
		sfxDeath: 'rat-death',
		sfxIdle: 'rat-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.snake]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.BEAST,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'snake-attack',
		sfxHit: 'snake-hit',
		sfxDeath: 'snake-death',
		sfxIdle: 'snake-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.dragonkin]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.DRAGONKIN,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'centaur-attack',
		sfxHit: 'centaur-hit',
		sfxDeath: 'centaur-death',
		sfxIdle: undefined,
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.lizardman]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.HUMANOID,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'lizardman-attack',
		sfxHit: 'lizardman-hit',
		sfxDeath: 'lizardman-death',
		sfxIdle: 'lizardman-idle',
		sfxSpecial: 'lizardman-special',
	},
	[MOB_IMAGES.dragon]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.DRAGONKIN,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'dragon-attack',
		sfxHit: 'dragon-hit',
		sfxDeath: 'dragon-death',
		sfxIdle: 'dragon-idle',
		sfxSpecial: 'dragon-special',
	},
	[MOB_IMAGES.dragonFire]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.DRAGONKIN,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'dragon-attack',
		sfxHit: 'dragon-hit',
		sfxDeath: 'dragon-death',
		sfxIdle: 'dragon-idle',
		sfxSpecial: 'dragon-special',
	},
	[MOB_IMAGES.dragonPoison]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.DRAGONKIN,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'dragon-attack',
		sfxHit: 'dragon-hit',
		sfxDeath: 'dragon-death',
		sfxIdle: 'dragon-idle',
		sfxSpecial: 'dragon-special',
	},
	[MOB_IMAGES.dragonFrost]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.DRAGONKIN,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'dragon-attack',
		sfxHit: 'dragon-hit',
		sfxDeath: 'dragon-death',
		sfxIdle: 'dragon-idle',
		sfxSpecial: 'dragon-special',
	},
	[MOB_IMAGES.dragonPlains]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.DRAGONKIN,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'dragon-attack',
		sfxHit: 'dragon-hit',
		sfxDeath: 'dragon-death',
		sfxIdle: 'dragon-idle',
		sfxSpecial: 'dragon-special',
	},
	[MOB_IMAGES.dragonWater]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.DRAGONKIN,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'dragon-attack',
		sfxHit: 'dragon-hit',
		sfxDeath: 'dragon-death',
		sfxIdle: 'dragon-idle',
		sfxSpecial: 'dragon-special',
	},
	[MOB_IMAGES.dragonForest]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.DRAGONKIN,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'dragon-attack',
		sfxHit: 'dragon-hit',
		sfxDeath: 'dragon-death',
		sfxIdle: 'dragon-idle',
		sfxSpecial: 'dragon-special',
	},
	[MOB_IMAGES.dragonDesert]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.DRAGONKIN,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'dragon-attack',
		sfxHit: 'dragon-hit',
		sfxDeath: 'dragon-death',
		sfxIdle: 'dragon-idle',
		sfxSpecial: 'dragon-special',
	},
	[MOB_IMAGES.ghoul]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.UNDEAD,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'ghoul-attack',
		sfxHit: 'ghoul-hit',
		sfxDeath: 'ghoul-death',
		sfxIdle: undefined,
		sfxSpecial: 'ghoul-special',
	},
	[MOB_IMAGES.mummy]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.UNDEAD,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'zombie-attack',
		sfxHit: 'zombie-hit',
		sfxDeath: 'zombie-death',
		sfxIdle: 'zombie-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.skeleton]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.UNDEAD,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'skeleton-attack',
		sfxHit: 'skeleton-hit',
		sfxDeath: 'skeleton-death',
		sfxIdle: undefined,
		sfxSpecial: 'skeleton-special',
	},
	[MOB_IMAGES.zombie]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.UNDEAD,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'zombie-attack',
		sfxHit: 'zombie-hit',
		sfxDeath: 'zombie-death',
		sfxIdle: 'zombie-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.vampire]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.UNDEAD,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'vampire-attack',
		sfxHit: 'vampire-hit',
		sfxDeath: 'vampire-death',
		sfxIdle: 'vampire-attack',
		sfxSpecial: 'vampire-special',
	},
	[MOB_IMAGES.goblin]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.HUMANOID,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'goblin-attack',
		sfxHit: 'goblin-hit',
		sfxDeath: 'goblin-death',
		sfxIdle: 'goblin-attack',
		sfxSpecial: 'goblin-special',
	},
	[MOB_IMAGES.goblinFire]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.HUMANOID,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'goblin-attack',
		sfxHit: 'goblin-hit',
		sfxDeath: 'goblin-death',
		sfxIdle: 'goblin-attack',
		sfxSpecial: 'goblin-special',
	},
	[MOB_IMAGES.goblinIce]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.HUMANOID,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'goblin-attack',
		sfxHit: 'goblin-hit',
		sfxDeath: 'goblin-death',
		sfxIdle: 'goblin-attack',
		sfxSpecial: 'goblin-special',
	},
	[MOB_IMAGES.hobgoblin]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.HUMANOID,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'rhino-attack',
		sfxHit: 'rhino-hit',
		sfxDeath: 'rhino-death',
		sfxIdle: 'rhino-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.kobold]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.HUMANOID,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'werewolf-attack',
		sfxHit: 'werewolf-hit',
		sfxDeath: 'werewolf-death',
		sfxIdle: 'werewolf-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.orc]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.HUMANOID,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'orc-attack',
		sfxHit: 'orc-hit',
		sfxDeath: 'orc-death',
		sfxIdle: 'orc-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.griffon]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.MYSTICAL,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'griffon-attack',
		sfxHit: 'griffon-hit',
		sfxDeath: 'griffon-death',
		sfxIdle: 'griffon-idle',
		sfxSpecial: 'griffon-special',
	},
	[MOB_IMAGES.harpy]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.MYSTICAL,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'harpy-attack',
		sfxHit: 'harpy-hit',
		sfxDeath: 'harpy-death',
		sfxIdle: undefined,
		sfxSpecial: 'harpy-special',
	},
	[MOB_IMAGES.werewolf]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.MYSTICAL,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'werewolf-attack',
		sfxHit: 'werewolf-hit',
		sfxDeath: 'werewolf-death',
		sfxIdle: 'werewolf-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.centaur]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.MYSTICAL,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'centaur-attack',
		sfxHit: 'centaur-hit',
		sfxDeath: 'centaur-death',
		sfxIdle: undefined,
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.cerberus]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.MYSTICAL,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'cerberus-attack',
		sfxHit: 'cerberus-hit',
		sfxDeath: 'cerberus-death',
		sfxIdle: 'cerberus-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.fungoid]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.HUMANOID,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'fungoid-attack',
		sfxHit: 'fungoid-hit',
		sfxDeath: 'fungoid-death',
		sfxIdle: 'fungoid-idle',
		sfxSpecial: 'fungoid-special',
	},
	[MOB_IMAGES.gargoyle]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.MYSTICAL,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'gargoyle-attack',
		sfxHit: 'gargoyle-hit',
		sfxDeath: 'gargoyle-death',
		sfxIdle: 'gargoyle-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.beetle]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.BEAST,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'beetle-attack',
		sfxHit: 'beetle-hit',
		sfxDeath: 'beetle-death',
		sfxIdle: undefined,
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.imp]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.DEMON,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'imp-attack',
		sfxHit: 'imp-hit',
		sfxDeath: 'imp-death',
		sfxIdle: 'imp-idle',
		sfxSpecial: 'imp-attack',
	},
	[MOB_IMAGES.minotaur]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.MYSTICAL,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'minotaur-attack',
		sfxHit: 'minotaur-hit',
		sfxDeath: 'minotaur-death',
		sfxIdle: 'minotaur-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.aviak]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.HUMANOID,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'aviak-attack',
		sfxHit: 'aviak-hit',
		sfxDeath: 'aviak-hit',
		sfxIdle: undefined,
		sfxSpecial: 'aviak-special',
	},
	[MOB_IMAGES.elephant]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.BEAST,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'elephant-attack',
		sfxHit: 'elephant-hit',
		sfxDeath: 'elephant-death',
		sfxIdle: 'elephant-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.lion]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.BEAST,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'lion-attack',
		sfxHit: 'lion-hit',
		sfxDeath: 'lion-death',
		sfxIdle: 'lion-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.crocodile]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.BEAST,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'crocodile-attack',
		sfxHit: 'crocodile-hit',
		sfxDeath: 'crocodile-death',
		sfxIdle: undefined,
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.rhino]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.BEAST,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'rhino-attack',
		sfxHit: 'rhino-hit',
		sfxDeath: 'rhino-death',
		sfxIdle: undefined,
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.lioness]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.BEAST,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'lion-attack',
		sfxHit: 'lion-hit',
		sfxDeath: 'lion-death',
		sfxIdle: 'lion-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.bear]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.BEAST,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'bear-attack',
		sfxHit: 'bear-hit',
		sfxDeath: 'bear-death',
		sfxIdle: 'bear-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.bearPolar]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.BEAST,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'bear-attack',
		sfxHit: 'bear-hit',
		sfxDeath: 'bear-death',
		sfxIdle: 'bear-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.toadlok]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.HUMANOID,
		resist: {
			blood: 1,
			poison: .7,
			arcane: 1,
			lightning: 1,
			fire: .7,
			ice: 1,
		},
		sfxAttack: 'toadlok-attack',
		sfxHit: 'toadlok-hit',
		sfxDeath: 'toadlok-death',
		sfxIdle: 'toadlok-idle',
		sfxSpecial: 'toadlok-special',
	},
	[MOB_IMAGES.giant]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.GIANT,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'giant-attack',
		sfxHit: 'giant-hit',
		sfxDeath: 'giant-death',
		sfxIdle: 'giant-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.iceGiant]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.GIANT,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'giant-attack',
		sfxHit: 'giant-hit',
		sfxDeath: 'giant-death',
		sfxIdle: 'giant-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.fireGiant]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.GIANT,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'giant-attack',
		sfxHit: 'giant-hit',
		sfxDeath: 'giant-death',
		sfxIdle: 'giant-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.spectre]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.UNDEAD,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'spectre-attack',
		sfxHit: 'spectre-hit',
		sfxDeath: 'spectre-death',
		sfxIdle: 'spectre-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.angler]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.HUMANOID,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'angler-attack',
		sfxHit: 'angler-hit',
		sfxDeath: 'angler-death',
		sfxIdle: 'angler-attack',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.evilEye]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.MYSTICAL,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'evil-eye-attack',
		sfxHit: 'evil-eye-hit',
		sfxDeath: 'evil-eye-death',
		sfxIdle: 'evil-eye-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.unicorn]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.MYSTICAL,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'unicorn-attack',
		sfxHit: 'unicorn-hit',
		sfxDeath: 'unicorn-death',
		sfxIdle: 'unicorn-idle',
		sfxSpecial: undefined,
	},
	[MOB_IMAGES.scorpion]: {
		hp: 1,
		armor: .8,
		mobType: MOB_TYPES.BEAST,
		resist: {
			blood: 1,
			poison: 1,
			arcane: 1,
			lightning: 1,
			fire: 1,
			ice: 1,
		},
		sfxAttack: 'beetle-attack',
		sfxHit: 'beetle-hit',
		sfxDeath: 'beetle-death',
		sfxIdle: undefined,
		sfxSpecial: undefined,
	},
	/*'cyclops': {
	},*/
}