var quests;
!function($, _, TweenMax, undefined) {
	/**
	 * Types of missions:
	 * cleanse - Win 100% of battles
	 * target - Checks type of mob killed (orc, toadlok, etc)
	 * kill (the BOSS) - checks mob name (typically a boss or champion type)
	 * explore - check room id after cleared and check how many unique rooms have been cleared
	 * gather - retrieve # lost relics
	 * investigate - record ancient writings,
	 */
	quests = [{
			level: 1,
			title: 'Kill Himber',
			bossName: 'Himber',
			description: '',
			imgIndex: 1,
			maxLevel: 2,
			type: QUEST_TYPES.kill,
			size: MAP_SIZES.large,
			zone: ZONES.salubrinHaven,
		},
		{
			level: 2,
			title: 'Kill Fahesh',
			bossName: 'Fahesh',
			description: '',
			imgIndex: 2,
			maxLevel: 2,
			type: QUEST_TYPES.kill,
			size: MAP_SIZES.small,
			zone: ZONES.salubrinHaven,
		},
		{
			level: 3,
			title: 'Kill Umusaq',
			bossName: 'Umusaq',
			description: '',
			imgIndex: 1,
			maxLevel: 2,
			type: QUEST_TYPES.kill,
			size: MAP_SIZES.small,
			zone: ZONES.salubrinHaven,
		},
		{
			level: 5,
			title: 'Kill Aslan',
			bossName: 'Aslan',
			description: '',
			imgIndex: 2,
			maxLevel: 2,
			type: QUEST_TYPES.kill,
			size: MAP_SIZES.small,
			zone: ZONES.salubrinHaven,
		},
		{
			level: 7,
			title: 'Kill Gaurav',
			bossName: 'Gaurav',
			description: '',
			imgIndex: 1,
			maxLevel: 2,
			type: QUEST_TYPES.kill,
			size: MAP_SIZES.small,
			zone: ZONES.salubrinHaven,
		},{ // placeholders
			level: 1,
			title: 'Kill Himber',
			bossName: 'Himber',
			description: '',
			imgIndex: 1,
			maxLevel: 2,
			type: QUEST_TYPES.kill,
			size: MAP_SIZES.large,
			zone: ZONES.tendolinPassage,
		},{
			level: 1,
			title: 'Kill Himber',
			bossName: 'Himber',
			description: '',
			imgIndex: 1,
			maxLevel: 2,
			type: QUEST_TYPES.kill,
			size: MAP_SIZES.large,
			zone: ZONES.greenthornCavern,
		},{
			level: 1,
			title: 'Kill Himber',
			bossName: 'Himber',
			description: '',
			imgIndex: 1,
			maxLevel: 2,
			type: QUEST_TYPES.kill,
			size: MAP_SIZES.large,
			zone: ZONES.lanfeldRefuge,
		},{
			level: 1,
			title: 'Kill Himber',
			bossName: 'Himber',
			description: '',
			imgIndex: 1,
			maxLevel: 2,
			type: QUEST_TYPES.kill,
			size: MAP_SIZES.large,
			zone: ZONES.rivenGrotto,
		},{
			level: 1,
			title: 'Kill Himber',
			bossName: 'Himber',
			description: '',
			imgIndex: 1,
			maxLevel: 2,
			type: QUEST_TYPES.kill,
			size: MAP_SIZES.large,
			zone: ZONES.bastilleCitadel,
		},{
			level: 1,
			title: 'Kill Himber',
			bossName: 'Himber',
			description: '',
			imgIndex: 1,
			maxLevel: 2,
			type: QUEST_TYPES.kill,
			size: MAP_SIZES.large,
			zone: ZONES.kordataCove,
		},{
			level: 1,
			title: 'Kill Himber',
			bossName: 'Himber',
			description: '',
			imgIndex: 1,
			maxLevel: 2,
			type: QUEST_TYPES.kill,
			size: MAP_SIZES.large,
			zone: ZONES.sylongSanctuary,
		},{
			level: 1,
			title: 'Kill Himber',
			bossName: 'Himber',
			description: '',
			imgIndex: 1,
			maxLevel: 2,
			type: QUEST_TYPES.kill,
			size: MAP_SIZES.large,
			zone: ZONES.thuleCrypt,
		},{
			level: 1,
			title: 'Kill Himber',
			bossName: 'Himber',
			description: '',
			imgIndex: 1,
			maxLevel: 2,
			type: QUEST_TYPES.kill,
			size: MAP_SIZES.large,
			zone: ZONES.templeOfPrenssor,
		},{
			level: 1,
			title: 'Kill Himber',
			bossName: 'Himber',
			description: '',
			imgIndex: 1,
			maxLevel: 2,
			type: QUEST_TYPES.kill,
			size: MAP_SIZES.large,
			zone: ZONES.fahlnirCitadel,
		},{
			level: 1,
			title: 'Kill Himber',
			bossName: 'Himber',
			description: '',
			imgIndex: 1,
			maxLevel: 2,
			type: QUEST_TYPES.kill,
			size: MAP_SIZES.large,
			zone: ZONES.anuranRuins,
		},{
			level: 1,
			title: 'Kill Himber',
			bossName: 'Himber',
			description: '',
			imgIndex: 1,
			maxLevel: 2,
			type: QUEST_TYPES.kill,
			size: MAP_SIZES.large,
			zone: ZONES.galeblastFortress,
		},{
			level: 1,
			title: 'Kill Himber',
			bossName: 'Himber',
			description: '',
			imgIndex: 1,
			maxLevel: 2,
			type: QUEST_TYPES.kill,
			size: MAP_SIZES.large,
			zone: ZONES.ashenflowPeak,
		},
	]
	///////////////////////////////////////////

}($, _, TweenMax);