loot.amulets = {
	base: {
		slots: ['neck']
	},
	normal: [
		{
			name: 'Amulet',
			itemLevel: 1,
		}
	],
	prefix: {
		resists: 40,
		resistAll: 15,
		spellPower: 40,
	},
	suffix: {
		stats: 30,
		allStats: 15,
		points: 30,
		crit: 20,
		regen: 5,
		leech: 8,
		wraith: 8,
	},
	rare: {
		skills: 3,
		allSkills: 2,
		addDamage: 10,
	},
	unique: [
		{
			name: 'Amulet',
			newName: 'Kordata Relic',
			resistFire: [15, 20].map(util.divideBy4),
			addSpellFire: [8, 12],
			addSpellArcane: [3, 5],
			sp: [20, 25],
			spRegen: [3, 4],
			enhancedDamageToMystical: [7, 11],
			dex: [8, 12],
			cha: 10,
			itemLevel: 4,
		}, {
			name: 'Amulet',
			newName: 'The Eye of Riltan',
			allSkills: 1,
			hpKill: [7, 9],
			addSpellIce: [4, 7],
			phyMit: 3,
			sp: [15, 20],
			mp: [21, 25],
			dodge: 3,
			itemLevel: 6,
		}, {
			name: 'Amulet',
			newName: 'The Arboretum Curio',
			armor: [10, 15],
			attack: 7,
			resistAll: [5, 8],
			allStats: [4, 6],
			damageTakenToSpirit: [3, 5],
			enhanceIce: 2,
			enhanceFire: 2,
			itemLevel: 8,
		}, {
			name: 'Amulet',
			newName: 'Etched Granite Charm',
			str: 5,
			sta: 5,
			dex: 5,
			wis: 5,
			intel: 5,
			dodge: 2,
			resistFear: [4, 6],
			mpRegen: [2, 4],
			itemLevel: 10,
		}, {
			name: 'Amulet',
			newName: 'Saracen\'s Guard',
			resistAll: [8, 11],
			allStats: 7,
			enhanceFire: [2, 3],
			magMit: [2, 4],
			conjuration: 2,
			mp: 13,
			sp: [10, 20],
			itemLevel: 12,
		}, {
			name: 'Amulet',
			newName: 'The Prowler\'s Eye',
			archery: 4,
			piercing: [4, 6],
			armor: 25,
			addSpellBlood: [5, 9],
			dex: [18, 24],
			agi: [27, 34],
			//restInPeace: true,
			leech: [4, 7],
			itemLevel: 13,
		}, {
			name: 'Amulet',
			newName: 'Enchanted Bone Collar',
			hp: 30,
			mp: [20, 25],
			armor: 8,
			twoHandBlunt: 3,
			sp: [15, 20],
			mpRegen: [3, 5],
			resistPoison: [27, 36].map(util.divideBy4),
			itemLevel: 15,
		}, {
			name: 'Amulet',
			newName: 'Anuran Talisman',
			intel: 15,
			wis: [12, 20],
			dex: [18, 24],
			mp: 35,
			mpKill: 4,
			crit: 10,
			resistPoison: 5,
			resistFire: 5,
			itemLevel: 18,
		}, {
			name: 'Amulet',
			newName: 'The Rising Sun',
			enhanceFire: [3, 5],
			hpRegen: 5,
			addSpellFire: [7, 12],
			resistFire: 13,
			sp: [25, 35],
			evocation: 2,
			cha: 25,
			intel: 15,
			itemLevel: 21,
		}, {
			name: 'Amulet',
			newName: 'Disciple\'s Symbol of Rinara',
			wis: 35,
			hpRegen: [4, 6],
			resistLightning: 13,
			enhanceLightning: [4, 6],
			sp: [22, 26],
			conjuration: [2, 3],
			dodge: 3,
			itemLevel: 25,
		}, {
			name: 'Amulet',
			newName: 'Entariz\'s Talisman',
			resistArcane: 9,
			resistBlood: 5,
			crit: 13,
			intel: [30, 35],
			addSpellArcane: [26, 32],
			addSpellPoison: [31, 35],
			addSpellIce: [21, 25],
			itemLevel: 28,
		}, {
			name: 'Amulet',
			newName: 'Necklace of Whispering Winds',
			addSpellLightning: [6, 8],
			alteration: [3, 4],
			conjuration: [2, 3],
			mpKill: 5,
			cha: [24, 32],
			agi: [20, 30],
			resistLightning: [30, 40].map(util.divideBy4),
			resistIce: [20, 30].map(util.divideBy4),
			resistArcane: [20, 30].map(util.divideBy4),
			itemLevel: 32,
		},
	]
}