loot.boots = {
	base: {
		slots: ['feet'],
		armorType: 'cloth',
	},
	normal: [
		{
			name: 'Boots',
			minArmor: 1,
			maxArmor: 4,
			itemLevel: 1,
			armorType: 'cloth',
			imgIndex: 0,
		}, {
			name: 'Slippers',
			minArmor: 4,
			maxArmor: 7,
			itemLevel: 6,
			armorType: 'cloth',
			imgIndex: 1,
		}, {
			name: 'Light Boots',
			minArmor: 6,
			maxArmor: 8,
			itemLevel: 14,
			armorType: 'cloth',
			imgIndex: 2,
		}, {
			name: 'Khussa',
			minArmor: 9,
			maxArmor: 12,
			itemLevel: 20,
			armorType: 'cloth',
			imgIndex: 3,
		}, {
			name: 'Heavy Boots',
			minArmor: 7,
			maxArmor: 10,
			itemLevel: 5,
			armorType: 'leather',
			imgIndex: 4,
		}, {
			name: 'Leather Boots',
			minArmor: 13,
			maxArmor: 17,
			itemLevel: 12,
			armorType: 'leather',
			imgIndex: 5,
		}, {
			name: 'Sharkskin Boots',
			minArmor: 18,
			maxArmor: 21,
			itemLevel: 20,
			armorType: 'leather',
			imgIndex: 6,
		}, {
			name: 'Hunting Boots',
			minArmor: 22,
			maxArmor: 25,
			itemLevel: 24,
			armorType: 'leather',
			imgIndex: 7,
		}, {
			name: 'Chain Boots',
			minArmor: 19,
			maxArmor: 22,
			itemLevel: 6,
			armorType: 'mail',
			imgIndex: 8,
		}, {
			name: 'Scaled Boots',
			minArmor: 23,
			maxArmor: 26,
			itemLevel: 15,
			armorType: 'mail',
			imgIndex: 9,
		}, {
			name: 'Sovereign Boots',
			minArmor: 27,
			maxArmor: 32,
			itemLevel: 24,
			armorType: 'mail',
			imgIndex: 10,
		}, {
			name: 'Blackened Boots',
			minArmor: 33,
			maxArmor: 37,
			itemLevel: 28,
			armorType: 'mail',
			imgIndex: 11,
		}, {
			name: 'Steel Boots',
			minArmor: 25,
			maxArmor: 29,
			itemLevel: 6,
			armorType: 'plate',
			imgIndex: 12,
		}, {
			name: 'Plated Boots',
			minArmor: 32,
			maxArmor: 36,
			itemLevel: 16,
			armorType: 'plate',
			imgIndex: 13,
		}, {
			name: 'Sabatons',
			minArmor: 39,
			maxArmor: 44,
			itemLevel: 24,
			armorType: 'plate',
			imgIndex: 14,
		}, {
			name: 'Cobalt Boots',
			minArmor: 47,
			maxArmor: 50,
			itemLevel: 33,
			armorType: 'plate',
			imgIndex: 15,
		},
	],
	prefix: {
		resists: 40,
		enhancedArmor: 100
	},
	suffix: {
		stats: 30,
		points: 30,
		ease: 2,
	},
	rare: {
		skills: 2,
	},
	unique: [
		{
			name: 'Boots',
			newName: 'Lavaspur',
			enhancedArmor: [12, 20],
			dex: 9,
			evocation: 1,
			intel: 9,
			defense: 2,
			resistFire: [15, 20],
			addSpellFire: [6, 11],
		}, {
			name: 'Slippers',
			newName: 'Hoarfrost Boots',
			enhancedArmor: [27, 35],
			evocation: 2,
			allStats: [4, 8],
			crit: 3,
			addSpellIce: [5, 8],
			resistIce: 32,
		}, {
			name: 'Light Boots',
			newName: 'Golden Baelor Boots',
			enhancedArmor: [46, 58],
			hp: [15, 20],
			wis: 15,
			intel: 15,
			allSkills: 1,
			addSpellFire: [8, 12],
			resistFire: 24,
		}, {
			name: 'Khussa',
			newName: 'Amice-Lined Shoes',
			enhancedArmor: [70, 80],
			hp: 15,
			allStats: [4, 6],
			dodge: 2,
			evocation: [2, 3],
			alteration: [1, 2],
			resistPoison: [13, 16],
			resistIce: [16, 20],
		}, {
			name: 'Heavy Boots',
			newName: 'Vagabond\'s Voyage',
			enhancedArmor: [15, 21],
			allStats: [4, 6],
			sp: 15,
			resistAll: [5, 8],
			addSpellLightning: [4, 6],
			spRegen: 2,
		}, {
			name: 'Leather Boots',
			newName: 'Boots of the Destroyer',
			enhancedArmor: [29, 40],
			str: 10,
			sta: 15,
			crit: 10,
			twoHandSlash: [2, 3],
			twoHandBlunt: [2, 3],
			hp: [18, 24],
			attack: [5, 8],
		}, {
			name: 'Sharkskin Boots',
			newName: 'Craftsman\'s Boots',
			enhancedArmor: [53, 67],
			agi: 15,
			wis: 10,
			offense: [1, 2],
			addSpellBlood: [4, 6],
			resistFire: [15, 25],
			resistIce: [15, 25],
			resistPoison: [20, 30],
		}, {
			name: 'Hunting Boots',
			newName: 'Gorilla-Hide Boots',
			enhancedArmor: [73, 84],
			str: 25,
			agi: [10, 15],
			sta: [10, 15],
			parry: 2,
			attack: [7, 10],
			resistBlood: 15,
			resistIce: 10,
		}, {
			name: 'Chain Boots',
			newName: 'Treads of Vergundi',
			enhancedArmor: [15, 24],
			hp: 30,
			sp: 15,
			hpKill: 4,
			resistPoison: 40,
			resistFire: 12,
			allStats: [3, 5],
		}, {
			name: 'Scaled Boots',
			newName: 'Emissary\'s Finesse',
			enhancedArmor: [35, 49],
			conjuration: [2, 3],
			offense: [2, 3],
			cha: [21, 30],
			resistAll: [6, 10],
			sp: [12, 18],
			spRegen: 2,
		}, {
			name: 'Sovereign Boots',
			newName: 'Dwarven Militia Boots',
			enhancedArmor: [64, 74],
			hp: 25,
			str: [10, 15],
			dex: [15, 20],
			resistBlood: [20, 30],
			resistIce: [20, 30],
			resistLightning: [20, 30],
		}, {
			name: 'Blackened Boots',
			newName: 'Charred Boots',
			enhancedArmor: [83, 92],
			evocation: 3,
			spKill: 7,
			addSpellFire: [8, 15],
			agi: [15, 20],
			resistFire: 50,
			resistPoison: [20, 40],
		}, {
			name: 'Steel Boots',
			newName: 'Goblin Captain\'s Boots',
			enhancedArmor: [21, 25],
			hp: 15,
			mp: 15,
			sp: 10,
			magMit: 2,
			phyMit: 2,
			crit: 7,
		}, {
			name: 'Plated Boots',
			newName: 'Greenmist Boots',
			enhancedArmor: [43, 52],
			hp: 20,
			mp: 20,
			str: [10, 15],
			sta: 10,
			intel: [10, 15],
			agi: 10,
			resistPoison: [25, 35],
			prop: 12341234,
		}, {
			name: 'Sabatons',
			newName: 'Minotaur\'s Hooves',
			enhancedArmor: [68, 77],
			resistFire: 15,
			resistBlood: [20, 25],
			resistArcane: 15,
			agi: 12,
			hp: [15, 20],
			dodge: 3,
		}, {
			name: 'Cobalt Boots',
			newName: 'Boots of the Righteous',
			enhancedArmor: [93, 107],
			str: [19, 28],
			wis: [14, 20],
			alteration: [3, 5],
			conjuration: [2, 3],
			enhanceArcane: [2, 3],
			resistPoison: [24, 33],
			resistArcane: [30, 40],
		},
	]
}