loot.bracers = {
	base: {
		slots: ['wrist'],
		armorType: 'cloth',
	},
	normal: [
		{
			name: 'Wraps',
			minArmor: 1,
			maxArmor: 2,
			itemLevel: 1,
			armorType: 'cloth',
			imgIndex: 0,
		}, {
			name: 'Cuffs',
			minArmor: 3,
			maxArmor: 5,
			itemLevel: 5,
			armorType: 'cloth',
			imgIndex: 1,
		}, {
			name: 'Bindings',
			minArmor: 4,
			maxArmor: 6,
			itemLevel: 12,
			armorType: 'cloth',
			imgIndex: 2,
		}, {
			name: 'Wristguards',
			minArmor: 6,
			maxArmor: 8,
			itemLevel: 20,
			armorType: 'cloth',
			imgIndex: 3,
		}, {
			name: 'Leather Bracers',
			minArmor: 4,
			maxArmor: 6,
			itemLevel: 5,
			armorType: 'leather',
			imgIndex: 4,
		}, {
			name: 'Patent Bracers',
			minArmor: 6,
			maxArmor: 9,
			itemLevel: 10,
			armorType: 'leather',
			imgIndex: 5,
		}, {
			name: 'Bonded Bracers',
			minArmor: 9,
			maxArmor: 12,
			itemLevel: 15,
			armorType: 'leather',
			imgIndex: 6,
		}, {
			name: 'Studded Bracers',
			minArmor: 13,
			maxArmor: 16,
			itemLevel: 22,
			armorType: 'leather',
			imgIndex: 7,
		}, {
			name: 'Scaled Bracers',
			minArmor: 5,
			maxArmor: 8,
			itemLevel: 6,
			armorType: 'mail',
			imgIndex: 8,
		}, {
			name: 'Laminar Bracers',
			minArmor: 10,
			maxArmor: 14,
			itemLevel: 14,
			armorType: 'mail',
			imgIndex: 9,
		}, {
			name: 'Splinted Bracers',
			minArmor: 14,
			maxArmor: 18,
			itemLevel: 22,
			armorType: 'mail',
			imgIndex: 10,
		}, {
			name: 'Kusari Bracers',
			minArmor: 19,
			maxArmor: 23,
			itemLevel: 26,
			armorType: 'mail',
			imgIndex: 11,
		}, {
			name: 'Bronze Bracers',
			minArmor: 12,
			maxArmor: 16,
			itemLevel: 6,
			armorType: 'plate',
			imgIndex: 12,
		}, {
			name: 'Cobalt Bracers',
			minArmor: 17,
			maxArmor: 22,
			itemLevel: 12,
			armorType: 'plate',
			imgIndex: 13,
		}, {
			name: 'Tetrarch Bracers',
			minArmor: 23,
			maxArmor: 27,
			itemLevel: 22,
			armorType: 'plate',
			imgIndex: 14,
		}, {
			name: 'Gilded Bracers',
			minArmor: 27,
			maxArmor: 30,
			itemLevel: 32,
			armorType: 'plate',
			imgIndex: 15,
		},
	],
	prefix: {
		resists: 20,
		enhancedArmor: 100
	},
	suffix: {
		stats: 20,
		points: 20,
		ease: 2,
	},
	rare: {
		skills: 2,
	},
	unique: [
		{
			name: 'Wraps',
			newName: 'Gilded Jade Bracelet',
			enhancedArmor: [10, 15],
			hp: 15,
			wis: [5, 8],
			evocation: [1, 2],
			conjuration: [1, 2],
			resistPoison: 3,
		}, {
			name: 'Cuffs',
			newName: 'Burnished Bone Bracelet',
			enhancedArmor: [24, 35],
			mp: 12,
			sp: [6, 10],
			wis: [10, 15],
			intel: [10, 15],
			resistArcane: [7, 10].map(util.divideBy4),
			crit: 3,
		}, {
			name: 'Bindings',
			newName: 'Bracelet of Woven Silk',
			enhancedArmor: [40, 45],
			hp: 15,
			wis: 5,
			intel: 10,
			resistLightning: [10, 15].map(util.divideBy4),
			resistArcane: [10, 15].map(util.divideBy4),
			cha: [12, 16],
		}, {
			name: 'Wristguards',
			newName: 'Orator\'s Entreat',
			enhancedArmor: [55, 64],
			resistFire: [12, 16].map(util.divideBy4),
			resistPoison: [12, 16].map(util.divideBy4),
			sta: 10,
			dex: [13, 16],
			dodge: [2, 3],
		}, {
			name: 'Leather Bracers',
			newName: 'Bracers of Battle',
			enhancedArmor: [15, 21],
			attack: [3, 8],
			str: [3, 5],
			dex: [7, 10],
			twoHandSlash: 2,
			crit: [3, 5],
		}, {
			name: 'Patent Bracers',
			newName: 'Ivory Bracelet',
			enhancedArmor: [26, 35],
			mp: [7, 12],
			sp: [11, 15],
			agi: [8, 12],
			hpRegen: 1,
			crit: 2,
			resistIce: 2,
			resistBlood: 2,
		}, {
			name: 'Bonded Bracers',
			newName: 'Granite Bracer',
			enhancedArmor: [44, 52],
			hp: 10,
			str: 7,
			sta: 12,
			resistIce: [8, 12].map(util.divideBy4),
			resistArcane: [11, 15].map(util.divideBy4),
			phyMit: [3, 5],
		}, {
			name: 'Studded Bracers',
			newName: 'Serpentine Bracer',
			enhancedArmor: [55, 63],
			agi: [13, 16],
			dex: [7, 10],
			dodge: [1, 2],
			resistPoison: [11, 15].map(util.divideBy4),
			mpRegen: [2, 3],
			wraith: 2,
		}, {
			name: 'Scaled Bracers',
			newName: 'Basilisk Bracer',
			enhancedArmor: [18, 24],
			hp: 12,
			wis: 10,
			agi: 5,
			oneHandBlunt: 2,
			conjuration: [1, 2],
			resistStun: [4, 6],
		}, {
			name: 'Laminar Bracers',
			newName: 'Runed Adamantium Bracer',
			enhancedArmor: [32, 44],
			mpKill: 4,
			wis: [12, 15],
			str: 5,
			magMit: 2,
			resistArcane: [12, 16].map(util.divideBy4),
			resistFire: [8, 12].map(util.divideBy4),
		}, {
			name: 'Splinted Bracers',
			newName: 'Martyr\'s Agony',
			enhancedArmor: [52, 64],
			dex: 10,
			wis: [12, 15],
			hp: 12,
			sp: [16, 20],
			spRegen: 2,
			resistBlood: 5,
		}, {
			name: 'Kusari Bracers',
			newName: 'Dragon Bane Bracer',
			enhancedArmor: [66, 75],
			str: [13, 17],
			agi: 9,
			evocation: [1, 2],
			piercing: 2,
			resistFire: 2,
			resistArcane: 2,
			resistIce: 2,
			leech: [2, 3],
		}, {
			name: 'Bronze Bracers',
			newName: 'Chief Grimden\'s Bracer',
			enhancedArmor: [25, 32],
			hp: [16, 20],
			sp: [16, 20],
			str: 12,
			hpKill: 3,
			twoHandBlunt: 3,
			parry: 2,
		}, {
			name: 'Cobalt Bracers',
			newName: 'Arbiter\'s Galvanized Bracer',
			enhancedArmor: [36, 52],
			mp: 10,
			alteration: [2, 3],
			defense: [2, 3],
			oneHandBlunt: [3, 4],
			resistArcane: 3,
			resistPoison: 3,
		}, {
			name: 'Tetrarch Bracers',
			newName: 'Dragon Claw Bracer',
			enhancedArmor: [64, 80],
			mp: [10, 15],
			hp: [8, 12],
			sp: [12, 16],
			crit: 3,
			resistAll: [3, 5],
			leech: [2, 3],
		}, {
			name: 'Gilded Bracers',
			newName: 'Scaled Brass Bracer',
			enhancedArmor: [88, 103],
			cha: [23, 28],
			crit: [4, 6],
			oneHandSlash: [2, 3],
			dex: [10, 15],
			resistAll: [7, 10],
		},
	]
}