items.charms = {
	base: {
		slots: ['range']
	},
	normal: [
		{
			name: 'Charm',
			itemLevel: 1,
		},
	],
	prefix: {
		resists: 40,
		resistAll: 15,
		spellPower: 30,
	},
	suffix: {
		stats: 20,
		points: 20,
		regen: 5,
	},
	rare: {
		skills: 2,
		addDamage: 20,
	},
	unique: [
		{
			name: 'Charm',
			newName: 'Shyclasp\'s Token',
			resistFear: 7,
			cha: [8, 10],
			sta: [8, 10],
			resistIce: [6, 10],
			resistLightning: [6, 10],
			resistPoison: [6, 10],
			resistFire: [6, 10],
		},
		{
			name: 'Charm',
			newName: 'Omen of Will',
			sta: [11, 15],
			hpKill: [4, 7],
			spKill: [4, 7],
			mp: [12, 16],
			resistFrozen: [7, 9],
			defense: [1, 2],
			addSpellIce: [6, 10],
		},
		{
			name: 'Charm',
			newName: 'Signet of the Scaled Order',
			mp: 25,
			offense: [1, 2],
			evocation: 2,
			resistSilence: 5,
			resistFear: 5,
			resistFire: 30,
			resistIce: 30,
		},
		{
			name: 'Charm',
			newName: 'Tempered Spirits',
			sta: [12, 16],
			wis: [8, 12],
			sp: 20,
			resistArcane: [28, 35],
			resistStun: [7, 10],
			mpRegen: [3, 5],
		},
		{
			name: 'Charm',
			newName: 'Clay of Everliving Golem',
			hp: 15,
			mp: 15,
			resistAll: [6, 10],
			hpRegen: [2, 4],
			offense: [1, 2],
			addSpellLightning: [7, 12],
		},
		{
			name: 'Charm',
			newName: 'Azulite\'s Breath',
			mpRegen: [4, 6],
			crit: [5, 8],
			resistSilence: [8, 12],
			allStats: [4, 6],
			damageTakenToSpirit: [2, 3],
			enhancedDamageToUndead: [4, 6],
		},
	]
}