loot.cloaks = {
	base: {
		slots: ['back'],
		armorType: 'cloth',
	},
	normal: [
		{
			name: 'Cape',
			minArmor: 1,
			maxArmor: 4,
			itemLevel: 1,
			armorType: 'cloth',
			imgIndex: 15,
		}, {
			name: 'Cloak',
			minArmor: 2,
			maxArmor: 5,
			itemLevel: 4,
			armorType: 'cloth',
			imgIndex: 1,
		}, {
			name: 'Woven Cloak',
			minArmor: 3,
			maxArmor: 6,
			itemLevel: 6,
			armorType: 'cloth',
			imgIndex: 2,
		}, {
			name: 'Fur-Lined Cloak',
			minArmor: 4,
			maxArmor: 8,
			itemLevel: 8,
			armorType: 'cloth',
			imgIndex: 3,
		}, {
			name: 'Drake-Hide Cloak',
			minArmor: 6,
			maxArmor: 10,
			itemLevel: 10,
			armorType: 'cloth',
			imgIndex: 4,
		}, {
			name: 'Brigand Shroud',
			minArmor: 7,
			maxArmor: 12,
			itemLevel: 12,
			armorType: 'cloth',
			imgIndex: 5,
		}, {
			name: 'Regal Shroud',
			minArmor: 6,
			maxArmor: 15,
			itemLevel: 15,
			armorType: 'cloth',
			imgIndex: 6,
		}, {
			name: 'Viceroy Cloak',
			minArmor: 8,
			maxArmor: 16,
			itemLevel: 18,
			armorType: 'cloth',
			imgIndex: 7,
		}, {
			name: 'Elven Shroud',
			minArmor: 8,
			maxArmor: 20,
			itemLevel: 20,
			armorType: 'cloth',
			imgIndex: 8,
		}, {
			name: 'Sylvan Cloak',
			minArmor: 10,
			maxArmor: 20,
			itemLevel: 22,
			armorType: 'cloth',
			imgIndex: 9,
		}, {
			name: 'Chlamys',
			minArmor: 12,
			maxArmor: 24,
			itemLevel: 24,
			armorType: 'cloth',
			imgIndex: 10,
		}, {
			name: 'Silk Cloak',
			minArmor: 16,
			maxArmor: 24,
			itemLevel: 26,
			armorType: 'cloth',
			imgIndex: 11,
		}, {
			name: 'Noble Cape',
			minArmor: 18,
			maxArmor: 25,
			itemLevel: 28,
			armorType: 'cloth',
			imgIndex: 12,
		}, {
			name: 'Ridged Shroud',
			minArmor: 20,
			maxArmor: 25,
			itemLevel: 30,
			armorType: 'cloth',
			imgIndex: 13,
		}, {
			name: 'Archon Cloak',
			minArmor: 22,
			maxArmor: 28,
			itemLevel: 32,
			armorType: 'cloth',
			imgIndex: 14,
		}, {
			name: 'Pall',
			minArmor: 24,
			maxArmor: 30,
			itemLevel: 34,
			armorType: 'cloth',
			imgIndex: 15,
		},
	],
	prefix: {
		resists: 40,
		spellPower: 40,
	},
	suffix: {
		stats: 12,
		allStats: 10,
		points: 30,
		crit: 20,
		ease: 2,
	},
	rare: {
		skills: 2,
		regen: 5
	},
	unique: [
		{
			name: 'Cape',
			newName: 'Arctic Cloak',
			attack: 5,
			dex: 5,
			evocation: 1,
			addSpellIce: [4, 7],
			resistIce: [12, 16],
			sp: [6, 9],
			spRegen: 2,
		}, {
			name: 'Cloak',
			newName: 'Lizardscale Cloak',
			mpKill: 2,
			intel: 7,
			alteration: [1, 2],
			crit: [4, 6],
			resistPoison: [12, 15],
			addSpellPoison: [6, 8],
			addSpellBlood: 4,
		}, {
			name: 'Woven Cloak',
			newName: 'Gossamer Cloak',
			dodge: 2,
			intel: [8, 12],
			wis: [7, 9],
			phyMit: 4,
			resistLightning: [17, 20],
			resistPoison: [11, 15],
		}, {
			name: 'Fur-Lined Cloak',
			newName: 'Singe\'s Copse',
			wis: [17, 20],
			addSpellFire: [16, 20],
			hpRegen: [2, 3],
			crit: 3,
			sp: [16, 20],
			spRegen: 4,
		}, {
			name: 'Drake-Hide Cloak',
			newName: 'Highwayman\'s Cloak',
			dex: 10,
			dodge: [1, 2],
			parry: 2,
			piercing: [2, 3],
			addSpellLightning: [12, 16],
			addSpellFire: [12, 16],
		}, {
			name: 'Brigand Shroud',
			newName: 'Cloak of the Polar Bear',
			hp: 20,
			addSpellIce: [33, 38],
			magMit: 2,
			twoHandSlash: 2,
			twoHandBlunt: 2,
			resistIce: [41, 50],
			sp: [11, 15],
		}, {
			name: 'Regal Shroud',
			newName: 'Molten Cloak',
			intel: [12, 15],
			addSpellFire: [28, 44],
			evocation: [1, 2],
			crit: 2,
			resistFire: [28, 35],
			cha: [13, 16],
		}, {
			name: 'Viceroy Cloak',
			newName: 'Ominous Shroud',
			hp: 45,
			str: 5,
			alteration: [2, 3],
			oneHandBlunt: 2,
			oneHandSlash: 2,
			piercing: 2,
			defense: [2, 3],
			addSpellBlood: [21, 25],
			addSpellPoison: [16, 32],
		}, {
			name: 'Elven Shroud',
			newName: 'Grovecaller\'s Shroud',
			conjuration: 2,
			addSpellLightning: [24, 35],
			agi: 12,
			dex: 15,
			oneHandSlash: [3, 5],
			resistFire: [16, 25],
			resistLightning: [16, 25],
			resistIce: [16, 25],
		}, {
			name: 'Sylvan Cloak',
			newName: 'Cloak of Leaves',
			wis: [11, 15],
			alteration: 3,
			conjuration: [1, 2],
			crit: [11, 15],
			resistLightning: [20, 25],
			resistPoison: [16, 20],
		}, {
			name: 'Chlamys',
			newName: 'Tribal Warfare Cloak',
			str: [13, 16],
			agi: [8, 12],
			piercing: [2, 3],
			alteration: [2, 3],
			crit: 5,
			resistAll: [8, 12],
		}, {
			name: 'Silk Cloak',
			newName: 'Cloak of Qalon',
			dex: [7, 10],
			agi: [7, 10],
			offense: 2,
			handToHand: [3, 5],
			oneHandSlash: [2, 3],
			resistFire: [21, 30],
			resistArcane: [21, 30],
			addSpellAll: [2, 4],
		}, {
			name: 'Noble Cape',
			newName: 'Magmashroud',
			dex: [16, 20],
			agi: [13, 16],
			handToHand: 4,
			offense: 3,
			addSpellFire: [27, 36],
			addSpellPoison: [15, 21],
			resistFire: 50,
		}, {
			name: 'Ridged Shroud',
			newName: 'Wyvern\'s Wing',
			defense: 6,
			hp: 20,
			agi: 25,
			alteration: [3, 5],
			crit: 10,
		}, {
			name: 'Archon Cloak',
			newName: 'Cloak of Icing Death',
			twoHandSlash: 3,
			allStats: [7, 10],
			magMit: 7,
			resistIce: [16, 20],
			addSpellIce: [33, 40],
			addSpellBlood: [28, 35],
			enhancedDamageToMystical: [3, 5],
		}, {
			name: 'Pall',
			newName: 'Soothsayer\'s Ethereal Cloak',
			resistAll: [8, 10],
			allStats: [8, 10],
			allSkills: 1,
			enhancedDamageToDragonkin: [7, 10],
			addSpellFire: [25, 32],
			addSpellIce: [15, 30],
			addSpellArcane: [21, 28],
		},
	]
}