loot.helms = {
	base: {
		slots: ['head'],
		armorType: 'cloth',
	},
	normal: [
		{
			name: 'Hood',
			minArmor: 1,
			maxArmor: 4,
			itemLevel: 1,
			armorType: 'cloth',
			imgIndex: 0,
		}, {
			name: 'Cap',
			minArmor: 1,
			maxArmor: 6,
			itemLevel: 1,
			armorType: 'leather',
			imgIndex: 1,
		}, {
			name: 'Bandana',
			minArmor: 2,
			maxArmor: 8,
			itemLevel: 5,
			armorType: 'cloth',
			imgIndex: 2,
		}, {
			name: 'Crown',
			minArmor: 4,
			maxArmor: 12,
			itemLevel: 10,
			armorType: 'cloth',
			imgIndex: 3,
		}, {
			name: 'Cowl',
			minArmor: 6,
			maxArmor: 12,
			itemLevel: 20,
			armorType: 'cloth',
			imgIndex: 4,
		}, {
			name: 'Coronet',
			minArmor: 10,
			maxArmor: 20,
			itemLevel: 24,
			armorType: 'cloth',
			imgIndex: 5,
		}, {
			name: 'Miter',
			minArmor: 12,
			maxArmor: 18,
			itemLevel: 26,
			armorType: 'cloth',
			imgIndex: 6,
		}, {
			name: 'Shroud',
			minArmor: 16,
			maxArmor: 24,
			itemLevel: 30,
			armorType: 'cloth',
			imgIndex: 7,
		}, {
			name: 'Helmet',
			minArmor: 20,
			maxArmor: 40,
			itemLevel: 12,
			armorType: 'leather',
			imgIndex: 8,
		}, {
			name: 'Shako',
			minArmor: 35,
			maxArmor: 50,
			itemLevel: 15,
			armorType: 'leather',
			imgIndex: 9,
		}, {
			name: 'Coif',
			minArmor: 42,
			maxArmor: 60,
			itemLevel: 6,
			armorType: 'mail',
			imgIndex: 10,
		}, {
			name: 'Sallet',
			minArmor: 60,
			maxArmor: 75,
			itemLevel: 30,
			armorType: 'mail',
			imgIndex: 11,
		}, {
			name: 'Burgonet',
			minArmor: 50,
			maxArmor: 70,
			itemLevel: 6,
			armorType: 'plate',
			imgIndex: 12,
		}, {
			name: 'Great Helm',
			minArmor: 66,
			maxArmor: 83,
			itemLevel: 16,
			armorType: 'plate',
			imgIndex: 13,
		}, {
			name: 'Barbute',
			minArmor: 78,
			maxArmor: 92,
			itemLevel: 26,
			armorType: 'plate',
			imgIndex: 14,
		}, {
			name: 'Royal Helm',
			minArmor: 84,
			maxArmor: 100,
			itemLevel: 34,
			armorType: 'plate',
			imgIndex: 15,
		},
	],
	prefix: {
		resists: 30,
		enhancedArmor: 100,
	},
	suffix: {
		stats: 30,
		points: 40,
		crit: 40,
		ease: 2,
	},
	rare: {
		skills: 3,
		allSkills: 2
	},
	unique: [
		{
			name: 'Hood',
			newName: 'Glyphed Cowl',
			intel: 5,
			wis: 5,
			evocation: 1,
			conjuration: 1,
			allStats: [2, 3],
			mp: [6, 10],
		}, {
			name: 'Cap',
			newName: 'Rendo\'s Bonnet',
			itemLevel: 1,
			enhancedArmor: [10, 20],
			defense: 1,
			sp: [4, 8],
			hp: [6, 10],
			mp: [6, 10],
		}, {
			name: 'Bandana',
			newName: 'Laozen\'s Headband',
			enhancedArmor: [40, 50],
			handToHand: [3, 5],
			offense: [4, 6],
			addSpellLightning: [6, 8],
			hp: [20, 25],
			agi: [35, 40],
			hpKill: 6,
		}, /*{
			name: 'Bandana',
			newName: 'Samurai\'s Devotion',
			odds: 0,
			enhancedArmor: [15, 20],
			dex: [6, 9],
			str: [6, 9],
			resistAll: [4, 6],
			itemLevel: 5,
			rarity: 'set',
		},*/ {
			name: 'Crown',
			newName: 'Grandmaster\'s Crown',
			enhancedArmor: [40, 60],
			offense: [2, 3],
			defense: [2, 3],
			handToHand: [2, 3],
			allSkills: 1,
			resistAll: 7,
		}, {
			name: 'Cowl',
			newName: 'Reaper\'s Cown',
			enhancedArmor: [50, 75],
			conjuration: 3,
			mpKill: 6,
			hp: [15, 20],
			mp: [20, 30],
			crit: [12, 16],
		}, {
			name: 'Cowl',
			newName: 'Executioner\'s Hood',
			enhancedArmor: [75, 90],
			offense: 3,
			str: [15, 20],
			dex: [15, 20],
			crit: [15, 20],
			twoHandSlash: [2, 3],
		}, {
			name: 'Coronet',
			newName: 'Crown of King Argentus',
			enhancedArmor: 80,
			alteration: 3,
			addSpellArcane: 10,
			resistArcane: 35,
			resistIce: 20,
			cha: [15, 20],
			twoHandBlunt: 5,
		}, {
			name: 'Miter',
			newName: 'Summoner\'s Beacon',
			enhancedArmor: [60, 70],
			conjuration: 3,
			evocation: [1, 2],
			hp: [20, 25],
			sp: [20, 25],
			hpKill: [3, 5],
			resistAll: [6, 10],
			dodge: [1, 2],
		}, /*{
			name: 'Miter',
			newName: 'Orator\'s Shout',
			itemLevel: 26,
			itemLevel: 26,
			itemLevel: 26,
			itemLevel: 26,
			itemLevel: 26,
			itemLevel: 26,
			itemLevel: 26,
			itemLevel: 26,
			itemLevel: 26,
			rarity: 'set',
		},*/ {
			name: 'Shroud',
			newName: 'Dragon Lord\'s Cowl',
			enhancedArmor: [75, 85],
			resistFire: [33, 45],
			evocation: [3, 4],
			enhanceFire: [3, 5],
			defense: 2,
			hp: [15, 30],
			mp: [33, 45],
			crit: 12,
		}, {
			name: 'Helmet',
			newName: 'Windstalker\'s Malice',
			enhancedArmor: [45, 65],
			offense: 2,
			allSkills: 2,
			oneHandSlash: 3,
			resistAll: 7,
			riposte: 5,
			parry: 2,
		}, /*{
			name: 'Helmet',
			newName: 'Sage\'s Vision',
			enhancedArmor: [40, 50],
			allSkills: [1, 2],
			hp: [20, 40],
			mp: [40, 50],
			mpKill: 3,
			crit: [20, 25],
			rarity: 'set',
		},*/ {
			name: 'Shako',
			newName: 'Pride of Fenwoven',
			enhancedArmor: [65, 80],
			conjuration: [4, 6],
			alteration: [4, 6],
			wis: [12, 20],
			resistFire: [26, 35],
			resistLightning: [30, 40],
			resistIce: [26, 35],
			sp: [27, 36],
			spRegen: [2, 3],
		}, {
			name: 'Coif',
			newName: 'Coif of Glory',
			enhancedArmor: [75, 85],
			allSkills: 1,
			resistLightning: 50,
			resistBlood: [25, 35],
			hpKill: 3,
			hpKill: 3,
			hp: 20,
			sp: [20, 30],
			hpRegen: 2,
		}, {
			name: 'Sallet',
			newName: 'Dusky Visor',
			enhancedArmor: [85, 95],
			magMit: [5, 7],
			phyMit: [2, 4],
			addSpellArcane: [4, 6],
			addSpellBlood: [3, 5],
			offense: [2, 3],
			sta: [18, 24],
			wis: [15, 20],
		}, {
			name: 'Burgonet',
			newName: 'Crested Helm',
			enhancedArmor : [88, 94],
			allSkills: 1,
			str: [20, 25],
			sta: [16, 24],
			cha: [27, 35],
			alteration: [2, 3],
			addSpellLightning: [8, 12],
			enhancedDamageToUndead: [6, 10],
		}, {
			name: 'Great Helm',
			newName: 'Call of the Hero',
			enhancedArmor: [85, 96],
			alteration: [2, 4],
			evocation: [3, 5],
			allStats: [7, 10],
			addSpellIce: [5, 8],
			hpKill: 5,
			enhancedDamageToDragonkin: [7, 12],
			hp: [40, 50],
			sp: [24, 30],
		},
		/*{
			name: 'Great Helm',
			newName: 'Minotaur\'s Horns',
			itemLevel: 30,
			itemLevel: 30,
			itemLevel: 30,
			itemLevel: 30,
			itemLevel: 30,
			itemLevel: 30,
			itemLevel: 30,
			itemLevel: 30,
			rarity: 'set',
		},*/
		{
			name: 'Barbute',
			newName: 'Wurmskull Barbute',
			enhancedArmor: [96, 110],
			twoHandSlash: 7,
			twoHandBlunt: 7,
			resistArcane: [31, 36],
			str: [21, 25],
			hp: [28, 35],
			sp: 33,
			addSpellPoison: [7, 9],
			addSpellBlood: [4, 6]
		}, {
			name: 'Royal Helm',
			newName: 'Vor\'s Adulation',
			enhancedArmor: [91, 100],
			defense: [4, 5],
			resistAll: [9, 12],
			allStats: [6, 8],
			wraith: [3, 4],
			hpRegen: 2,
			addSpellFire: [4, 6],
			addSpellArcane: [3, 5],
		},
	],
}