items.rings = {
	base: {
		slots: ['fingers']
	},
	normal: [
		{
			name: 'Ring',
			itemLevel: 1,
		}
	],
	prefix: {
		resists: 40,
		resistAll: 15,
		spellPower: 20,
	},
	suffix: {
		stats: 30,
		allStats: 15,
		points: 20,
		crit: 10,
		regen: 5,
		leech: 5,
		wraith: 5,
	},
	rare: {
		skills: 2,
		addDamage: 5,
	},
	unique: [
		{
			name: 'Ring',
			newName: 'Stone of Artremia',
			allSkills: 1,
			mpKill: 5,
			addBlood: [2, 4],
			mp: [7, 10],
			wraith: [2, 3],
			resistBlood: [10, 15],
			itemLevel: 3,
		}, {
			name: 'Ring',
			newName: 'Jagged Band',
			str: [10, 15],
			armor: 7,
			parry: 3,
			crit: [3, 5],
			defense: [1, 2],
			hp: 10,
			addBlood: [2, 3],
			itemLevel: 5,
		}, {
			name: 'Ring',
			newName: 'Ring of Howling Thicke',
			armor: 6,
			dex: 5,
			wis: 10,
			intel: [6, 10],
			resistPoison: 25,
			wraith: 3,
			alteration: [1, 2],
			itemLevel: 7,
		}, {
			name: 'Ring',
			newName: 'Beryl Skull Ring',
			hp: [8, 12],
			mp: [8, 12],
			sp: [8, 12],
			cha: 7,
			hpKill: 7,
			leech: 3,
			crit: [3, 5],
			addBlood: [2, 3],
			itemLevel: 10,
		}, {
			name: 'Ring',
			newName: 'Blazing Star',
			hp: 15,
			dodge: 2,
			magMit: 5,
			addSpellFire: [7, 12],
			resistFire: 25,
			resistArcane: 10,
			sp: 12,
			itemLevel: 12,
		}, {
			name: 'Ring',
			newName: 'Crow\'s Frost',
			attack: [10, 15],
			addIce: [3, 5],
			addSpellIce: [8, 14],
			dex: [10, 15],
			mp: [12, 15],
			spKill: [3, 5],
			resistIce: [20, 30],
			itemLevel: 15,
		}, {
			name: 'Ring',
			newName: 'Moonstone Band',
			str: [5, 8],
			wis: 12,
			mp: [15, 20],
			sp: [5, 10],
			evocation: [2, 3],
			alteration: [2, 3],
			conjuration: [2, 3],
			resistBlood: 15,
			itemLevel: 18,
		}, {
			name: 'Ring',
			newName: 'Ovext\'s Amethyst Ring',
			hp: 25,
			agi: 15,
			dex: 5,
			crit: [12, 16],
			resistFire: [20, 30],
			resistPoison: [20, 30],
			wraith: [2, 4],
			itemLevel: 20,
		}, {
			name: 'Ring',
			newName: 'Gronk\'s Wedding Ring',
			str: [15, 20],
			attack: [5, 10],
			hp: 15,
			crit: [8, 12],
			resistBlood: [24, 30],
			riposte: [2, 3],
			cannotBeStunned: true,
			itemLevel: 22,
		}, {
			name: 'Ring',
			newName: 'Band of Screaming Winds',
			hp: 15,
			sp: [16, 24],
			resistLightning: [16, 20],
			resistArcane: [11, 15],
			crit: [5, 7],
			oneHandBlunt: 3,
			alteration: [1, 2],
			itemLevel: 24,
		}, {
			name: 'Ring',
			newName: 'Ring of Rainbow Skies',
			offense: [2, 3],
			conjuration: [2, 3],
			allStats: [7, 10],
			resistAll: [10, 12],
			addSpellLightning: [7, 11],
			addSpellArcane: [7, 11],
			itemLevel: 26,
		}, {
			name: 'Ring',
			newName: 'Elusive Warping Ring',
			dodge: 5,
			defense: 2,
			dex: [9, 12],
			agi: [12, 15],
			phyMit: [3, 5],
			parry: [3, 5],
			riposte: [2, 3],
			hpRegen: 3,
			itemLevel: 28,
		}, {
			name: 'Ring',
			newName: 'Titan\'s Wrath',
			str: [24, 30],
			sta: [13, 16],
			hp: [17, 20],
			crit: 3,
			allSkills: 1,
			attack: 12,
			itemLevel: 32,
		},
	]
}